### ISSUE TITLE
Bug navigation sur le parcours j'ai un projet en tête

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1025]
Lorsque j'arrive sur la page de résultats du parcours j'ai un projet en tête, le clic sur "questionnaire" dans le fil d'ariane ne fonctionne pas. 
Pour info, il s'agit d'un parcours ou j'ai rensigné les informations manuellement (sans siret)

https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat?choix-du-parcours=j-ai-un-projet&siret=siret-non-renseigne&effectif=ME&activite=tourisme&region=Centre-Val+de+Loire&objectifs=r%C3%A9nover+mon+b%C3%A2timent#questionnaire-resultat
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/970
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/993
```

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux : à tester ici >> https://tee-preprod-pr1080.osc-fr1.scalingo.io/
