### ISSUE TITLE
Revoir le hover des cartes projets

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1031]
- [ ] Revoir l'effet visuel du hover, à mettrre à l'intérieur de la carte (cf carte dispositifs)

objectif : 
- harmoniser l'effet visuel utilisé en hover sur la plateforme
- le rendu de l'effet sur la carte projet n'est pas beau sur un fond de couleur 

cf capture d'ecran : 
![Image](https://github.com/user-attachments/assets/57616aa4-e501-4bf8-919b-a4d67fd87143)

**Comment by ColineLebaratoux** [comment]
@dolemoine

**Comment by dolemoine** [comment]
@ColineLebaratoux le lien pour test : https://tee-preprod-pr1077.osc-fr1.scalingo.io/

page résultat sur les 2 parcours :
    [page résultat "Je ne sais pas par où commencer"](https://tee-preprod-pr1077.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=siret-non-renseigne&effectif=ETI_GE&activite=industrie&region=Auvergne-Rh%C3%B4ne-Alpes&locaux=proprietaire-et-locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=oui&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat)
    [page résultat "j'ai un projet en tête"](https://tee-preprod-pr1077.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=j-ai-un-projet&siret=siret-non-renseigne&effectif=ME&activite=tourisme&region=Auvergne-Rh%C3%B4ne-Alpes&objectifs=ma+performance+%C3%A9nerg%C3%A9tique#questionnaire-resultat)
