### ISSUE TITLE
Uniformiser l'affichage de la ThemeHeaderCard

### ISSUE THREAD

**Issue by dolemoine** [betagouv/mission-transition-ecologique#1048]
Le bandeau de thématique présente des affichages incohérents du à l'obligation de définir la propriété "titre" du composant `DsfrCard`: 

![Image](https://github.com/user-attachments/assets/813aba32-7d17-454c-a4f8-32a57c531198)

![Image](https://github.com/user-attachments/assets/72975a60-8bcf-40c4-ba14-9a52dc489ab3)

**Comment by dolemoine** [comment]
@ColineLebaratoux le résultat attendu est bien celui des maquettes ?

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine ! Oui [cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6780-379362&t=y1SJ4t4AcmRo3Kl4-1)

**Comment by dolemoine** [comment]
@ColineLebaratoux url pour test : https://tee-preprod-pr1077.osc-fr1.scalingo.io/
