### ISSUE TITLE
Bug: filtre programmes/dispositifs

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#1076]
- [x] Lorsque l'on est sur la page des resulats d'un parcours et que l'on affiche la liste des programmes avec un fitre donnant aucun resultat, un problème d'affichage est présent car les filtres se retrouvent en dessous du message indiquant qu'il n'y a pas de résultat

![Image](https://github.com/user-attachments/assets/78de7d13-fe0f-4509-bfe1-d9ad268c692a)

- [x] Il est nécessaire de corriger le message d'erreur sur l'onglet "vos aides financières". Sur les idées d'actions à mettre en place il est centré et a la bonne taille. 

- Lorsque l'on est sur la liste des programmes depuis le catalogue et que l'on a un filtre affichant aucun résultat, aucun message n'est affiché (@ColineLebaratoux peut être que c'est normal ?)

![Image](https://github.com/user-attachments/assets/a6052d0c-ae13-4700-9ec0-7a67d9dae1ec)

**Comment by ColineLebaratoux** [comment]
> Lorsque l'on est sur la liste des programmes depuis le catalogue et que l'on a un filtre affichant aucun résultat, aucun message n'est affiché (@ColineLebaratoux peut être que c'est normal ?)
non il devrait y avoir le message : 
<img width="670" alt="Capture d’écran 2024-09-11 à 14 37 27" src="https://github.com/user-attachments/assets/485de07f-dece-4b5b-929c-7ed16490b499">

**Comment by ColineLebaratoux** [comment]
bug relevé par @yvalentin 
le message d'erreur ne s'affiche pas. 
Test sur le catalogue des aides https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise
filtré sur prêt + DDFIP = aucun résutat = manque le message

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani @dolemoine est-ce que l'un d'entre vous peut prendre ce bug dans sa to do ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux à tester ici >> https://tee-preprod-pr1184.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani, 
Correction mobile : 

- [ ] Le message d'erreur fait disparaitre les tags thématiques et déplace le bouton "filtre" sur le bas 

![IMG_8587](https://github.com/user-attachments/assets/35736158-94d9-41a4-a4b1-e46da6615755)
![IMG_8588](https://github.com/user-attachments/assets/49c964b7-1bfb-469a-af23-a5292199e86d)


Quelques correction UI :

- [ ] Peux-tu harmoniser le placement du message sur les deux onglets ?
https://github.com/user-attachments/assets/07e12699-6418-47c8-a00b-a4572a4ec998

- [ ] Peux-tu diminuer la taille de l'illustration et du message (objectif : pouvoir le voir entièrement au dessus de la ligne de flottaison)
actuel 
<img width="1333" alt="Capture d’écran 2024-10-03 à 09 26 44" src="https://github.com/user-attachments/assets/e64e8c31-5cec-42f4-a144-cfa9338be91a">
cible
<img width="724" alt="Capture d’écran 2024-10-03 à 09 26 33" src="https://github.com/user-attachments/assets/72a5b840-0053-450a-88dc-e0708709f2d7">

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux nouveaux changements https://tee-preprod-pr1184.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani, quelques dernières petites corrections : 

- [ ] Sur mobile, remonter l'illustration 
<img width="348" alt="Capture d’écran 2024-10-04 à 09 31 01" src="https://github.com/user-attachments/assets/c45cc7e5-a687-49ff-905b-888d06d50d86">

- [ ] Sur desktop, contraindre le texte à passer sur deux lignes avec une césure après "identifiée" (cf maquette)

**Comment by oumeimaelisbihani** [comment]
c'est ici >> https://tee-preprod-pr1184.osc-fr1.scalingo.io/ @ColineLebaratoux

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani, est-ce que tu peux faire cette modif sur les autres tailles d'écran ?
A partir d'une largeur de 767 il repasse sur une ligne 

> contraindre le texte à passer sur deux lignes avec une césure après "identifiée" (cf maquette)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux la je pense que c'est mieux : https://tee-preprod-pr1184.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
merci !
