### ISSUE TITLE
Ne pas afficher la thématique rénovation si l'utilisateur ne dispose pas de locaux pro

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1078]
Dans le questionnaire "je ne sais pas par ou commencer" si l'utilisateur sélectionne "Je ne dispose pas de locaux professionnels", il n'y a pas d'interet de lui proposer le tag thématique rénovation.

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1183.osc-fr1.scalingo.io/

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux suite à la revue technique, une question : est ce que ça concernerait aussi les gens locataires de leurs locaux ?

**Comment by ColineLebaratoux** [comment]
Bonne question, je suis d'accord la thématique rénovation n'est pas vraiment pertinente pour les locataires. 

ça ouvre une autre question, pourquoi on retrouve des des projets de type "maitrise des besoins de chauffages" "sèche linge" "frigo" dans rénovation ? @jbledevehat on pourrait les laisser uniquement dans la thématique énergie ces projets tu ne penses pas ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux @jbledevehat est ce qu'il faudrait pas ajouter pour les aides : Diagnostic SARE, coup de pouce chauffage, installation de panneaux photovoltaique, Crédit d'Impôt Rénovation Énergétique (CIRE), Sites touristiques exemplaires comme critères d'éligibilité le fait d'être propriétaire ou propriétaire+locataire de ses locaux ?
