### ISSUE TITLE
Amélioration de la gestion des images (baserow)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1081]
Les mêmes images apparaissent pour les projets sensibilisation des équipes et stratégie RSE 
![Image](https://github.com/user-attachments/assets/b8a93031-6d33-45ea-8acd-8638014da622)

or l'image de stratégie RSE est : 

![Image](https://github.com/user-attachments/assets/9d81178d-c614-4d58-9ff1-5e82873e9735)

**Comment by ttdm** [comment]
C'est parce que le champ "image URL TEE" de la table image est "sensibilisation-equipes". Je viens de le changer. 
Je laisse le ticket ouvert pour garder en tête d'améliorer la gestion des images. 

Tech only : Deux pistes pour régler ce problème : 
1. reprendre directement le nom des images, après vérification, c'est finalement possible
2.  vérifier que les slugs (ou les noms) sont uniques et dans le cas contraire, append -x au nom pour forcer l'unicité.
