### ISSUE TITLE
Mettre à jour lib et nx 

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#1100]

**Comment by yvalentin** [comment]
Pour recette complete car mise à jours important des lib en dépendance du projet

https://tee-preprod-pr1098.osc-fr1.scalingo.io/

**Comment by yvalentin** [comment]
@jbledevehat ou @coline Si vous avez un moment pour faire un checkup ?
L'url est encore up

https://tee-preprod-pr1098.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@yvalentin Qu'est-ce que je dois vérifier ?

**Comment by yvalentin** [comment]
@ColineLebaratoux C'est une mise à jours important des librairies externes que l'on utilise.

Du coup, l'idée est de vérifier que globalement tout fonctionne. J'ai déjà fais un tour. Mais c"est bien si on est plusieurs à faire la vérification approfondie.
Merci
