### ISSUE TITLE
Sur un projet, afficher tous les dispositifs liés, si aucune data entreprise

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1101]
Sur une page projet, 

si l'utilisateur n'a pas renseigné son SIRET - s'il passe directement depuis le catalogue des projets - alors 
1. Ne pas afficher le formulaire, et,
2. Afficher toutes la liste des dispositifs entre le titre "Mes aides" et l'encarte "Complétez votre profil en 2 minutes..." 
![Image](https://github.com/user-attachments/assets/217b51da-ace7-4037-8ee5-e4bf9e262289)

sinon comme actuellement afficher les dispositifs le concernant ET afficher le formulaire
```[tasklist]
### Tasks
```

**Comment by jbledevehat** [comment]
@ColineLebaratoux pour info

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1125.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
good !

en revanche, pendant le temps de chargement de la liste, j'ai pu voir le message et l'illustration "aucune aide n'a été trouvée avec les critères selectionnés". est-ce qu'on peut virer ça et mettre un petit loader si ça prend du temps ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1125.osc-fr1.scalingo.io/ voila avec les fix !

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani ! 
ça fonctionne bien 👍
Je me dis juste que le temps de chargement est assez long. Notamment quand on a cliqué sur une carte dispositif depuis une fiche projet et qu'on fait un retour arrière sur la fiche projet

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1125.osc-fr1.scalingo.io/ j'ai ajouté le fil d'ariane comme il faut catalog > nom du projet > nom du dispositif. Pour le temps de chargement j'ai l'impression que c'est que sur scalingo, en local ça charge nickel

**Comment by ColineLebaratoux** [comment]
merco @oumeimaelisbihani 
Est-ce que tu peux faire la même correction sur les fiches procjets consultées via les parcours "jai un projet en tête" "je ne sais pas par ou commencer"
ex : https://tee-preprod-pr1125.osc-fr1.scalingo.io/questionnaire/resultat/pret-vert?choix-du-parcours=j-ai-un-projet&siret=35333323000012&effectif=ETI_GE&objectifs=building

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux je le fais sur l'autre ticket ! histoire de bien rester sur un seul sujet par ticket

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux du coup c'est bien valid ? je peux changer le tag si tu veux
