### ISSUE TITLE
Je clique sur un projet ayant aucune aides disponible me concernant >> Afficher un message

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1104]
En tant qu'entreprise, je consulte une page projet dont aucune aide me concerne (non-éligiblité) => alors afficher non pas un échec mais... 
- une message d'encouragement même si aucun dispositif d'aide possible ?
- un message pour aller voir un conseiller ?

proposition : 
@jbledevehat tu en penses quoi ?

> "Nous n'avons identifié aucune aide publique pour la mise en œuvre de votre projet de "...". N'hésitez pas à nous contacter pour discuter de votre projet et explorer ensemble d'autres solutions de financement possibles."

ou dans la mesure où nous admettons ne pas intégrer l'exhaustivité des aides : 
> "Nous n'avons trouvé aucune aide publique pour votre projet pour le moment. Toutefois, nos conseillers peuvent vous informer sur des aides régionales ou territoriales. Contactez-nous pour explorer ensemble d'autres solutions de financement."

ou plus simple
✅ > "Nous n'avons pas trouvé d’aide éligible à votre entreprise pour votre projet de “Réduction des emballages”.
Nous vous invitons à nous contacter pour explorer ensemble d'autres solutions de financement."

[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7768-419961&t=S8ujsE4aXyZq3RY7-1)
![Image](https://github.com/user-attachments/assets/f6f1bcd8-2176-4798-966d-ac3fa0b01bf4)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1150
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1245
```

**Comment by ColineLebaratoux** [comment]
@jbledevehat a priori aujourd'hui, si un projet est affiché c'est qu'un dispositif y est associé. Donc, si je ne me trompe pas, il n'y a pas d'occasion pour afficher ce message. 

A part si on change nos règles d'affichage des projets ?

**Comment by ColineLebaratoux** [comment]
Proposition : 

![Image](https://github.com/user-attachments/assets/282b3cc4-d1e2-495d-883c-bf3413f72ba6)

**Comment by ColineLebaratoux** [comment]
![Image](https://github.com/user-attachments/assets/831d8104-a7b4-4464-a6b3-bcc10375f5a3)

**Comment by ColineLebaratoux** [comment]
@jbledevehat tu en penses quoi ?
"Nous n'avons identifié aucune aide publique pour la mise en œuvre de votre projet de "...". 
N'hésitez pas à nous contacter pour discuter de votre projet et explorer ensemble d'autres solutions de financement possibles."
