### ISSUE TITLE
Je renseigne mon SIRET mais mon lieu d'activité n'est pas le lieu de domiciliation

### ISSUE THREAD

**Issue by mpiac** [betagouv/mission-transition-ecologique#1106]
Cas concret : 
Hôtel Martinez a une entreprise domiciliée à Paris bien que le lieu d'activité soit à Cannes > Si je remplis le formulaire avec le siret, certaines aides ne me sont donc pas proposées (les aides de la Région par exemple qui sont destinées aux entreprises dont l'activité est en Région)
> Peut-on ajouter lieu d'activité si différent dans le formulaire ? Est-ce qu'on considère que ce sont des cas exceptionnels ? Quelle est la proportion d'entreprises concernées ?

**Comment by ColineLebaratoux** [comment]
Une solution pourrait être de faire évoluer la saisie de l'étape SIRET : 

au clic sur la croix d'un tag, on arrive sur un menu déroulant pour corriger l'info SIRET. (du coup on peut gérer l'effectif de cette manière)
![Image](https://github.com/user-attachments/assets/ffe6e3c6-7a1e-4097-9d9f-eac2d086cac2)

![Image](https://github.com/user-attachments/assets/1d88b1c3-2bb9-4fcd-a9d2-c7e4ca640211)


[cf discussion sur ce ticket](https://github.com/betagouv/mission-transition-ecologique/issues/1105#issuecomment-2397026167)
