### ISSUE TITLE
Mettre en place le funnel PostHog

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1111]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1207
```

**Comment by jrayneau** [comment]
J'ai configuré sur PostHog le funnel de conversion du questionnaire, il est visible dans l'insights "Funnel Questionnaire". Les demandes sont les demandes de dispositifs et de projets (hors catalogue)
![Image](https://github.com/user-attachments/assets/b2670961-430e-4c28-be91-885461de9251)

**Comment by jrayneau** [comment]
Ca serait utile d'ajouter l'étape page de Détail (de dispositif ou de projets)
