### ISSUE TITLE
Filtrer les aides sur l'opérateur avec une donnée consolidiée

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1121]
Sur l'annuaire des aides, la liste des opérateurs pour filtrer les aides est étonnante (manquante de donnée, trop spéfique pour certain, ex : Breizh Fab...)

- [x] Ajouter la donnée souhaité à l'affichage sur le tableau des opérateurs - https://baserow.io/database/114839/table/314410/539018
- [ ] Intégrer cette liste d'opérateur à la place de la liste existante

**Comment by ttdm** [comment]
Testable sur : https://tee-preprod-pr1200.osc-fr1.scalingo.io/aides-entreprise

Comme discuté : les opérateurs sont maintenant dynamiques et se mettent directement en prod depuis la base de donnée baserow. 
(Mise à jour éxécutée en même temps que la mise à jour des programmes). 

Le filtre a été réalisé à la fois sur l'opérateur de contact et les opérateurs secondaire. Dans le cas contraire, il n'y a aucun dispostif pour l'agence de l'eau ce qui fait un peu bizarre pour l'utilisateur. 
J'ai rajouté un message dans la colonne filtre de la table baserow pour bien dire que toutes les valeurs listée dans la colonne doivent être liées à un programme en prod pour ne pas avoir d'option de filtrage vide.

**Comment by jbledevehat** [comment]
Peux-tu recharger la liste stp ? Car j'ai apporté des modifications des noms d'opérateurs.

**Comment by ttdm** [comment]
@jbledevehat tu peux voir la donnée à jour sur l'url au dessus !

**Comment by jbledevehat** [comment]
A communiquer aux opérateurs quand en prod
