### ISSUE TITLE
Vérification des liens CCI

### ISSUE THREAD

**Issue by ttdm** [betagouv/mission-transition-ecologique#1123]
Le site CCI est configuré pour refuser les visites des robots ce qui complexifie la vérification des liens. 
ça simplifierai notre process de vérification si la CCI nous autorisait à visiter leur site automatiquement.

**Comment by jbledevehat** [comment]
@ttdm peux-tu me donner des exemples de liens stp pour illustrer la demande ?

**Comment by ttdm** [comment]
c'est vraiment tous les liens cci donc par exemple :
https://www.cci.fr/offre/valorisez-les-demarches-environnementales-de-votre-entreprise et https://www.cci.fr/ressources/developpement-durable/contacts-developpement-durable
https://www.cci.fr/ressources/developpement-durable/cfde
On a une 20aine de liens référencés qui appartiennent à la CCI. 

 Après j'ai mis en place une solution qui simule un navigateur et des actions humaines et qui permet de contourner le problème. 
 Ce serait mieux si on avait l'autorisation de visiter leur site avec un robot mais c'est vraiment pas très important.
