### ISSUE TITLE
Parcours j'ai un projet en tête : ajouter un loader pour le temps de chargement avant le choix de la thématique

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1146]
Sur le parcours j'ai un projet en tête, ajouter un loader pour le temps de chargement avant le choix de la thématique
![Image](https://github.com/user-attachments/assets/777fb6b5-d6e5-4931-9547-4393de89dd49)

**Comment by yvalentin** [comment]
Testable sur le même PR que pour le remplaceement des  icones du dsfr #1224 

https://dashboard.scalingo.com/apps/osc-fr1/tee-preprod-pr1222

**Comment by ColineLebaratoux** [comment]
zut, j'ai loupé l'occasion de tester ce ticket. Tu veux bien régénérer ce lien stp @yvalentin ?

**Comment by ttdm** [comment]
En reprenant toutes mes notifs de retour de vacances, je viens de tomber la dessus et de relancer la review apps @ColineLebaratoux
