### ISSUE TITLE
Revoir les conditions d'affichage des projets, à afficher même si aucun dispositif n'est éligible pour l'entreprise

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1150]
Irritant : 
- [ ] Aujourd'hui, même si un projet peut être pertinent pour une entreprise, nous ne l'affichons uniquement si un dispositif est lié. Or, il pourrait être interessant de lui présenter tous les projets qui le concerne, même si aucune aide n'est dispo pour lui. 
- [ ] A l'inverse toutes les entreprises à Cannes verront les projets liés à la restauration car rattaché à une aides régions PACA pour tous secteurs d'activité
- [ ] Aujourd'hui, on offre un affichage deceptif pour l'utilisateur : il visualise une thématique vide quand aucun dispositif n'est lié à un projet de la thématique
![Image](https://github.com/user-attachments/assets/8755b078-61fe-4424-95d7-d3ad9289871d)

proposition : 
- [ ] dissocier l'affichage des projets selon l'existence de dispositifs éligible 
- [ ] mettre en place un champ sectoriel pour les projets qui conditionnerait leur affichage

ticket lié #1149

**Comment by ColineLebaratoux** [comment]
tu en penses quoi @ttdm ?

**Comment by jbledevehat** [comment]
J'ai ajouté un point (2ème case à cocher) @ColineLebaratoux

**Comment by ColineLebaratoux** [comment]
Mais oui, bien vu. ça ne va pas du tout 😅

**Comment by ttdm** [comment]
D'un point de vue général, les conditions d'affichage des projets semblent être un sujet peu clair. Voir par exemple le message de Celine sur le mattermost qui s'étonne que des entreprises de la réunion voient des projets ajoutés pour l'expé de cannes.
Il me semble qu'il faut faire quelque chose sur le sujet. 
Je vois deux solutions : 
- créer un filtrage des projets et donc pour être cohérent, cela voudrait dire étendre publicodes aux projets (on pourrait faire sans publicodes mais au minimum, si on commence à multiplier les projets et à filtrer dessus, il faudrait que le filtrage passe du front au back et c'est du travail)
- créer des personas avec une 20aines d'entreprises et un tableau de bord qui permet de voir facilement ce que telle ou telle entreprise verrait. 
Les deux solutions sont applicables en parallèles. Il s'agit de deux gros chantiers. 

Pour le reste c'est beaucoup des choix de design: 
1. je ne suis pas très fan de montrer le projet si aucune aide n'est disponible. En temps qu'utilisateur, ça m'inciterai à me renseigner dessus pour ensuite découvrir que je ne peux pas être aidé sur le sujet, frustrant ! Peut être afficher le projet tout en modifiant son style pour qu'il soit clair qu'aucune aide liée n'est dispo ? et avec un bandeau gris dès l'ouverture du projet ? (On pourrait même imaginer un CTA, "laissez nous votre mail pour que l'on vous contacte dès qu'un dispositif auxquel vous êtes éligible liée à ce projet sera recensée")
2. effectivement les projets sont pour l'instant plutôt plus visible que ce l'on pourrait croire. 
3. Si on garde le fonctionnement actuel avec un filtrage, je suis 100% d'accord qu'il faudrait cacher la thématique si aucun projet n'est éligible.

**Comment by ColineLebaratoux** [comment]
Merci @ttdm 
Je veux bien participer à un point sur le sujet avec @jbledevehat et peut-être @mpiac ?

Pour répondre à ton point 1 : 
1. Notre plateforme a également un rôle inspirationnel pour les entreprises qui n'ont pas de projets en tête, donc c'est chouette de pouvoir leur montrer les projets prioritaires à mener pour leur secteur d'activité, même s'il n'y a pas encore d'aide pour les accompagner. 
Mais oui, il faut réflechir à un message à afficher pour informer l'utilisateur et aussi lui donner une solution de repli. Exemple : contacter la région. (puisque nous n'avons pas encore intégré tous les dispositifs régionaux, il reste toujours une chance du côté de la région. A discuter avec l'équipe bizdev)
![Capture d’écran 2024-09-30 à 11 56 38](https://github.com/user-attachments/assets/aa074f0d-e4eb-481a-b607-99644c4b41a7)

**Comment by ttdm** [comment]
@ColineLebaratoux 
@jbledevehat 
La PR est prête et peut être review sur https://tee-preprod-pr1213.osc-fr1.scalingo.io/
Par contre pour ne pas voir tous les projets tous le temps, il faut modifier les secteurs des projets dans la table correspondante sur baserow !

**Comment by jbledevehat** [comment]
@ttdm Est-ce que tu peux mettre les mêmes noms de secteur que sur les programs stp. Car juste une lettre ne permet pas de savoir son nom.

**Comment by ttdm** [comment]
@jbledevehat  tu as vu que le détail des secteurs est en description ? 
Tu confirmes que tu préfères que ce soit fait dans le nom directement ?

**Comment by ttdm** [comment]
@jbledevehat @mpiac  les noms des colonnes baserow ont été mises à jour. Vous pouvez effectuer les modifications sur les données. Faites moi signe quand ce sera OK !

**Comment by jbledevehat** [comment]
@ttdm C'est bon pour moi... Peux-tu régénérer le lien stp pour tester ?

**Comment by ttdm** [comment]
Je viens de voir le message de JB et de faire la maj des projets. 

@jbledevehat  @ColineLebaratoux  Vous pouvez tester si ça vous convient d'un point de vue fonctionnel: si les projets que voient une entreprise vous conviennent.

**Comment by ColineLebaratoux** [comment]
✅ @ttdm, vérification sur le lien de preprod du filtrage des projets selon l'éligibilité de l'entreprise => ça fonctionne bien 
✅ @jbledevehat, j'ai vérifié les colonnes secteur d'activités ciblées pour chaque projet. C'est ok, je proposerais juste de restreindre le scope activité 
- pour le projet "réduction-emballages" (=> j'ai directement modifié sur baserow) ok pour toi @jbledevehat ? (tu avais mis ✅ à tous)

- pour le projet "éco-conception" également, mais c'est un peu particulier parce que c'est la thématique au global dont l'affichage devrait peut-être être conditionnée en fonction du secteur d'activité. Il me semble que l'éco-conception est un terme bien identifié pour le secteur C (Industrie manufacturière) mais ne concerne pas (et aussi ne parle pas du tout à tous les autres secteurs). Tu en penses quoi @jbledevehat ?

**Comment by jbledevehat** [comment]
Cf. discussion du jour sur #tee-design sur Mattermost... Car un vrai débat.
Pour moi c'est good.
