### ISSUE TITLE
Correction de l'affichage des pages consultées dans fil d'ariane et l'url

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1162]
Bug / Regression au niveau de l'url et du fil d'ariane 
Cf ticket #903 qui consistait à améliorer l'url en ajoutant l’historique de navigation, pour permettre de retracer le parcours de consultation d'une fiche dispositif depuis une fiche projet.
=> Questionnaire/projet/ID projet/ID dispositif

Ex : 
Sur le parcours "j'ai un projet en tête", [Depuis la fiche projet "audit énergétique"](https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat/projet/audit-energetique?choix-du-parcours=j-ai-un-projet&siret=35333323000012&effectif=ME), si je clique [sur la fiche dispositif "diag perf'immo"](https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat/diag-perf-immo?choix-du-parcours=j-ai-un-projet&siret=35333323000012&effectif=ME), j'arrive sur l'url suivante
https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat/diag-perf-immo?choix-du-parcours=j-ai-un-projet&siret=35333323000012&effectif=ME

Or, l'url devrait afficher .../questionnaire/resultat**/audit-energetique/**diag-perf-immo?choix-du-parcours=j-ai-un-projet&siret=35333323000012&effectif=ME

et le fil d'ariane devrait afficher Accueil > Questionnaire > Vos résultats > Audit énergétique > Diag Perf'immo
![Capture d’écran 2024-09-30 à 11 46 13](https://github.com/user-attachments/assets/3d1e287d-465f-4142-9f80-938a9559f175)

Idem quand on est sur l'annuaire suite à la prochaine évolution #1101 par @oumeimaelisbihani

**Comment by ColineLebaratoux** [comment]
@yvalentin il s'agit bien d'une regression ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux j'ai trouvé le fix, c'est bien une régression ! je le corrige dans l'aprem

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani !

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux à tester ici : https://tee-preprod-pr1179.osc-fr1.scalingo.io/
