### ISSUE TITLE
Modifier la carte CTA "je complète mon profil" sur la fiche projet

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1169]
Modifier le CTA "je complète mon profil" sur la fiche projet. 

**Pour rappel :** 
Cette carte CTA a pour objectif d'inciter l'utilisateur à s'identifier (SIRET effectif) pour lui permettre d'obtenir des résultats personnalisés pour son entreprise. Il est un rappel du CTA présent dans le header (cf ticket #1108)

**comportement :**
- Au clic sur le CTA > ouverture de la modale (#1172)

**conditions d'affichage :** 
- Cette carte CTA s'affiche uniquement lorsque l'utilisateur consulte une fiche projet sans avoir été "identifié" (nous ne connaissons pas son SIRET et son effectif). 
NB : Le bloc "contactez un conseiller"ne s'affiche jamais en même temps que cette carte CTA "je complète mon profil" (uniquement quand l'utilisateur est identifié)

---
**TO DO :**
- [x] Aligner la carte avec les cartes dispositifs 
- [x] Modifier le texte pour "Vous voulez uniquement voir les aides éligibles pour votre entreprise ?" (puisque maintenant nous affichons toutes les aides disponibles sur un projet à l'utilisateur) et diminuer la taille (cf maquette)
- [x] Modifier le CTA pour "Je complète mon profil" + le passer en jaune (**gras**) sur fond bleu

En prod : 
![Image](https://github.com/user-attachments/assets/922eee86-5400-4888-b7db-6b4ae3a81ed6)

Vision cible : 
![Image](https://github.com/user-attachments/assets/d437f49f-4d0e-463f-8d6a-442e67a3d35c)

[maquette ](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7713-397764&t=20RoYIka3ToVEiYI-1)

**Comment by ColineLebaratoux** [comment]
- [ ] Peux-tu ajouter un interlignage un peu plus grand entre le texte et le CTA ?

![Image](https://github.com/user-attachments/assets/2ad73171-8e72-49a8-b69d-0642da31781f)
![Image](https://github.com/user-attachments/assets/3268184b-2ef9-48b0-8c5d-a66b7b59341c)

- [ ] En version mobile, peux-tu supprimer l'image, pour ferrer tous les contenus sur la gauche ?
![Image](https://github.com/user-attachments/assets/0e68cdda-ab6b-4591-89de-b820fa0f3cb9)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux les changements https://tee-preprod-pr1262.osc-fr1.scalingo.io/projets-entreprise/diag-360
