### ISSUE TITLE
Ajouter un filtre entreprise dans le filtre latéral du catalogue des aides et des projets

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1178]
- En tant qu'entreprise, une fois que je me suis "identifiée", je souhaite que toutes mes recherches sur le site soient filtrées pour mon entreprise, notamment si je consulte le catalogues des aides et des projets.
- En tant qu'entreprise, j'arrive sur une fiche aide depuis une recherche google, je m'identifie depuis la fiche aide et m'aperçois que je ne suis pas éligible à cette aide. Un CTA "voir mes aides éligibles" m'amène sur le catalogue des aides filtrées pour mon entreprise. 

- En tant qu'opérateur, j'ai besoin de tester le catalogue des aides consécutivement avec différents paramètres pour faire des tests. 

---
- [ ] Ajouter un filtre "entreprise" avec le nom de l'entreprise et le détail des données (secteur, localisation, effectif)dans la colonne des filtres. Ces données sont pré-remplis en fonction des informations enregistrées dans la modale. Ce filtre reste toujours ouvert.

- [ ] Ajout d'un indice avec le nb de filtres actifs sur chaque filtre (pour permettre à l'utilisateur de voir en un coup d'oeil quels filtres sont actifs)

conditions d'affichage : 
- [ ] Le filtre entreprise est actif par défaut lorsque l'entreprise est identifiée (modale complétée)

- [ ] Lorsque le filtre entreprise est actif, supprimer le filtre régionale (qui viendrait en conflit avec la localisation de l'entreprise). Lorsque le filtre entreprise est désactivé par l'utilisateur, le filtre régional est reproposé

- [ ] Le filtre entreprise n'est pas visible lorsque l'entreprise n'est pas identifié.

**filtre actif :** 

![Image](https://github.com/user-attachments/assets/a4c9fcc2-c494-4ba6-a6f3-0e0c3475e7e9)

**filtre déséctionné :** 
![Image](https://github.com/user-attachments/assets/1c81290a-93ff-46e9-ba7d-3763c4e6af54)

**utilisateur non identifié**
![Image](https://github.com/user-attachments/assets/79073568-aa6f-4417-ac7f-6d8672b914b1)

**Comment by ColineLebaratoux** [comment]
@jbledevehat tu en penses quoi ?

**Comment by jbledevehat** [comment]
Je me demande pourquoi il devrait y avoir un filtre dans la barre latérale avec le nom de l'entreprise. Intuitivement, je souhaite voir que les aides me concernant. Donc s'il y a un usage de voir toutes les aides, c'est avant tout une suppression de l'entreprise dans "Vous êtes..." qui faut facilement retirer.

**Comment by ColineLebaratoux** [comment]
Je comprends ton point. On pourrait commencer par ta proposition qui consiste à ne rien changer, ça ne coûte rien 🙂

En revanche, je t'explique ce qui motive ma proposition d'afficher le filtre entreprise aux côtés des autres filtres à gauche : 
- Je crains que ce ne soit pas aussi logique que l'on voudrait que les résultats des catalogues sont automatiquement filtrés avec les données enregistrées dans la modale. => mais à tester 
- Je suis embêtée par le filtre "région" qui entre en conflit avec les données de l'entreprise. Ou peut-être juste ne pas l'afficher si une entreprise est identifiée ?

**Comment by jbledevehat** [comment]
Oui je te rejoins, testons. Et oui pour le filtre région à ne pas afficher.
