### ISSUE TITLE
mise à jour de l'illustration eau

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1190]
![Image](https://github.com/user-attachments/assets/e1c10835-ef26-4a6b-aea3-bdb03e12e261)

- [ ] les vecteurs de mon illu sur l'économies d'eau semble cassés, je remets un nouveau svg ici pour le remplacer.

**Comment by ColineLebaratoux** [comment]
nouvel svg pour l'eau ![Image](https://github.com/user-attachments/assets/f944f9d6-7549-4fdc-b97a-492e007e511e)

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani ou @dolemoine est-ce que vous auriez le temps de prendre ce petit ticket ? 🙏

**Comment by dolemoine** [comment]
@ColineLebaratoux url de test : https://tee-preprod-pr1227.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci d'avoir pris le ticket @dolemoine 
En revanche, désolée je me rends compte que mon svg a encore un défaut. 
Voilà un nouveau svg 
![Image](https://github.com/user-attachments/assets/4d58b3ba-79b7-46e8-9e02-5355ec89fbfb)

Merci 🙏

**Comment by dolemoine** [comment]
@ColineLebaratoux done !

**Comment by ColineLebaratoux** [comment]
merci ! c'est déja à jour sur le lien ?

**Comment by ColineLebaratoux** [comment]
merci !
