### ISSUE TITLE
Modification de la commune dans la modale entreprise

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1202]
- rendre le tag localisation pré-rempli via le siret modifiable 
- remplacer le select "choix de la région" par une barre de recherche avec autocomplétion sur la ville. (cf maquette)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux version améliorée : https://tee-preprod-pr1284.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
chouette ! 

- [ ] Juste attention, il semblerait que l'espacement ce soit agrandit entre la localisation et l'activité : 
![Capture d’écran 2024-11-07 à 11 58 34](https://github.com/user-attachments/assets/e68e0751-238d-4e86-82ac-1b5183731c03)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux c'est réglé : https://tee-preprod-pr1284.osc-fr1.scalingo.io/ !

**Comment by ColineLebaratoux** [comment]
Merci !
j'étais passé à côté de ton précédent message : 
> Je me suis déjà notée le décalage de l'image quand les résultats apparaissent.
Bien vu !

> Et question, est ce que tu penses nécessaire d'ajouter un temps de latence entre le moment ou l'utilisateur écrit le nom de la ville et l'affichage des résultats (comme sur le siret ou c'est de 0,5 s?
Peut-être bien, j'ai l'impression que ça rame à chaque lettre entrée. ça pourrait permettrre de changer ça ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux à tester : https://tee-preprod-pr1284.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani Le test se fait sur le parcours "je préfère compléter mes infos manuellement" c'est ça ? Et ensuite tu étendras la solution sur le parcours SIRET ? 

Mes retours :

- [ ] le tri des résultats ne semble pas être par ordre alphabétique. Par exemple :
<img width="526" alt="Capture d’écran 2024-11-18 à 15 46 14" src="https://github.com/user-attachments/assets/899cf689-cf89-4f7f-8d92-7efc7a52642a">
<img width="553" alt="Capture d’écran 2024-11-18 à 15 46 05" src="https://github.com/user-attachments/assets/80145b57-5f71-4626-a410-975a608dd6b8">

- [ ] est-ce que tu peux paramètrer une plus grande latence entre l'ajout d'un second caractère et l'affichage du message d'erreur (comme pour le siret, env. 3 sec)
<img width="283" alt="Capture d’écran 2024-11-18 à 16 29 31" src="https://github.com/user-attachments/assets/4a542509-b72b-4c00-8de8-2170008163a0">

- [ ] La croix du tag est trop collée au texte (tu peux faire le même espacements que sur les autres tags)
<img width="428" alt="Capture d’écran 2024-11-18 à 15 50 26" src="https://github.com/user-attachments/assets/d644e7e9-d087-4e12-be5f-fe3c0c559288">

- [ ] il y a toujours un soucis d'espacement trop important cf correction plus haut"Juste attention, il semblerait que l'espacement ce soit agrandit entre la localisation et l'activité"

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux les changements : https://tee-preprod-pr1284.osc-fr1.scalingo.io/ j'ai mis un délai de 1s entre la saisie de la ville et la recherche. Pour l'écart entre les capsules, ça devrait etre bon ! j'ai du les retravailler pour inclure un espace pour les messages d'erreur pour empécher les déplacements intempestifs. Pour ta première question, je suis pas sure de comprendre. Quand on fait un enregistrement siret, on est pas sensé pouvoir modifier les infos si ? ça voudrait dire que les infos associées au siret ne sont pas correctes ?

**Comment by ColineLebaratoux** [comment]
Super, c'est parfait comme ça @oumeimaelisbihani !
Pour améliorer la recherche par ville : 

- [ ] Si l'utilisateur tape "lons le saunier" à la place de "lons-le-saunier", est-ce qu'on pourrait afficher le résultat plutôt que de lui afficher une erreur ? 
> En France, il y a environ 5 500 communes dont le nom comporte un tiret, comme "Saint-Martin", "Château-Renard", ou "Notre-Dame-de-Bellecombe".

**Comment by ColineLebaratoux** [comment]
Top !!!

**Comment by ColineLebaratoux** [comment]
Mince, attends dernière modif : 

- [ ] enlever l'italique pour harmoniser le
<img width="570" alt="Capture d’écran 2024-11-20 à 15 44 38" src="https://github.com/user-attachments/assets/7cfa48d5-7028-47e5-ac91-e15ff1f2f8bb">
 format des consignes dans les champs 👍

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux c'est modifié : https://tee-preprod-pr1284.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci,
Ticket **valid** 🎉

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1421.osc-fr1.scalingo.io/ version complète avec le parcours par questionnaire qui marche !

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani !
Bon le comportement est un peu bizarre mais c'est pas le parcours majeur et on s'est dit qu'on faisait au plus simple. 

- [ ] Pour unifier, peut-être que tu pourrait passer le composant de recherche de la commune en bleu (cf champ siret)

<img width="991" alt="Capture d’écran 2024-12-11 à 10 28 45" src="https://github.com/user-attachments/assets/ec6e4238-58c3-421b-9070-2f5fa059e735">
<img width="1332" alt="Capture d’écran 2024-12-11 à 10 29 17" src="https://github.com/user-attachments/assets/d6936132-c22f-44cb-bbfb-7387093a47ff">

**Comment by yvalentin** [comment]
@oumeimaelisbihani @ColineLebaratoux 
Besoin d'une combobox pour l'autocompletion et l'accesibilité

Peut être dans un prochain ticket ?

https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/
