### ISSUE TITLE
Ajout MOOC Entreprises & biodiversité

### ISSUE THREAD

**Issue by mpiac** [betagouv/mission-transition-ecologique#1230]
Parmi les dispositifs "Pour aller plus loin" sur la page du projet, serait-il possible d'ajouter le [MOOC Entreprises & Biodiversité](https://mooc.formation.lpo.fr/enrol/synopsis/index.php?id=4), copiloté par la LPO, l'OFB et le MEDEF ? Le MOOC a reçu de très bon retours de la part des entreprises participantes, et il fait partie des dispositifs génériques d'accompagnement que le ministère souhaite mettre en avant.
```[tasklist]
### Tasks
- [x] Ajout d'un dispositif MOOC Entreprises et biodiversité suite à discussion
```

https://baserow.io/database/114839/table/314437/539069/row/300

**Comment by mpiac** [comment]
@ColineLebaratoux Peux-tu faire une passe/vérification s'il te plaît ? Merci beaucoup :)

**Comment by ColineLebaratoux** [comment]
C'est bon, pareil j'ai étoffé la description courte

**Comment by mpiac** [comment]
@ttdm Puis-je te laisser checker si tout est bon de ton côté ? Merci bcp !!
