### ISSUE TITLE
Proposition de modifications sites touristique exemplaire

### ISSUE THREAD

**Issue by mpiac** [betagouv/mission-transition-ecologique#1232]
Problématique : wording validé en comité peu de marge de modification là-dessus 

Intérêt pour elle d'ajouter le volet puisque limite le flux et donc l'impact sur l'env.
L’appel à Projets « Sites touristiques exemplaires » vise à accompagner des opérations de sites emblématiques forts, ou à fort potentiel de développement permettant à la fois l’amélioration des conditions d’accueil et d’information des visiteurs, leur sensibilisation et la régulation des flux dans l’optique d’un développement durable.

Il se décline en deux volets :

Volet 1 : soutien à des aménagements ;

              Volet 2 : soutien à des solutions technologiques de gestion des flux.

**Comment by mpiac** [comment]
Changement de La Région Sud souhaite soutenir financièrement les investissements qui visent à améliorer l'accueil du public sur ses sites touristiques dans le respect de la préservation des patrimoines naturels régionaux. pour ==> vise à accompagner des opérations de sites emblématiques forts, ou à fort potentiel de développement permettant à la fois l’amélioration des conditions d’accueil et d’information des visiteurs, leur sensibilisation et la régulation des flux dans l’optique d’un développement durable.

**Comment by mpiac** [comment]
Ajouter le volet 2

**Comment by mpiac** [comment]
Ajout du volet 2 description longue + phrase description courte

**Comment by mpiac** [comment]
@ColineLebaratoux si tu veux faire une petite review rapide :)

**Comment by ColineLebaratoux** [comment]
j'ai juste modifié le début "Sites touristique exemplaire vise à accompagner les opérations..."pour simplifier "Cette aide soutient les projets de ..."
