### ISSUE TITLE
Ajout Cedre ambition

### ISSUE THREAD

**Issue by mpiac** [betagouv/mission-transition-ecologique#1285]
https://baserow.io/database/114839/table/314437/539069/row/364

Peut-être en titre  : Rejoignez la communauté des 300 entreprises régionales engagées pour la transition écologique et la RSE et soutenues par la Région Sud ?

**Comment by mpiac** [comment]
Suivant ta validation je modifierai le cedre investissement qui passe du coup à max 100k en subvention pour les entreprises qui viennent de cedre ambition...

**Comment by ColineLebaratoux** [comment]
@mpiac j'ai du mal à comprendre l'étape 2  "Inscrivez-vous sur le Réseau Preci, le portail régional de l’économie circulaire, afin de favoriser les retours d’expérience et synergies entre entreprises responsables
[Le Réseau Preci](https://www.reseau-preci.org/)". 
Je le comprends comme une étape facultative, plutôt à réaliser en dernière étape non ? Ou j'ai peut-être mal compris ?

**Comment by mpiac** [comment]
@

> [@mpiac](https://github.com/mpiac) j'ai du mal à comprendre l'étape 2 "Inscrivez-vous sur le Réseau Preci, le portail régional de l’économie circulaire, afin de favoriser les retours d’expérience et synergies entre entreprises responsables [Le Réseau Preci](https://www.reseau-preci.org/)". Je le comprends comme une étape facultative, plutôt à réaliser en dernière étape non ? Ou j'ai peut-être mal compris ?

Oui on peut peut-être en dernière étape ça porte à confusion selon les sites mais dernière étape c'est ce qui semble faire consensus : 

"Au préalable, il est demandé aux entreprises candidates de s’inscrire sur [reseau-preci.org : le portail régional de l’économie circulaire](https://www.reseau-preci.org/) afin de favoriser les retours d’expérience et synergies entre entreprises responsables." https://entreprises.maregionsud.fr/financement/sud-entreprises/gamme-cedre/cedre-ambition
mais là : https://www.cote-azur.cci.fr/transition-ecologique-des-entreprises-rse-lancez-vous-avec-cedre-ambition-en-2025/ c'est même pas notifié donc clairement une dernière étape 
et sur le mail envoyé par la personne responsable du dispositif à la région : "Pour candidater à CEDRE Ambition 2025 :

Les dossiers sont à envoyer par mail à [cedre@maregionsud.fr](mailto:cedre@maregionsud.fr) en indiquant dans l’objet « Candidature CEDRE Ambition 2025 » avant le 13 décembre 2024 (à 23h59).
Inscrivez-vous sur [www.reseau-preci.org](http://www.reseau-preci.org/) pour profiter de toutes les informations liées à l’économie circulaire en région"

**Comment by mpiac** [comment]
@ttdm Un nouveau dispositif à vérifier si tu peux pour la mise en prod :)
