### ISSUE TITLE
Diag Ecoconception valeur condition cassé

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1330]
Avec une entreprise précise, sur une aide j'ai pas la bonne valeur du cout : https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat/projet/ecoconception/diag-ecoconception?choix-du-parcours=j-ai-un-projet&siret=38456442300018&effectif=TPE&objectifs=eco-design

![Image](https://github.com/user-attachments/assets/1d4ae976-1396-47f1-bcea-4252fbcfb5a9)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1266
```

**Comment by ttdm** [comment]
Le lien au dessus est fonctionnel en prod; le coût restant à charge est bien personnalisé. 

J'en ai profité pour tester pour différentes tailles d'entreprise, ça a toujours l'air fonctionnel.
