### ISSUE TITLE
Revoir la nomenclature des types d'aide : "financement" / "accompagnement"...

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#224]
Aujourd'hui, on distingue les dispositifs de cette manière : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8717abd2-c541-4a11-887d-1f237fc8c728)

Demain, on souhaite faire évoluer cette nomenclature, pour regrouper les accompagnements et les financements d'accompagnements qui correspondent à des prestations de même nature. 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a62a79df-72cf-4c2a-bad7-d03ccdb191cf)

- [x] Changer toutes les études Ademe en "étude" et non "financement"
- [ ] Remplacer le terme accompagnement par "étude"

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/62af6660-2a06-4432-8b01-450f9d9ca9ae)

---
[voir ticket lié pour la suite des évolutions de la fiche dispositif](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/716#issue-2270924239)

**Comment by jbledevehat** [comment]
@ttdm j'ai modifié le type d'un dispositif "Accompagenement" en "Etude"
Il faudrait voir dans le front ce nouveau terme "Etude" plutôt que "Accompagnement"
Est-ce pour toi ou plutôt pour Dorian/Oumeima ?

**Comment by ttdm** [comment]
@jbledevehat  Je dirais plutôt pour moi parce que j'ai tenté de le faire ce soir en même temps que les ajouts de 2 programmes mais c'est pas évident au niveau des données / pas très agréable comme entrée dans les données :
- tu as renommé à la fois des "accompagnements" et des "accompagnements en étude".  
 - jusqu'à présent, les "accompagnements" avaient deux champs dans le tableau " Coût reste à charge" et "⏱Prestation (durée + étalement)"
 - de leur côté les financements avaient le champ " Montant de l'aide" 
 **- quitte à recréer une nouvelle colonne, il faudrait au minimum uniformiser les "étude"**
 - il y a ensuite du travail dans le json schema et pour vérifier toute la propagation dans le front. 
 
 Du coup quel(s) champ(s) pour les études ? 
 Je peux reprendre le tableau manuellement pour le mettre à jour mais je ne veux pas transférer des "montant de l'aide" dans "cout reste à charge" sans en discuter parce que ça ne me semble pas vraiment être des équivalents.

**Comment by ttdm** [comment]
@jbledevehat 

Tu peux tester les modifications ici https://tee-preprod-pr928.osc-fr1.scalingo.io/aides-entreprise

Comme prévu, malgré le type unique "étude", il y a deux possibilités de données financières affichées. C'est géré dans baserow via la création de deux types "etude" et "financement-etude".

De visible sur le site, je n'ai changé que le label du type. Je ne pense pas devoir changer autre chose mais si tu as en têtes des affichages spécialisés par type sur le site, n'hésite pas à les tester.

**Comment by jbledevehat** [comment]
Je vois écris " Coût : undefined " pour toutes les études ADEME... 
![Image](https://github.com/user-attachments/assets/a6fea372-355a-4ca0-8ffa-78a666dd3bdd)

**Comment by ttdm** [comment]
@jbledevehat  C'est corrigé !
J'en ai profité pour refaire un tour complet et il me semble que cette fois çi tout à a été modifié !

**Comment by ttdm** [comment]
Revue en visio avec JB, suppression du need validation, et merge dans la foulée pour que les données de dispositifs soient à jour (en particulier le fond tourisme durable)
