### ISSUE TITLE
Générer la déclaration d’accessibilité

### ISSUE THREAD

**Issue by JulienParis** [betagouv/mission-transition-ecologique#234]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/9b314324-572b-43cf-9621-795c7317f208)

**Comment by jrayneau** [comment]
Il est possible de mettre à jour la page accessibilité en générant une page accessibilité avec le service beta.
gouv : 
https://betagouv.github.io/a11y-generateur-declaration/#create

**Comment by ColineLebaratoux** [comment]
tester l'accessibilité sur 3 pages clés : 
- page d'accueil
- page résultats 
- fiche dispositif

**Comment by jbledevehat** [comment]
En doublon avec d'autres d'autres cartes
