### ISSUE TITLE
Ajout d'un choix à la question "bâtiment" : Parlons de vos locaux...

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#279]
- [x]  Ajouter un choix à la question "bâtiment" “*je ne dispose pas de locaux professionnels”* 
(c'est le cas de beaucoup d'entreprises individuelles)

---
En profiter pour
- [x] Ajouter d'un Emoji au choix n°3 : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/cc0154ac-6ac5-4416-9af3-6bfee1a1dcf0)

**Comment by pierrecamilleri** [comment]
- [ ] Corriger la dénomination de l'entreprise, actuellement erronnée (l'API Sirene ne renseigne pas le champ `denominationUniteLegale`)

**Comment by oumeimaelisbihani** [comment]
version de test ici >> https://tee-preprod-pr774.osc-fr1.scalingo.io/
