### ISSUE TITLE
A l'étape SIRET, pouvoir recherche par le SIRET, SIREN, nom... directement

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#333]
recherche par le SIRET, SIREN, nom, Adresse... comme sur https://annuaire-entreprises.data.gouv.fr/

Voir le fonctionnement de Place des entreprises qui a une belle UX.

**Comment by ColineLebaratoux** [comment]
voir ticket avec une évolution au niveau de l'étape SIRET : [#627](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/627)

**Comment by ttdm** [comment]
Je pense que le ticket du dessus est à faire séparément et en simultanné avec le reste des autres modifs du ticket pour conserver de la cohérence durant tout le parcours. (en terme de dev, ça a aussi plus de sens)

Voila une première proposition d'interface : 
https://tee-preprod-pr721.osc-fr1.scalingo.io/questionnaire/siret?choix-du-parcours=j-ai-un-projet#questionnaire

**Comment by ColineLebaratoux** [comment]
Hello @ttdm ! 
Voilà mes retours suite à ton message : 
1) Pour les entreprises individuelles, je suis d'accord avec Yohann pour le titre "nom de la personne - siret"  plutôt que "Entreprise individuelle-siret". 

2) Concernant le nombre de résultats à afficher : Je suis d'accord avec toi, on ne peut pas en mettre plus de 3 par page au risque de repousser trop bas le bouton suivant.
- Créer de multiples page de résultat, aurait été une bonne solution mais si ça demande un effort important de dev, ça n'en vaut pas la peine. Il ne s'agit pas d'un irritant fort côté utilisateur. 
- En solution intermédiaire, je proposerai de rester sur un affichage de 3 résultats mais d'ajouter 2 mentions lorsqu'il y a plus de 3 résultats à la recherche. A savoir : 
- [ ]  afficher "besoin d'aide pour retrouver votre siret ? Cliquez ici + lien externe vers l'annuaire entreprise. 
- [ ] afficher "3 résultats proposés" plutôt que le nb exact de résultats pour éviter de créer une confusion pour l'utilisateur qui ne voit que 3 résultats. 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/52ede595-b788-46e1-ae7d-fc82937af284)

@yvalentin @jbledevehat n'hésitez pas à réagir si vous êtes d'un autre avis

**Comment by ColineLebaratoux** [comment]
J'en profite pour glisser ici 2,3 corrections UI : 


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/3a2470c2-3220-4991-8172-1365ccd34d0a)

- [ ] Corriger la mention d'aide à la saisie pour ex : "Boucherie Sanzot" ou N° SIRET "130 025 265 00013"
- [ ] Ajouter un espace avant les ":"
- [ ] Diminuer un peu l'espacement entre les cartes
