### ISSUE TITLE
🕵🏻‍♂️ Programmer de nouveaux tests utilisateurs avec les entreprises de la FEEF (Mars 2024)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#389]
- [x] ajouter les utilisateurs sur [le fichier notion ](https://www.notion.so/accelerateur-transition-ecologique-ademe/6d0307bead254033bc2addcb1488bb85?v=9b0fe5f9be594297bd2710c363470fa8&pvs=4) (liste des entreprises de la FEEF + contact Pierre de Romanet)
- [ ] Planifier les rdv 
- [ ] redéfinir les objectifs des prochains tests

**Comment by ColineLebaratoux** [comment]
@jbledevehat pour info, j'ai ajouté toutes les entreprises (14) à contacter sur le notion 
- Beaucoup d'entreprises de l'offre ou déjà engagées. 
- Beaucoup du secteur de l'agroalimentaire 
- Très peu de TPE / aucune entreprise individuelle

Anne suggérait de faire appel à CCI France, et CMA France pour compléter le panel : je trouve que c'est une bonne idée pour rééquilibrer les types d'entreprises interrogées.

**Comment by jbledevehat** [comment]
Mail en cours pour planif 2ème trimestre
