### ISSUE TITLE
Mettre en place des champs conditionnels pour gérer les variables des dispositifs

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#390]
Rationaliser les déclinaisons en une seule fiche dispositif et afficher des variables au niveau des champs "cout" ou "durée"  "montant de l'aide" en fonction de la région / taille de l'entreprise... 

Pour mettre en place ce système nous avons choisi de : 
- ❌ Soit garder 1 ligne par dispositif régional dans le tableau excel 
- ❌ Fusionner les déclinaisons sur une ligne et mettre le code sur l'excel => source d'erreurs
- ✅ Fusionner les déclinaisons sur une ligne et mettre les variables dans un second tableau => ok

Le tableau des déclinaison à été créer pour les 3 diag Bpifrance dans un onglet à côté de DataProd

---
### **TO DO** 

- [ ] Créer un test pour ce Tableau "champs conditionnels"
- [ ] Définir quel est le dispositif générique. Le dispositif générique reste dans "dataprod". Il affiche des données min.max (dispositif affiché dans l'annuaire)
- [ ] Mettre les déclinaisons et les mettre dans champs conditionnels
- [ ] Le faire pour les 3 Diag Bpifrance renseigné dans l'onglet 

---
### **liste des dispositifs concernés pour la CCI et CMA :** 

**visite énergie**
visite-energie-cma (en prod)
visite-energie-cci (en prod)
Visite-énergie-ARA
Visite-énergie-BFC
Visite-énergie-bzh
Visite-énergie-GE
Visite-énergie-IDF
Visite-énergie-PACA

**performa**
Performa-national (en prod)
Performa-ARA
Performa-BFC
Performa-Bzh
Performa-Corse
Performa-CVL
Performa-GE
Performa-IDF
Performa-réunion
Performa-Normandie
Performa-NA
Performa-occitanie
Performa-PDL
Performa-PACA

**diagnostic eau**
Diag eau-hdf
Diag eau-Bzh
Diag eau-CVL
Diag eau-GE

**imprim'vert**
imprimvert-national (en prod)
imprimvert-paca
imprimvert-na
imprimvert-occitanie

**ecodéfis des artisans et des commerçants ** 
ecodefis-national (en prod)
ecodefis-paca

**Rénovation Petit Tertiaire Privé** 
renov-petit-tertiaire-National (en prod)
renov-petit-tertiaire-CVL (Diagnostic SARE)
renov-petit-tertiaire-Normandie (Diagnostic SARE)
renov-petit-tertiaire-occitanie (Rénov'petit tertiaire)

**Comment by ColineLebaratoux** [comment]
**Données incomplètes**

J’ai passé en orange les cases incomplètes pour lesquels nous sommes en attente d’informations de la part des opérateurs compétents. @jbledevehat  je te laisse en faire part aux référents CCI CMA


**Doublons**

Le dispositif « ecodefis des artisans et des commerçants » apparait 2 fois : un à l’échelle nationale (déjà intégré à la version en prod) et un à l’échelle régionale en PACA. Le programme et les conditions d’éligibilité semblent être identiques. Est-ce nécessaire de le présenter 2 fois sachant qu'une entreprise de la région PACA aura le résultat en doublon ? 
Même remarque pour le dispositif "imprim'vert" : il apparait 3 fois : un à l’échelle nationale (déjà intégré à la version en prod) et un à l’échelle régionale en Nouvelle-Aquitaine, et un en PACA. Est-ce nécessaire de le présenter plusieurs fois sachant qu'une entreprise de la région Nouvelle-Aquitaine ou PACA aura le résultat en doublon ? 
Concernant le diagnostic 360° de type « Performa environnement». On recense 13 déclinaisons régionales, avec une offre similaire.

Même constat pour le dispositif "visite énergie" avec 7 déclinaisons régionales
Idem pour le "Diagnostic eau" avec 3 déclinaisons régionales 

---
Voici les différentes options pour le traitement de ces déclinaisons. @Pierre Camilleri, quel est ton avis ?

1) Intégrer l’ensemble des déclinaisons régionales sur la plateforme tel quel 
:-1: des données dispersées difficiles à mettre à jour
:-1: ajoute de la complexité à la lisibilité de l’offre en TE

2) Intégrer l’ensemble des déclinaisons régionales sur la plateforme en unifiant les contenus. 
Titre : Performa IDF / Performa Normandie / Performa Bretagne …
Unification des textes : promesse, description et objectifs. 
:-1: des données dispersées difficiles à mettre à jour
:+1: Une meilleure compréhension des « familles » de dispositif pour les utilisateurs et leurs prescripteurs

3) Rationaliser les déclinaisons régionales en une seule fiche dispositif. 
Ajuster les disparités avec des données relatives, du type : Durée : « entre 1 à 2 jours selon la région » / Prix : « selon région »
:+1: Solution qui semble la plus simple pour l’expérience utilisateur et pour la mise à jour des données

**Comment by ColineLebaratoux** [comment]
On en rediscute @jbledevehat @ttdm @ColineLebaratoux

**Comment by jbledevehat** [comment]
@ttdm Pour tous les dispositifs CCI, CMA listés dans l'objet de la carte, j'ai fait toutes les modifs dans BaseRow, donc à voir directement la-bas pour savoir ce qui change.
Par contre j'ai supprimer les lignes Rénovation Petit Tertiaire Privé spécifique régions car pas de pertinence métier à avoir ces spécifités.
Puis j'ai bien laisser les autres dispositifs dans l'Excel historique.
A dispo si besoin pour revoir cela si questions.

**Comment by ttdm** [comment]
Pour le diagnostic eau, il faudrait écrire un diagnostic eau "générique". Ce diagnostique eau serait visible dans le catalogue lorsqu'on ne renseigne pas les données d'entreprise avec l'égibilité dans l'ensemble des régions des diag régionaux. Ensuite, ce dispositif sera ensuite modifié par région. S'il est impossible de créer un diagnostique générique alros peut être que les dispositifs doivent être sépère dès l'origine et être considérés comme des dispositifs autonomes.

**Comment by ttdm** [comment]
Test fonctionnel sur le lien suviant : 
https://tee-preprod-pr1122.osc-fr1.scalingo.io/

Je pense que ça fonctionne mais c'est un peu complexe de le vérifier : 
-  il n'y a finalement que peu de changements sur le site en prod ( La majorité des changements concernent les urls liés aux programmes ou les opérateurs secondaires qui ne sont pas des données affichées. (Les yamls ont eu bien changés)
- Il faut trouver des entreprises qui cochent les cases spécifiques pour voir les différences et ce n'est pas toujours évident ! 

En clair, je vous incite à passer quelques minutes de plus que d'habitude à tester !

**Comment by ttdm** [comment]
Merci à la personne qui vient de tester et de générer un bug, je fix ça :)

**Comment by ttdm** [comment]
@jbledevehat @ColineLebaratoux  C'est enfin tout prêt ! 

Voila une dizaine de liens pour validation : 

Tests sur l'effectif avec le dispositif eco-flux:
- sur la page de résultat du questionnaire : [Pour une petite entreprise](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=PE&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat), aller sur l'onglet 'vos aides financières' -> présence de eco-flux avec le texte "2 000 € HT après subvention de 50% "...; au clic sur eco-flux, même valeur
- meme entreprise, même questionnaire, affichage de eco-flux simplement à partir de l'URL [lien](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat/diag-eco-flux?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=PE&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non) 
-  sur la page de résultat du questionnaire : [Pour une entreprise de taille moyenne](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=ME&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat), aller sur l'onglet 'vos aides financières' -> présence de eco-flux avec le texte "3 000 € HT après subvention de 50% " ; même texte à l'ouverture du dispostif ...
- meme entreprise, même questionnaire, affichage de eco-flux simplement à partir de l'URL [lien](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat/diag-eco-flux?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=ME&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non)
- page de résultat [pour une eti](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=ETI_GE&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat), filtrage valide, pas de présence d'éco flux.
- page de résultat [pour une ei](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=77561483700133&effectif=EI&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat), filtrage valide, pas de présence d'éco flux.
- [sur l'annuaire](https://tee-preprod-pr1122.osc-fr1.scalingo.io/aides-entreprise/diag-eco-flux), texte générique "De 2 000 € HT à 3 000 € HT après subvention de 50%"

Tests sur la région avec le dispositif performa-environnement:
- [en bretagne](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat/performa-environnement?choix-du-parcours=j-ai-un-projet&siret=siret-non-renseigne&effectif=TPE&activite=tertiaire&region=Bretagne&objectifs=environmental), texte attendu dans prestation : 1 journée de prestation répartie sur 2 mois
- [en auvergne rhone alpes ](https://tee-preprod-pr1122.osc-fr1.scalingo.io/questionnaire/resultat/performa-environnement?choix-du-parcours=j-ai-un-projet&siret=siret-non-renseigne&effectif=TPE&activite=tertiaire&region=Auvergne-Rh%C3%B4ne-Alpes&objectifs=environmental), texte attendu dans prestation: 2 jours de prestation répartis sur 6 mois
- [annuaire](https://tee-preprod-pr1122.osc-fr1.scalingo.io/aides-entreprise/performa-environnement) texte attendu dans prestation : 1 journée

**Comment by ColineLebaratoux** [comment]
Wow ! Trop bien @ttdm 
C'est une usine à gaz derrière ?

**Comment by ttdm** [comment]
Pas tant que ça je dirai. Il y avait pas mal de travail mais le principe de ce que j'ai fait est assez simple ce qui doit permettre une maintenance assez facile. 
Dans l'idée il y a juste 3 choses de faites :
- l'ajout d'informations conditionnelles dans les yamls des dispositifs
- des modifs du front end pour qu'il retourne dès que possible les informations des entreprises
- dès que l'on rentre dans le backend, si on a des informations sur une entreprise, alors, avant toute autre action, on modifie le programme pour qu'il soit spécifique à l'entreprise.
