### ISSUE TITLE
Evolution du filtre par thématique sur la page de résultats 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#452]
❌ **la page de résultats présente aujourd’hui une longue liste d'aides difficile à digérer**

> *“Ah je pensais regarder toute la liste. mais en fait il y en a beaucoup !” “Par contre, Je suis pas sûr que les gens descendent jusqu’en bas. Je préférerais que ce soit trié par thématique, c’est un peu mélangé là."*

> *“Je sais plus sur quelle thématique je suis. C’est pas pratique, ça pose problème. il faudrait les mots clés affichés.”*

---
**Solution**
- [ ] ajouter des chapeaux thématiques pour trier les résultats (sur les pages des résultats des deux parcours)

---
**Spécificité pour chaque parcours :** 
- [ ] Sur la page de résultats du parcours "je ne sais pas par ou commencer" et sur la page "annuaire", créer un système de tag pour naviguer entre les différentes thématiques. 
- Seules les tags des thématiques prioritaires pour l'entreprise s'affichent (issues des réponses au questionnaire)
- Tag "Tous" = l'ensemble des thématiques prioritaires pour l'entreprise
- Choix d'affichage par défaut : filtré par thématique (et non tous)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/f0755d1c-0824-4c86-902e-541925cb9aef)

- [ ] Sur la page de résultats du parcours "J'ai un objectif en tête", ajouter le bandeau thématique sans afficher les tags thématiques
[voir le proto](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=1436%3A131849&mode=design&t=QgWJvmlwUZYu6UUv-1). 
=> pas de filtre thématique sur la page de résultats "j'ai un objectif en tête" => https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/694
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/fa30bbe0-917e-405c-b622-56337484f290)

---
Noms et codes couleurs des thématiques : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/4a6c22b4-784c-4ec2-b667-ff3da763e936)

- Construction & rénovation (tag 🏢 bâtiment)
- Économies d’énergie (tag ⚡️ énergie)
- Mobilité (tag 🚲 mobilité)
- Économies d’eau (tag 💧eau)
- Déchets & réemploi (tag 🗑 déchets)
- Analyses environnementales (tag 🌱 analyses)
- Ressources humaines (tag 👩‍🎓 RH)
- Éco-conception (tag :repeat: écoconception)

Illustrations : 
https://drive.google.com/drive/folders/1bFxV2jwI2194MfZi1OqSFPUbb6npzSjA?usp=drive_link

Version mobile 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8bb31d8b-adf8-40f3-a3b1-8344f0f25a5b)

**Comment by yvalentin** [comment]
en test pour validation ici:
https://tee-preprod-pr688.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Super @yvalentin ! 
Voilà mes retours : 

- [ ] Côté affichage, j'avais en tête que seuls les tags correspondants aux thématiques prioritaires de l'entreprise doivent s'afficher. Si l'entreprise dit dans le formulaire que l'énergie n'est pas une priorité pour elle, alors pas de tag énergie. Est-ce possible ?

**🎨 modifs UI :** 
- [ ] Sur le parcours "j'ai un objectif en tête", peux-tu faire apparaitre le bandeau correspondant à l'objectif choisi par l'utilisateur ?

- [ ] Je crains que les tags soient un peu petits. Pourrais-tu augmenter leur taille (pour toutes les tailles d'écran) ? cf maquette
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b09b7aa1-edc2-4541-a359-eca992561516)

- [ ] Sur mobile, les bandeaux thématiques "analyses environnementales" et "bâtiment" sont plus hauts que les autres. Peux-tu bloquer la hauteur max ? 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ee0a1b9c-9b02-47be-89e8-ef2c9d10cd5b)

- [ ] Sur mobile, l'illustration du bandeau "mobilité" est collé au bord gauche. Peux-tu ajouter une marge comme pour les autres illustrations ? 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/dfb6401c-6975-4f92-9e29-11bea0ca29f8)

- [ ] Sur mobile, pour gagner en lisibilité, peux-tu retirer le mot "thématique" des bandeaux et augmenter la taille du titre et sa graisse. (comme sur desktop)

- [ ] Lorsque les tags sont sur plusieurs lignes, peux-tu réduire l'espacement entre les tags ? 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b142033a-0681-4c3a-83aa-468ea0f8a05d)

- [ ] Pourrais-tu modifier l'illustration RH pour celle que je vais t'envoyer sur mattermost

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/f581ffc0-73e8-43cd-9ace-b896093f7718)

**Comment by yvalentin** [comment]
@ColineLebaratoux 
L'ensemble (sauf les points suivants) ont été mis à jour et déployé sur la review app (https://tee-preprod-pr688.osc-fr1.scalingo.io/aides-entreprise)

> Sur mobile, l'illustration du bandeau "mobilité" est collé au bord gauche. Peux-tu ajouter une marge comme pour les autres illustrations ?

Pour ce point, certaines images ont des tailles et des constructions différentes ce qui crée ce différent d'affichage. Comme les images sont mis en responsive, pour moi le plus facile serait que toutes les images soient de la même taille et la même construction

- thematique-batiments.svg (width="195" height="156") - cercle **pas** entier, tout à l’intérieur du cercle
- thematique-dechets.svg (width="237" height="156") - cercle **pas** entier, **pas** tout à l’intérieur du cercle
- thematique-eau.svg (width="190" height="156") - cercle **pas** entier, tout à l’intérieur du cercle
- thematique-eco-conception.svg (width="188" height="182") - cercle entier, **pas** tout à l’intérieur du cercle
- thematique-energie.svg (width="215" height="156") - cercle **pas** entier, **pas** tout à l’intérieur du cercle
- thematique-mobilite.svg (width="197" height="156") - cercle **pas** entier, **pas** tout à l’intérieur du cercle
- thematique-ressources-humaines.svg (width="268" height="239") - cercle entier, **pas** tout à l’intérieur du cercle
- thematique-strategie.svg (width="196" height="156") - cercle entier, **pas** tout à l’intérieur du cercle

> Sur mobile, les bandeaux thématiques "analyses environnementales" et "bâtiment" sont plus hauts que les autres. Peux-tu bloquer la hauteur max ?

J'ai bloqué/fixé à 100px pour le mobile et 200px pour le reste.
Dis moi si tu veux d'autres valeurs
```scss
      @include media-query.respond-from(xs) {
        height: 100px !important;
      }
      @include media-query.respond-from(sm) {
        max-height: 200px;
        height: 100% !important;
      }
```

**Comment by ColineLebaratoux** [comment]
@yvalentin je me suis crée un ticket (#731 ) pour revoir les illustrations. je te les repartagerai dès que c'est fait pour mettre à jour les illus.
En attendant je te propose de cloturer ce ticket ✅ 🎉
