### ISSUE TITLE
Ajouter des validateurs au niveau des champs du formulaire de contact

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#470]
Ajouter des validateurs pour éviter les erreurs 500 dans matomo :
- mail 
- téléphone
- SIRET ?

ticket formulaire de contact lié : [#470](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/470)

**Comment by jbledevehat** [comment]
Un lien avec #627 ?

**Comment by dolemoine** [comment]
@dolemoine:  implementer la validation du champs au focus out plutôt qu'à la soumission du formulaire

**Comment by dolemoine** [comment]
@ColineLebaratoux est-ce que je traite le ticket #262 en même temps? auquel cas est-ce que les messages d'erreur sont définis?

**Comment by dolemoine** [comment]
@ColineLebaratoux voilà le lien pour validaiton : https://tee-preprod-pr736.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @dolemoine ! 

En testant, je me rends compte que c'est un peu lourd l'état de validation du DSFR. ça prend beaucoup de place !
Serait-il possible d'enlever la checkbox pour l'état valid ? et même le bandeau latéral ?
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/db9b7efe-3291-49c1-b3bb-1dbd395fd2df)

**Comment by dolemoine** [comment]
@ColineLebaratoux c'est à jour sur l'url de demo: https://tee-preprod-pr736.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
C'est parfait !

**Comment by dolemoine** [comment]
@ColineLebaratoux petite question sur les messges d'erreur.

**Comment by ColineLebaratoux** [comment]
Zut, je n'ai plus ça en tête. 
Tu veux bien regénérer le lien de test ?

**Comment by dolemoine** [comment]
et voilà ! https://tee-preprod-pr736.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
![Capture d’écran 2024-05-27 à 12 57 05](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/6aff5afc-a70b-456a-9028-8598034ec2fb)
ça semble pété sur ce lien, je n'arrive pas à accéder à une fiche dispositif 😕

**Comment by jbledevehat** [comment]
@ColineLebaratoux Ca te va si le champs est vide de mettre par défaut "Ce champs est obligatoire" plutôt que "...n'est pas valide" ?

**Comment by ColineLebaratoux** [comment]
Si j'essaye d'interpréter le commentaire de @yvalentin, il s'agirait d'afficher "ce champs est obligatoire" lorsque rien n'a été saisi dans le champ. et de mettre "...n'est pas valide" lorsque le format n'est pas le bon. C'est ok pour moi

**Comment by dolemoine** [comment]
je crois que c'est l'idée oui. Ok pour moi, ça demande quelques petites modifications, je regarde ça demain!

**Comment by yvalentin** [comment]
> Si j'essaye d'interpréter le commentaire de @yvalentin, il s'agirait d'afficher "ce champs est obligatoire" lorsque rien n'a été saisi dans le champ. et de mettre "...n'est pas valide" lorsque le format n'est pas le bon. C'est ok pour moi. Tu confirmes Yoh ?

Oui, c'est bien ça ;-)

**Comment by dolemoine** [comment]
@ColineLebaratoux dernière version avec la petite modif dispo sur le lien de test : https://tee-preprod-pr736.osc-fr1.scalingo.io/
