### ISSUE TITLE
Changer le statut d'une opportunité (de "nouvelle" vers "transmis") une fois l'opportunité transmise à BPI

### ISSUE THREAD

**Issue by celinebagault** [betagouv/mission-transition-ecologique#503]
Actuellement les demandes transmises à BPI ont le statut "nouvelle". 
- [ ] Changer vers "transmis" une fois la demande transmise à BPI ou autres
- [ ] Supprimer la donnée "Envoyé ?" qui fait doublon

**Comment by jbledevehat** [comment]
Pour conclure sur ce sujet, nous ne regarderons pas la demande et l'envoyons à Bpifrance sans notre aval.

**Comment by ttdm** [comment]
@jbledevehat @celinebagault Aujourd'hui, on coche la case "envoyée" à la fois pour les transmissions vers CE et les transmissions vers BPI. 

J'aimerai juste confirmation que l'objectif c'est de remplacer la case "envoyée" par le statut "transmise" dans les 2 cas et non simplement pour BPI (carte écrite avant que le lien vers CE soit en place) ?

**Comment by jbledevehat** [comment]
Oui c'est bien dans les 2 cas
