### ISSUE TITLE
Ajouter le lien du Typeform pour permettre aux opérateurs d'ajouter/créer des dispositifs d'aides

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#515]
Typeform pour permettre aux opérateurs d'ajouter et de compléter tous les détails d'une aide pour être référencé sur la plateforme 

- [x] Créer le typeform : https://jeanbaptiste17.typeform.com/to/E6I4FHb4

### Intégration :
**court terme** 

- [x] renommer l'url dans typeform "jeanbaptiste17"
- [x] ajouter un lien dans le footer "Ajouter une aide" entre "statistiques" et "échanger avec un conseiller" 
- [x] créer une page : _https://mission-transition-ecologique.beta.gouv.fr/ajouter-une-aide-entreprises_ pour y intégrer le typeform 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/008b172b-1f67-42ec-983c-7ca35276e0d1)

Code d'intégration du formulaire : 
`<div data-tf-live="01HNJQ5V7EYXZTQAY755QPMA4R"></div><script src="//embed.typeform.com/next/embed.js"></script>`

**Comment by ColineLebaratoux** [comment]
Je te mets mes retours ici. Je peux faire des corrections directement si tu es ok avec mes reformulations
---

- [ ] Pour toutes les questions ouvertes : est-ce possible de mettre un champ texte plus large pour faciliter l’écriture et la vue globale du texte saisi (idéalement avec un compteur de mots) ? 
---
- [ ]  Mettre « la description longue » après les étapes du dispositif (c’est comme ça qu’elle apparait sur la fiche dispositif)
---
- [ ]  Question 7 à reformuler et à faire évoluer en question à choix unique : 
Ce dispositif…
A) est adapté pour une entreprise qui ne sait pas par où commencer dans la transition écologique 
B) est trop « expert » pour une entreprise qui ne sait pas par où commencer 
---
- [ ]  Question 8 « Est-ce que l'entreprise sera forcement seul pour aboutir sur cette démarche ? » => pas vraiment compréhensible. C’est pour qualifier un dispositif activable en autonomie ? 

A reformuler et à faire évoluer en question à choix unique : 
Quelle est la prochaine étape pour que l’entreprise puisse bénéficier de ce dispositif ? 
A) L’entreprise doit envoyer un message pour être recontacté par un conseiller. 

B) L’entreprise peut réaliser sa démarche (inscription, dépôt de dossier…) en autonomie sur un site internet. La mise en relation avec un conseiller n’est pas requise. 
---

- [ ]  Mettre « les étapes du dispositif» juste après la promesse (c’est comme ça qu’elles apparaissent sur la fiche dispositif)
- [ ]  Reformuler  « les étapes du dispositif» (supprimer « objectifs »)
« Pour un accompagnement ou une formation : Elles détaillent le programme.
Pour un financement : Elles décrivent pas à pas la démarche pour obtenir le financement en question.
Il y a entre 2 à 5 étapes. »
---
- [ ]  question sur la durée de la prestation : est-elle conditionnée par le type de dispositif (uniquement accompagnement et formation ? ) 
- [ ] question sur la durée de la prestation, modifier la légende pour : « Précisez également a durée totale dans laquel s’inscrit cet accompagnement. Ex :  12 jours de prestation répartis sur 6 à 8 mois »
---
- [ ]  Date de début et fin de dispositif : est-ce possible de changer pour un format JJ/MM/AAAA ?
---
- [ ] Reformuler « existe t-il un nombre d'année d'activité minimum pour que l'entreprise puisse bénéficier du dispositif ? »
---
- [ ]  Enlever le chapeau « coordonnées » qui donne l’impression d’être à remplir (et supprimer « si nous ne les avons pas déjà » qui donne l’impression que c’est facultatif)

**Comment by jbledevehat** [comment]
Pour le moment j'ajouterai un lien plutôt dans le footer ce qui sera rapide à faire. 
Ensuite il faut créer une page : https://mission-transition-ecologique.beta.gouv.fr/ajouter-une-aide-entreprises 
Enfin intégrer le typeform dans celle-ci.
@ColineLebaratoux ça te va comme plan ?

**Comment by ColineLebaratoux** [comment]
ok ça me va @jbledevehat ! 
Si notre solution court terme dure un peu, il faufdrait peut-être essayer de changer le nom du lien "jeanbaptiste17" ? 😅

**Comment by JulienParis** [comment]
intégration avec PR #589 

preview : https://tee-preprod-pr589.osc-fr1.scalingo.io

**Comment by JulienParis** [comment]
Pour info j'ai fait une petite amélioration, consistant à adapter la hauteur max de la page typeform en fonction du responsive. Par défaut le widget Typeform faisait 500px de haut. Perso je trouvais ça + propre en hauteur 100% (-la navbar) =>

---

Sur desktop

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/9ad500f7-6232-4089-8c07-b73b4896fad3)

---

Sur mobile

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/c9451800-5344-4215-a7fb-5ff1b8596004)
