### ISSUE TITLE
Créer une page /budget

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#535]
Dans nos obligations de Startup d'Etat, nous devons faire une page Budget. 

---

# Budget

Transition Écologique des Entreprises est un service public numérique, c’est pourquoi nous sommes transparents sur les ressources allouées et la manière dont elles sont employées.

## Principes

Nous suivons le [manifeste beta.gouv](https://beta.gouv.fr/approche/manifeste) dont nous rappelons les principes ici :

- Les besoins des utilisateurs sont prioritaires sur les besoins de l’administration
- Le mode de gestion de l’équipe repose sur la confiance
- L’équipe adopte une approche itérative et d’amélioration en continu

## Fonctionnement

Transition Écologique des Entreprises est une start-up d'état. L'équipe est donc portée par un intrapreneur qui est responsable du service numérique développé. Son rôle est multiple : déploiement, gestion des produits, référent auprès de son administration (budget, compte rendus d'avancement).

L'ensemble de l'équipe et le descriptif du produit est décrit sur la [fiche du produit beta.gouv.fr](https://beta.gouv.fr/startups/transition-ecologique-des-entreprises.html)

## Cofinancement

La particularité de notre Startup d'Etat est le cofinancement des plusieurs entité publiques : 

- [ADEME - Agence de la transition écologique](https://www.ademe.fr/)
- [DGE - Direction Générale des Entreprises](https://www.entreprises.gouv.fr/fr/la-direction-generale-des-entreprises-dge)
- [CGDD - Commissariat général au développement durable](https://www.ecologie.gouv.fr/commissariat-general-au-developpement-durable-cgdd)
- [Bpifrance - Banque publique d'investissement](https://www.bpifrance.fr/)
- [FINDPE - Fonds d’investissement « Numérique et Données » pour la Planification écologique](https://www.numerique.gouv.fr/services/fonds-dinvestissement-numerique-et-donnees-pour-la-planification-ecologique/) de la [DINUM](https://www.numerique.gouv.fr/) & [SGPE](https://www.info.gouv.fr/grand-dossier/france-nation-verte/le-secretariat-general-a-la-planification-ecologique)

## Consommation

| 2023 | Total   | 
| ------- | -------- | 
| Design | 83 194 € | 
| Développement et Data engineering | 164 674 € | 
| Pilotage | 154 627 €  | 
| Coaching | 48 600 € | 
| Relation aux entreprises (BizDev) | 10 819 € | 
| **Total TTC** | **461 914 €** | 

| 2024 (prévisionnel) | Total   | 
| ------- | -------- | 
| Design | 152 552,40 € | 
| Développement et Data engineering | 439 117,59 € | 
| Pilotage |  192 628,80 €  | 
| Coaching | 61 862,40 € | 
| BizDev | 172 558,18 € | 
| **Total TTC** | **1 018 719,37 €** | 

---

Reprendre et faire le même page avec les mêmes terme que la page budget “en construction” de Carte Verte : [https://carte-verte.beta.gouv.fr/budget](https://carte-verte.beta.gouv.fr/budget)

Pour info exemple de page budget terminées : [https://www.territoiresentransitions.fr/budget](https://www.territoiresentransitions.fr/budget)

**Comment by jbledevehat** [comment]
@ColineLebaratoux Est-ce que ça te va comme page obligatoire et rapide à faire ?

**Comment by JulienParis** [comment]
suggestion : @jbledevehat si on s'inspire de la page budget de territoiresentransition.fr je pense que ce serait bien de ventiler les montants ("cofinancement" et "consommation") par années civiles, quitte à avoir une colonne supplémentaire pour les totaux.

**Comment by ttdm** [comment]
@ColineLebaratoux  @jbledevehat 
Pour me changer les idées cett après midi, j'ai fait une première proposition de page budget : 
https://tee-preprod-pr1312.osc-fr1.scalingo.io/budget

A vos remarques sur le contenu / le format  !

**Comment by jbledevehat** [comment]
Ca me va bien. On peut l'envoyer comme tel. Merci

**Comment by ColineLebaratoux** [comment]
super ! 
petites remarques UI :
- [ ] Je pense que tu peux diminuer un peu la taille du camenbert sur desktop, (mais pas de la légende qui est déja bien petite)
- [ ] je placerais plutôt la légende en dessous du camembert 
- [ ] Pour plus de cohérence avec l'identité du site, tu peux utyiliser les couleurs de la charte : 

bleu
100% #001891
30% #92a4ff
10% #dbe1ff

vert
100% #1ebe8e
30% #b4f3e0
10% #e6fbf5

violet
100% #6a62f4
30% #d2d0fc
10% #f0effe

rouge
100% #fca081
30% #fee3d9
10% #fff6f2

jaune
100% #facf35
30% #fef1c2
10% #fffaeb
