### ISSUE TITLE
Evolution du Fil d'ariane

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#565]
❌ Le fil d'ariane prend trop de place en longueur et n'est pas utilisé par les utilisateurs pour revenir sur chaque piste de question. 

❌ Sa présence pose question _“d’accord, je comprends pas trop l’interêt de ce truc. en fait ici, la liste de gauche (parle du fil d’ariane) j’avais pas compris ce que c’était. je pensais que c’etait un menu du site ou des filtres comme sur le site de la fnac par exemple. j’avais pas compris que c’etait pour revenir en arrière. c’est bizarre.”_

❌ Par ailleurs, certains utilisateurs doutent encore de leur éligibilité pour les résultats proposés
_> *"c’est pas clair du tout ça sur le site. On entre le siret au départ mais sur ici, je ne suis plus sûre d’être concerné par toutes ces offres."“Ah si ça pourrait être pour moi ? Alors, il faut rassurer sur le fait que la liste des aides sont bien applicables à notre activité, et à nos petites structures, sinon elles vont dire “c’est pas pour moi”.*
> *Il doit y avoir un sacré algorithme derrière ! Mais il faut que les critères d’éligibilité soient affichées. parce que qu’on ne sait pas vraiment ce qui est pris en compte”*_
Sur la page de résultats et sur la page dispositif, nous devons :
- l'aider à comprendre que le dispositif est présenté parce qu'il est éligible 
- l'aider à comprendre que les variables affichées sont contextualisées en fonction de son siret et réposnes au questionnaire 

---
### **Proposition**
- [ ] ajouter la fleche de retour arrière (page resultat)
- [ ] Supprimer les pistes de questions sous les thématiques dans le questionnaire (pour alléger)
- [ ] Supprimer le fil d'ariane sur la page de résultats 

- [ ] Ajouter un bandeau de rappel des données saisies par l'utilisateur. 
1) SIRET "SIRET "XXXXXXXXXXXXXX"
2) Effectif "Entre n et n employés" (issu de la réponse au questionnaire)
3) Secteur d'activité "nom de la sous classe" issu du SIRET
 ou  "artisanat"/ "industrie, fabrication, production"/"tourisme, restauration"/"secteur tertiaire"/"activité agricole"/"autre activité" issu du questionnaire
4) Localisation "code postal + commune" 
(Pour chacun des 4 blocs limiter le nombre de caractères à 30 caractères max, espaces inclus))
- le bouton "retour" permet à l'utilisateur de revenir à la dernière étape du formulaire)
- le bandeau est sticky

[cf maquette ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=5159%3A138396&mode=design&t=QgWJvmlwUZYu6UUv-1)

[prototype ](https://www.figma.com/proto/tHgzORFkJYTVspsQgR2kg6/TEE-V5?page-id=1436%3A131849&type=design&node-id=5159-138396&viewport=-9304%2C711%2C0.2&t=lEsDNTRfPAgqCw6w-1&scaling=min-zoom&starting-point-node-id=2641%3A126694&mode=design)

### **🖥 Version desktop**
**Sur la page de résultats**

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/1543cf70-03bb-4bef-b997-7981b161f5f4)

**Variante du bandeau sur une fiche dispositif**

- [ ] Ajouter la mention "Cette aide correspond à vos critères d'éligibilité"
- [ ] Passer le bandeau en vert (vert de la charte à 50% + un nouveau vert pâle # D2F2E8)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/9fbb2db5-9917-4218-83d7-7d02db11d169)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/7467c8d2-de2f-4bf4-a8c7-1b4e67c760c3)

[ cf prototype](https://www.figma.com/proto/tHgzORFkJYTVspsQgR2kg6/TEE-V5?page-id=4712%3A119315&type=design&node-id=5389-123907&viewport=-1592%2C-1043%2C0.06&t=l1hIFHzSM5u2ROry-1&scaling=min-zoom&starting-point-node-id=4712%3A127937&mode=design)

### **📱Version mobile**
Dans le menu des filtres (cf ticket [#452](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/452))

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8372aff5-0d81-4f82-b0f8-92109142aa89)

**Comment by jbledevehat** [comment]
@ColineLebaratoux Je veux bien prendre 15min pour comprendre les interactions sur ces informations. Car c'est aussi important d'avoir en tête comment possiblement changer celles-ci.

**Comment by ColineLebaratoux** [comment]
@jbledevehat j'ai mis à jour le ticket avec les corrections discutées tout à l'heure

**Comment by ColineLebaratoux** [comment]
@jbledevehat @JulienParis, le dernier testeur doutait de son éligibilité aux aides proposées sur la page de résultat. 
C'est un retour récurent des précédents tests. 
Je lui ai montré le figma avec l'aperçu de ce fil d'ariane reprenant les critères d'éligibilité. Mais selon lui, ce n'était toujours pas assez clair. 

Sa suggestion, ajouter un "vous êtes éligible" pour rassurer l'utilisateur et lever le doute : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8d91a86a-6df2-47ee-a344-0113bf5fc9e7)

En effet, on est pas sûr à 100% de son éligibilité, avec les éligibilités spécifiques mais permet d'améliorer l'UX.
qu'en pensez-vous ?

**Comment by ColineLebaratoux** [comment]
@yvalentin, on supprime la fonctionnalité de modification sur ce ticket

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/a409180e-77a4-40b4-99cb-c6f357bb3c0e)

**Comment by yvalentin** [comment]
https://tee-preprod-pr749.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @yvalentin !

- [ ] Est-ce que tu peux augmenter un peu la hauteur du bandeau vert sur la fiche dispositif + mettre en gras le texte "Cette aide correspond à vos critères d’éligibili
<img width="918" alt="Capture d’écran 2024-05-27 à 16 37 32" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/030bfada-1330-45b8-bc23-a27b1f088275">
té"

- [ ] Est-ce que tu peux décaler le "retour" sur la gauche, ferré sur les filtres
![Capture d’écran 2024-05-27 à 16 33 37](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/ca99f5d6-c766-4cf0-bbb5-ba6c7d90ec3f)
![Capture d’écran 2024-05-27 à 16 35 04](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/9342bcb5-b805-4d75-b0c0-0d8f76970e3d)
![Capture d’écran 2024-05-27 à 16 36 17](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/95c8c69a-d4f0-4d4d-a2e9-7b3ed1f4ad29)

**Comment by ColineLebaratoux** [comment]
L'évolution du fil d'étapes du formulaire était sur ce ticket @yvalentin (noyé dans d'autres évolutions, au temps pour moi)
❌ Le fil d'ariane prend trop de place en longueur et n'est pas utilisé par les utilisateurs pour revenir sur chaque piste de question.
❌ Sa présence pose question “d’accord, je comprends pas trop l’interêt de ce truc. en fait ici, la liste de gauche (parle du fil d’ariane) j’avais pas compris ce que c’était. je pensais que c’etait un menu du site ou des filtres comme sur le site de la fnac par exemple. j’avais pas compris que c’etait pour revenir en arrière. c’est bizarre.”

- [ ] Supprimer les pistes de questions sous les thématiques dans le questionnaire (pour alléger)
Je crée un nouveau ticket sur ce sujet [#800](https://github.com/betagouv/mission-transition-ecologique/issues/800#issue-2325743714)
