### ISSUE TITLE
importer des nouveaux dispositifs

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#571]
nouveaux : 
- Démarche d’éco-conception - Bretagne 
- Parcours Adaptation au changement climatique
- Formation ecogestes en CHR
- Formation réferent tourisme durable 
- bonus réparation

mise à jour du texte :
- Formation Ademe

**Comment by ColineLebaratoux** [comment]
@celinebagault, j'ai relu et corrigé les 4 nouvelles lignes. 
Quelques remarques :
- "Démarche d’éco-conception - Bretagne" => Tu renvoies en étape 1 vers [ce formulaire de contact. ](https://www2.bretagne.cci.fr/Developpement-durable/demande-rdv). 
- Idem pour "Formation référent tourisme durable"  => tu renvoies en étape 1 vers [ce formulaire de contact](https://www.cciamp.com/produit/contact/1063406)
Pour les dispositifs de ce type, il me semblait que la marche à suivre était de passer par notre formulaire de contact pour passage de relai avec PDE. (je trouve que ça fait doublon de renvoyer vers un autre formulaire de contact de la CCI). Qu'en pensez-vous @jrayneau @jbledevehat  

- Idem pour "Formation ecogestes en CHR" Tu affiches ici le nom, mail & le numéro de téléphone du contact cci. C'est top pour l'utilisateur mais on n'a encore jamais fait ça pour un autre dispositif. ça vaut le coup de se poser la question, ça ferait jurisprudence ! Qu'en pensez-vous @jbledevehat @jrayneau ?
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/0803ca8c-b569-4574-9d68-b0b90833c84d)
=> je propose d'ajouter le contact mail dans un CTA "inscription par mail" qui ouvre l'application mail de l'utilisateur avec l'adresse mail du contact en destinataire.
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/c6d8a9b7-c62f-4c64-9985-6591afe02ff5)



autre retour rédactionnelle @celinebagault : 
- J'ai remarqué que tu avais opté pour renseigner le contenu des programmes dans la rubrique "description longue" et mettre la marche à suivre pour postuler dans les rubriques "étapes". Je te conseillerai de faire l'inverse car les étapes sont les contenus les plus valorisés sur l'UI de la page dispositif (contrairement à la description longue qui se trouve en bas de page, replié sur mobile) et les utilisateurs ont besoin de comprendre avant toute chose le contenu du programme. 
=> J'ai supprimé les descriptions longues et j'ai ajouté le contenu dans les étapes.

**Comment by jbledevehat** [comment]
@ColineLebaratoux @celinebagault Oui il faut passer par Conseillers-Entreprises et oui il ne faut pas mettre de nom/prénom dans nos outils, c'est à CE d'être cet annuaire. Donc à mon sens, ce n'est pas un dispositif activable en autonomie.

**Comment by ColineLebaratoux** [comment]
ok @jbledevehat je corrige les lignes dans ce sens

**Comment by jbledevehat** [comment]
On est d'accord oui

**Comment by ColineLebaratoux** [comment]
@ttdm tu peux importer les mises à jours sur les lignes dispositifs ?

**Comment by ttdm** [comment]
@ColineLebaratoux 

Je vais pouvoir mettre à jour les dispositifs depuis baserow sous peu. Ce ticket sera ensuite très rapide. 

Pour les dispositifs cité dans le premier message : 
- ecoconception-bzh : RAS
- adatation-bzh : RAS 
- ecogeste-PACA : RAS
- bonus-reparation : il y a un conflit dans les tailles. Il est noté toutes tailles mais limité à 249 ensuite
- tourisme-durable-paca : il n'y a pas de thème ciblé et aucun secteur d'activité n'a été ciblé.
- formation ademe : déjà mis à jour.

**Comment by ColineLebaratoux** [comment]
Merci @ttdm, c'est complété
