### ISSUE TITLE
Ajouter 2 filtres dans l'annuaire (Opérateurs + Régions) 

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#597]
- [ ] Ajouter 2 filtres sur la région et sur l'opérateur de contact (Suite aux besoins des opérateurs pour améliorer légèrement la recherche dans l'Annuaire)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/becaa222-812e-463f-bf76-a1f3ce79dd72)
---

📱version mobile : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/c92db67b-5bea-4286-baee-4bf0b552c531)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/63ffa7e7-9263-400a-9a9b-d7ef64ca47f7)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/bdbe8aed-0ec7-4f98-8c78-352962b3cb05)

ticket lié : vision produit #218

**Comment by jbledevehat** [comment]
@JulienParis @yvalentin ce n'était pas une bonne idée de vous avoir mis tout les 2 dessus. Qui de vous 2 prends le ticket ? Pour savoir où ça en est ?

**Comment by oumeimaelisbihani** [comment]
Pour les filtres régions, est ce que quand on sélectionne une région, on veut explicitement les dispositifs correspondant uniquement à cette région ou bien ceux qui correspondent à cette région et ceux nationaux ?

**Comment by oumeimaelisbihani** [comment]
aussi avec ces deux nouveaux filtres ça pose question sur le centrage de l'accordéon [https://tee-preprod-pr754.osc-fr1.scalingo.io/](url), est ce qu'il vaut mieux mettre les filtres en haut ?

**Comment by ColineLebaratoux** [comment]
Le lien ne fonctionne pas "This view no longer exists"

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr754.osc-fr1.scalingo.io/ là ça devrait etre bon !

**Comment by ColineLebaratoux** [comment]
En fait, je pense qu'il faut supprimer le comportement sticky des filtres, ça facilitera l'ouverture des accordéons. ça a du sens aussi parce que les filtres thématiques restent en haut. ok pour toi ?

**Comment by oumeimaelisbihani** [comment]
yep c'est bon pour moi ! du coup centré en haut avec un léger padding ?

**Comment by oumeimaelisbihani** [comment]
en effet c'est que les filtres opérateurs/région ne sont pas encore terminés donc pas encore à la bonne taille !

**Comment by ColineLebaratoux** [comment]
On peut garder le même emplacement que celui vu ensemble initialement

**Comment by oumeimaelisbihani** [comment]
donc en fonction de la carte du premier dispositif ?

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr754.osc-fr1.scalingo.io/ version de test ici

**Comment by ColineLebaratoux** [comment]
petit détail : 

- [ ] Peux-tu trier les opérateurs par ordre alphabétique ?


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/9924c2be-e344-4db0-8bd6-27e793b70f17)

**Comment by oumeimaelisbihani** [comment]
c'est bon version à jour https://tee-preprod-pr754.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Super, je valide le ticket
