### ISSUE TITLE
Intégrer 3 dispositifs DDFIP (crédits d'impôt)

### ISSUE THREAD

**Issue by celinebagault** [betagouv/mission-transition-ecologique#604]
- [ ] intégrer ces 3 dispositifs : 

- industries vertes
- certification en agriculture biologique
- Navires utilisant des énergies propres

**Comment by ColineLebaratoux** [comment]
Merci @celinebagault, j'ai relu et complété la description de ces dispositifs. 
Je les ai tous les trois ajouté comme "dispositif activable en autonomie"
j'ai enlevé les liens vers les-aides.fr > je trouve ça étrange pour un utilisateur d'être renvoyé vers une autre plateforme qui agrège des aides. Du coup, j'ai ajouté quelques infos supplémentaires dans nos conditions d"éligibilité et dans la rubrique 'en savoir plus"

**Comment by ttdm** [comment]
Petites questions : 

- Sur l'excel il y a une trentaine de dispositifs "prêts pour la prod" mais pas "en prod". Vous confirmez qu'il faut mettre en prod uniquement ces trois dispositifs et ne pas se fier à "prêt pour la prod" ?
- En tant que dev, j'attends d'avoir une issue pour me dire spécifiquement quel dispositif je passe en prod et quand je le fais, je coche la case en prod (et ajoute son id fiche dispositif)

**Comment by ColineLebaratoux** [comment]
Oui en effet il y a des dispositifs prêts pour la prod, en attente de réalisation [de ce ticket](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/390#issue-2026248201). Il s'agit de dispositifs similaires avec des déclinaisons régionales. Est-ce que @pierrecamilleri t'a briefé sur ce ticket ?

**Comment by jbledevehat** [comment]
@ColineLebaratoux pour relecture

**Comment by ColineLebaratoux** [comment]
Hello @ttdm, 
J'ai compris que le nouveau process de mise à jour permettait d'intégrer les dispositifs "prêts pour la prod" automatiquement en 24h. C'est bien ça ? 
Si c'est le cas, pourquoi ces 3 dispositifs ne sont pas en prod ?
Merci !


Par ailleurs, concernant [cette discussion ](https://github.com/betagouv/mission-transition-ecologique/issues/604#issuecomment-2046846413), j'ai retiré le tag "prêt pour la prod" pour l'ensemble des dispositifs régionaux en attente de la mise en place de champs conditionnels (ticket #390)

**Comment by ttdm** [comment]
Bonjour coline, 

Quelques petites précisions : 
- le filtrage est effectué sur la valeur "en prod" et non "prêts pour la prod". En particulier vis à vis de tous les dispositifs régionaux ;) 
- il n'y a pas de mise en ligne automatique, il y a création automatique, tous les 24h, d'une "pull request" github qui peut être validée par chacun d'entre nous si la personne se sent compétente pour valider les changements. Pour les changements d'édito en particulier, tout le monde peut se sentir compétent ! Pour les projets, il n'y a rien de très technique non plus. Lorsqu'ils y a de nouveau dispositifs en prod, il faut être assez vigilent sur les champs publicodes et je pense que c'est le moment ou seul Yohann et moi peuvent valider. 

Si je comprend bien, je passe les 3 dispositifs listés sur ce ticket en prod ?

**Comment by ColineLebaratoux** [comment]
salut @ttdm ! 
ok merci pour ces infos, c'est plus clair. 
Donc oui, ils sont prêts pour la mise en ligne. Je change le statut de ces 3 dispositifs en statut "en prod". 
C'est tout bon comme ça ?

**Comment by ttdm** [comment]
@ColineLebaratoux Seul deux des 3 dispositifs sont dans la PR géénrée automatiquement aujourd'hui mais comme je le disais pour une ajout de dispositif, il faut tout de même faire une vérification manuelle pour le publicodes donc je reprend manuellement le ticket ;)
En principe je fais ça aujourd'hui.

**Comment by ColineLebaratoux** [comment]
Merci @ttdm ! désolée pour l'accent et les informations manquantes. Je complète l'édito pour corriger l'éligibiliét sectorielle.
