### ISSUE TITLE
Ajouter un message sur le formulaire de contact pour engager davantage l’utilisateur a écrire son besoin (enjeu de qualification)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#623]
- [ ] Ajouter un message sur le formulaire de contact au niveau du champ "quel est votre besoin ?"

> Pour vous aider au mieux, nos conseillers ont besoin d'éléments de contexte. 
> N’hésitez pas à nous détailler votre projet, vos besoins ou vos questionnements.

[Cf Proposition UI ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4477%3A25759&mode=design&t=xzikLEWjvC2rdbkY-1): 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/43c27abe-f075-41fe-b67f-dc95a04a187f)

=> [Lien vers l'illustration ](https://drive.google.com/file/d/1o76rre7LPfykwKKkz7HbgghF22gJEmZc/view?usp=drive_link)

----

Corrections front du formulaire de contact qui peuvent être réalisées en même temps que le #627 

----
Réflexion du 21/03 : **Comment engager davantage l’utilisateur a laisser un message ?**
Objectifs : Des demandes mieux qualifiées
Qui permettrait de : Gagner du temps en diminuant les appels de Céline ou les mails de PDE auprès des utilisateurs pour qualifier la demande

Problème : 
- 40% des utilisateurs ne complètent pas le message du formulaire de contact 
- Souvent des utilisateurs qui complètent un grand nb de dispositifs qui ne laissent pas de message 

Hypothèse : 
- L'utilisateur ne sait pas comment remplir le message pré-rempli
- L'utilisateur se sent anonyme 
- L'utilisateur ne se sent pas engagé par son message 
- L'utilisateur ne sait pas a qui le dispositif est envoyé, il jète des bouteilles à la mer
- L'utilisateur ne trouve pas le dispositif correspondant à son besoin, 
- L'utilisateur fait plusieurs demandes pour maximiser ses chances 

Idées : 
- Afficher le nom de l'entreprise pour engager l'utilisateur 
- ajouter un message à côté de "Quel est votre besoin ?" du type : "Ces informations nous permettront de constituer un dossier à votre nom. Donnez-nous le maximum de détails pour que nous puissions vous aider au mieux". 
"pour vous aider les conseillers ont besoin d'éléments de contexte..." (cf PDE)
- rendre obligatoire la saisie d'un message 
- A terme, mettre le formulaire de contact au niveau du projet et pas seulement au niveau du dispositif (pour éviter d'avoir autant de demandes que le nb de dispositif positionné sur le même projet)
- humaniser le formulaire avec la tête d'un conseiller

**Comment by celinebagault** [comment]
Je me demande si a minima, on pourrait rendre obligatoire le champs message (ou au moins signaler par l'astérisque rouge, que ce n'est pas un champs optionnel). 

Et peut-être ajouter un message à côté de "Quel est votre besoin ?" du type : "Ces informations nous permettront de constituer un dossier à votre nom. Donnez-nous le maximum de détails pour que nous puissions vous aider au mieux".

**Comment by ColineLebaratoux** [comment]
Autre idée, on pourrait ajouter ta photo pour rendre moins anonyme le formulaire 😄

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/bae43f51-3827-4ea4-ae6a-10fb44437778)

**Comment by jrayneau** [comment]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/8970478/d7e7db7b-1dfb-4f16-b8d2-9cfc2c32c5d3)



![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/8970478/f47db36a-2044-438c-8be3-2259e0c1fa74)

**Comment by dolemoine** [comment]
hello @ColineLebaratoux, petite question sur le sizing du texte. Comme on a un container centrale qui est moins large que ce tu as mis sur la maquette, le texte est renvoyé à la ligne dans le bandeau : 



![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/e05e949f-a12a-4551-9737-c4cac886f23a)

Comment tu veux gérer ça ? Est-ce Ok de le laisser comme tel ? Ou est-ce qu'on réduit la taille du texte pour que ça rentre sur 2 lignes ?

**Comment by dolemoine** [comment]
@ColineLebaratoux dernière question, comment souhaites-tu que le bandeau soit intégré en version mobile ? 


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/0a769afc-8248-4083-a2f8-1c51a1718be8)

**Comment by ColineLebaratoux** [comment]
Je te propose de supprimer l'illustration, de diminuer la taille du texte et de supprimer le retour à la ligne entre les 2 phrases si possible. 
ok pour toi ?

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/4230ea96-c777-43ac-b143-c03367a86a40)

**Comment by dolemoine** [comment]
@ColineLebaratoux voilà le lien pour validation : https://tee-preprod-pr757.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
C'est parfait !
