### ISSUE TITLE
Accessibilité : correction au niveau champs des formulaires

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#627]
Corrections sur l'étape SIRET et sur le formulaire de contact : 

- [ ] Ne pas placer les labels dans le placeholder => cf proposition maquette ci-dessous
- [ ] Description - obligatoire, intégrant un exemple par défaut du format attendu => cf proposition maquette ci-dessous

<img width="467" alt="Capture d’écran 2024-05-03 à 15 08 35" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/c0d4bf09-b185-470d-af63-292b48346ee0">

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/6e04bedb-74f2-44d6-9b3b-b324ca40bb75)

sources : 
https://www.systeme-de-design.gouv.fr/elements-d-interface/blocs-fonctionnels/societe/
https://www.systeme-de-design.gouv.fr/elements-d-interface/blocs-fonctionnels/adresse-electronique

**Comment by jbledevehat** [comment]
Un lien avec #470 ?

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai l'impression que la partie Description est déjà obligatoire avec un texte prérempli. Est-ce que tu as souvenir d'un ticket précédent pour ce point là ?

**Comment by ColineLebaratoux** [comment]
@dolemoine, Je me suis mal exprimée sur le ticket : 
 

- [ ] "Ne pas placer les labels dans le placeholder" => on supprime la description du format attendu à l'intérieur du champ de saisie 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/9906e73b-e079-454c-a2e8-d188a86dbea2)


- [ ] "Description - obligatoire, intégrant un exemple par défaut du format attendu" => il est obligatoire d'ajouter une description du format attendu. Il faut donc ajouter la mention : "ex : "Boucherie Sanzot" ou N° SIRET "13002526500013" au dessus du champ de saisie. (on fait évoluer la recherche par Nom, Siret, siren cf ticket #333)

**Comment by dolemoine** [comment]
@ColineLebaratoux voilà le lien pour validation : https://tee-preprod-pr734.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine 
voilà mes retours sur le formulaire de contact : 
- [ ] il manque le format attendu pour le mail, pour le téléphone
- [ ] il manque un espace avant les ":"

**Comment by dolemoine** [comment]
@ColineLebaratoux sur la maquette présentée, l'adresse mail d'exemple est soulignée : 


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/a264543e-3001-4d14-b277-77ee9b97300c)

Dans le DSFR, elle ne l'est pas :


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/dbc2192a-450d-42ac-b4a3-35aae2ef51f6)

Est-ce que tu souhaites qu'elle le soit ?

**Comment by ColineLebaratoux** [comment]
bien vu, c'est pas nécessaire qu'elle soit soulignée

**Comment by dolemoine** [comment]
@ColineLebaratoux c'est corrigé
