### ISSUE TITLE
CMS projets/progam : création de la base des "actions-projets" #BenchmarkTool

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#630]
- [x] Inventaire des actions sur Miro : https://miro.com/app/board/uXjVKdk9jNk=/
- [x] Définir l'outil le plus adapté afin d'avoir une validation de l'objet Program et Projet : ~~Excel~~, notion, airtable...
CF début d'écriture des actions sur le tableau excel [tableau ici](https://docs.google.com/spreadsheets/d/1TSnfITAvIm4TjF0gcOfxiy7G-HVbNPsU/edit?usp=sharing&ouid=110808165297464445892&rtpof=true&sd=true) ou sur un airtable 
   - Voir [bench](https://www.notion.so/accelerateur-transition-ecologique-ademe/f3519a60249445d59ff67facf3025a09?v=cd7c5177b5954c44a1a0ba8a17c0d428)
- [x] Choix de Baserow 

[cf maquette d'une fiche projet (à date)](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6026%3A476423&t=fWgIX5WgMlHxXJom-1)

- [ ] Ecrire la base projet**

**Comment by jbledevehat** [comment]
- [ ] Créer un tableau pour décrire les actions : fusionner [tableau Coline ici](https://docs.google.com/spreadsheets/d/1TSnfITAvIm4TjF0gcOfxiy7G-HVbNPsU/edit?usp=sharing&ouid=110808165297464445892&rtpof=true&sd=true) et [tableau JB ici](https://ademecloud-my.sharepoint.com/:x:/r/personal/jeanbaptiste_ledevehat_ext_ademe_fr/_layouts/15/Doc.aspx?sourcedoc=%7B9df3ab68-2f86-4cd3-b509-d0a3a87577af%7D&action=edit&activeCell=%27EcoFlux%2BTPEgagnante%27!C75&wdinitialsession=316bf000-1a5f-8670-bcad-e416ad161e62&wdrldsc=2&wdrldc=1&wdrldr=AccessTokenExpiredWarning%2CRefreshingExpiredAccessT)
- [ ] Acter les thématiques (proposition de 7 = fusion rénovation et efficacité énergétique) https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/335
- [ ] Ecrire les 30 premières actions


---
ticket lié #630

**Comment by ColineLebaratoux** [comment]
---
Rappel du retro-planning des actions : 

**UX UI**
- [x] Maquette des actions dans le parcours "j'ai un objectif en tête" =[ prototype ici](https://www.figma.com/proto/tHgzORFkJYTVspsQgR2kg6/TEE-V5?page-id=4712%3A119315&type=design&node-id=4712-119316&viewport=-18829%2C-10336%2C0.48&t=H3PH6C4qi67lM0Hz-1&scaling=min-zoom&starting-point-node-id=4712%3A119316&mode=design)

**Atelier avec les partenaires**
- [x] [CR du cadrage des actions](https://docs.google.com/presentation/d/1tCdc66XF3s0W1RRjgHmxtPTj5vdaA3Mx05lNHWTM_T4/edit#slide=id.g2bfa934f71b_0_108) 
- [x] Faire une slide sur le retroplanning des actions pour le prochain comité opérateur
- [x] Planifier un atelier de travail actions projets ?

**Synchro avec l'Ademe / les autres startups**
- [x] Point avec l'intra de Plus fraiche ma ville + Martin ?
- [x] Point avec Agir

**Tests utilisateurs**
- [x] [voir Plan de test](https://www.notion.so/accelerateur-transition-ecologique-ademe/Plan-de-test-Mars-2024-512d5c6303c644cd83e6d1266d09c4af?pvs=4)
 cf ticket #631 

**Ecriture des actions**
- [x] Déterminer la bonne granularité des actions et écrire les guidelines 
- [x] Créer un tableau pour décrire les actions [tableau Coline ici](https://docs.google.com/spreadsheets/d/1TSnfITAvIm4TjF0gcOfxiy7G-HVbNPsU/edit?usp=sharing&ouid=110808165297464445892&rtpof=true&sd=true) ou [tableau JB ici](https://ademecloud-my.sharepoint.com/:x:/r/personal/jeanbaptiste_ledevehat_ext_ademe_fr/_layouts/15/Doc.aspx?sourcedoc=%7B9df3ab68-2f86-4cd3-b509-d0a3a87577af%7D&action=edit&activeCell=%27EcoFlux%2BTPEgagnante%27!C75&wdinitialsession=316bf000-1a5f-8670-bcad-e416ad161e62&wdrldsc=2&wdrldc=1&wdrldr=AccessTokenExpiredWarning%2CRefreshingExpiredAccessT)
- [x] Acter les thématiques (proposition de 7 = fusion rénovation et efficacité énergétique) https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/335
- [ ] Ecrire les 30 premières actions

**Comment by ColineLebaratoux** [comment]
@jrayneau Est-ce que tu penses que tu pourrais nous aider à identifier l'outil le plus adapté pour notre base projets ? Peut-être en regardant des bonnes pratiques d'autres startups ?

Si ça peut aider sur la réflexion, j'avais commencer à poser [ce tableau excel ](https://docs.google.com/spreadsheets/d/1TSnfITAvIm4TjF0gcOfxiy7G-HVbNPsU/edit?usp=sharing&ouid=110808165297464445892&rtpof=true&sd=true) avec les différents champs requis sur une fiche projet : titre, thématique liée, description, image, urls pour aller plus loin, dispositifs liés, conditions d'affichage...

**Comment by ColineLebaratoux** [comment]
Hello @ttdm @yvalentin ! 
Vous en êtes où sur ce benchmark ? 
Notre coeur balance vers quel outil ?

**Comment by jbledevehat** [comment]
Choix terminé... Suite du travail sur la #794
