### ISSUE TITLE
Déplacer le filtre "type d'aide" sur un bandeau latéral gauche

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#655]
- [x] déplacer le filtre "type d'aide" sur un bandeau latéral gauche, comportement sticky au scroll
- [x] Supprimer le fils d'arianne actuel (page resultat)

**Page de résultats**
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/76ed582e-e2a2-4e1a-a831-520a17e2f74d)

**Annuaire**
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/becaa222-812e-463f-bf76-a1f3ce79dd72)
---

📱version mobile : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/c92db67b-5bea-4286-baee-4bf0b552c531)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/63ffa7e7-9263-400a-9a9b-d7ef64ca47f7)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/bdbe8aed-0ec7-4f98-8c78-352962b3cb05)

**Comment by oumeimaelisbihani** [comment]
Version de test disponible ici : https://tee-preprod-pr735.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
hello ! 
Merci. Y'a des calages un peu différents de la maquette. On peut en reparler demain ? 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/4913cb7f-a4ad-4d2b-91c7-cb47782fe9e9)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/ecd89770-08cd-4a4e-a63f-0f7239c096cf)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/0fcd82a8-dd81-451e-9001-a01953ecdc9f)

**Comment by oumeimaelisbihani** [comment]
mince en effet, là ça devrait etre mieux : https://tee-preprod-pr735.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani 
Ces points sont bons : 👍
- [ ] Mettre un titre filtre & renommer "filtrer par nature de l'aide" et reprendre l'UI de la maquette si possible
- [ ] La taille des checkbox (à mettre plus petites) 

En revanche, je veux bien que tu fasses une repasse lundi sur : 
 
- [ ] Caler la largeur du "bandeau thématique" avec celui des blocs "dispositifs d'aide" 
- [ ] Déplacer les filtres plus bas au niveau du premier bloc "dispositif d'aide"


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/7787fe24-705e-44e7-b29b-0d30716216f0)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/40856aa8-3115-4eaf-a7de-c2843891bd58)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/2ecfb7aa-5abf-4123-9203-1379607b39e3)







petits détails UI : 
- [ ]  mettre les chechbox en noir
- [ ] réduire l'espacement entre filtre et types d'aides

**Comment by oumeimaelisbihani** [comment]
Les modifications sont ici >> https://tee-preprod-pr735.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani 
Super le placement dans les colonnes et la largeur des blocs dispositifs et bandeau thématique 👍
- [ ] Toujours concernant la hauteur des filtres, c'est possible de le caler en fonction du haut du premier bloc dispositif ? Pour que quel que soit la page(annuaire, parcours 1 ou 2) il ne flotte pas au milieu de la colonne ?

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/1d6fe4c5-3cc6-44e9-aed4-7684e5b184e1)

mini détail UI pour finir
- [ ] passer "Filtres" en gras

**Comment by oumeimaelisbihani** [comment]
La dernière version est ici : https://tee-preprod-pr735.osc-fr1.scalingo.io/ avec la colonne de filtres centrée

**Comment by ColineLebaratoux** [comment]
Super @oumeimaelisbihani ! Je passe le ticket en Valid
