### ISSUE TITLE
SEO - Personnalisation des titres et description des pages et dispositifs

### ISSUE THREAD

**Issue by ttdm** [betagouv/mission-transition-ecologique#666]
Le titre et descriptif des pages depuis un moteur de recherche gagnerait à être amélioré. 

Pour référence, voici le résultat de la recherche d'un programme lié à l'eau
![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/15088539/090d149b-3825-4494-9a15-5febe3aac064)

Liste des tâches  : 
- [x] Définir le contenu à ajouter en titre et en description
- [x] (Optionnel) Ecrire/générer ce contenu 
- [x] Ajout/modif des balises 'title' et 'meta description' avec le contenu correspondant.

**Comment by ttdm** [comment]
@jrayneau  

J'ai codé une première implem. 
Pour l'instant, le titre de chaque page sera : "Transition écologique - {Nom du programme}"
Et la description sera la description courte du programme. 

Deux exemple :  
- Transition écologique - Programme Volontaire Français ACT 
- L’ADEME soutient financièrement les entreprises volontaires dans la mise en œuvre d'un modèle économique compatible avec une trajectoire bas carbone. 
Vous serez accompagné avec la méthode ACT Pas à Pas (Assessing Low Carbon Transition), une méthode structurante, progressive et sur le long terme qui aide les entreprises à réduire significativement leurs émissions de gaz à effet de serre.

- Transition écologique - Audit label Clef Verte
- Réalisez un audit pour vous aider à obtenir le Label Clef verte, le premier ecolabel de tourisme durable destiné aux hébergements touristiques et restaurants. Ce label certifie l'engagement de votre établissement en faveur d'un tourisme plus durable.

ça te semble OK ? 
Pour info, rien ne force google à utiliser ces deux infos, ce sont des suggestions de notre part. Généralement google utilise assez fidèlement les titres. C'est moins le cas pour les descriptions.

**Comment by jrayneau** [comment]
Je partage ton point Dorian. 
Je trouverais ça bien de rajouter la notion d'entreprise 
Par exemple : "Transition écologique des TPE & PME - {Nom du programme}"
Mais est-ce trop long ?
