### ISSUE TITLE
SIRET - revoir process sur backend

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#673]

**Comment by ttdm** [comment]
@yvalentin 
Petit point tech sur les api : 
https://api.gouv.fr/guides/quelle-api-sirene

En gros : 
- Les points d'API Sirene et api-entreprise sont fait pour récupérer les données une fois l'entreprise déjà sélectionnée, en utilisant un champ (SIRET ou Siren) exact.
- Pour la sélection à partir de champs partiel, il faut utiliser : https://api.gouv.fr/documentation/api-recherche-entreprises
- les entreprises non-diffusibles ne sont pas sur recherche-entreprise mais sont sur Sirene. 
- Pour le backend, l'API Sirene semble vraiment OK pour le moment. Le seul intérêt à avoir accès à l'api entreprise serait de récupérer un effectif à jour mais le ratio dev vs gain me semble réduit.
