### ISSUE TITLE
Regression UI Responsive

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#690]
J'ai pu observer une régression UI qui n'a pas été corrigé ou qui est revenue 

- [x] rétablir les marges droite sur les contenus "promesse" + "description courte"

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/f700c039-86db-42ac-86af-3a6015de24bf)

- [x] rétablir les marges gauche droite autour des contenus "en savoir plus" + "conditions d'éligibilité" 

Voir l'issue #585 
Voir les captures suivantes :

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/2809273a-1767-4dd1-bd0e-0eb45ebdd5f5)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/6ce0b6d5-7c83-4f82-8d2d-cebb3d054782)

**Comment by yvalentin** [comment]
@jbledevehat La capture ne fonctionne pas :-(

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr888.osc-fr1.scalingo.io/ > pour tester

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani ! Pourrais-tu me régénérer ce lien ?

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr888.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani @yvalentin C'est tout bon, sauf pour le formulaire de contact qui est trop reserré. 
Est-ce possible de lui rajouter des marges comme avant ? 
![Capture d’écran 2024-07-23 à 16 58 01](https://github.com/user-attachments/assets/7a607a35-0023-48b9-9163-122dd48fe9c5)
![Capture d’écran 2024-07-23 à 16 57 45](https://github.com/user-attachments/assets/d1f37329-e020-4cb2-9408-b38a181cfee8)

**Comment by oumeimaelisbihani** [comment]
c'est modifié : https://tee-preprod-pr888.osc-fr1.scalingo.io/
