### ISSUE TITLE
Ajouter un CTA "contacter un conseiller" sur les fiches dispositifs

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#691]
**TO DO**

- [x] Ajouter un CTA "contactez un conseiller" qui renvoie vers le formulaire de contact (scroll en bas de page) => pour tous les dispositifs sauf ceux "activables en autonomie. 
- [x] Changer le titre du formulaire de contact "contactez un conseiller +"nom de l'opérateur" cf maquette
- [x] enlever le bandeau en bas de page "nous contacter" de toutes les fiches dispositifs 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/18b80d40-2be6-4f9c-864a-b486d7083457)

----
**Rappel des irritants utilisateurs**

**Problèmes relevés par les utilisateurs :** 
👎 L'étape "déposez votre demande d'aide" pose question car elle n'est pas accompagné d'un lien pour réaliser l'action _“déposez votre demande d’aide, il n’y a pas de lien. là je ne sais pas ou ca se passe. combien de temps ca va me prendre ?"_

👎 L'étape "L'ADEME étudie votre demande d'aide" pose question car aucun délai n'est mentionné _“ca va prendre combien de temps ? les dossiers doivent etre finalisés avant le 31/12 ? Mais je ne sais pas combien de temps l’Ademe prend pour étudier mon dossier”_

👎 Problème transverse à toutes les fiches dispositifs : le formulaire de contact n’est pas visible _"Après relecture de la page je comprends que soit je me debrouille tout seul, soit avant d’aller dans le dur je peux prendre contact avec un conseiller. C’est pas évident à comprendre. Ca m’oblige à aller en bas de la page. je l’ai pas vu tout de suite"_

👎 Les utilisateurs aimeraient retrouver une liste de recommandation certifié par l'ADEME à l'étape "Choisissez le bureau d'étude" _"L’avantage d'une plateforme comme la votre serait de regrouper les aides ET les contacts : pas que des subventions, aussi des presta référencés sur des bilans carbones, des études…"_

👎 Problème transverse aux financements, la description de l'aide est très succincte (contrairement aux accompagnements qui sont expliqués en plusieurs bulletpoints dans la partie "au programme")

👎  le formulaire n'est pas assez visible
 “C’est pas évident à comprendre. Après relecture de la page je comprends que soit je me debrouille tout seul, soit avant d’aller dans le dur je peux prendre contact avec un conseiller. C’est pas très clair. Ca m’oblige à aller en bas de la page. je l’ai pas vu tout de suite. ca pourrait etre un petit picto contact sur la droite qui m’amène en base de page ? ou alors peut être ajouter dans les étapes : 1) contacter un conseiller (facultatif) avec un lien qui amene en bas au niveau du formulaire.”

👎   on donne deux actions possibles sur une fiche dispositif = confusant
Cet accompagnement vous intéresse ? avec le formulaire
nous contacter / Echanger avec un conseiller

**Comment by ColineLebaratoux** [comment]
@jbledevehat @jrayneau ok pour vous ?

**Comment by ttdm** [comment]
Le boutton est à ajouter **SAUF pour les dispositifs activables en autonomie**. 

On est mûr sur ce sujet ? 
Pour l'instant, il me semble qu'il n'y a aucune donnée sur le sujet dans les programmes. 
Je peux ajouter un champ "activable en autonomie" oui/non à partir des données excel si l'info y est et que l'on considère que l'info est bonne.

**Comment by ColineLebaratoux** [comment]
Oui, il y a une colonne dans le tableau data qui qualifie en binaire si un dispositif est activable en autonomie.


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/bf457dc9-5db6-4377-b45b-2760ed67ad3e)

**Comment by ttdm** [comment]
@ColineLebaratoux 
Pour validation  : 
Un dispositif non autonome : https://tee-preprod-pr715.osc-fr1.scalingo.io/aides-entreprise/amo-chaufferie-biomasse
Un dispositif autonome : https://tee-preprod-pr715.osc-fr1.scalingo.io/aides-entreprise/extreme-defi-mobilite

C'est possible que la modif sur le titre du formulaire ne soit pas complète mais dans ce cas, peux tu la préciser :)

**Comment by ColineLebaratoux** [comment]
Hello @ttdm Peux-tu régénérer les liens scalingo stp ?

**Comment by ColineLebaratoux** [comment]
C'est parfait @ttdm !
