### ISSUE TITLE
Nettoyer le code publicode dans les dispositifs sur le retour de réponse de l'api `/api/programs`

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#697]
Actuellement, les retours de réponse de l'api pour les dispositifs renvoie une quantité importante de code en relation avec publicode. La seul partie encore utilisé sur le front est en relation avec le filtre sur les thématique

```json
"entreprise . a un objectif ciblé": {
                "une de ces conditions": [
                    "questionnaire . objectif prioritaire . est la mobilité durable"
                ]
            }
```

et pourrait être remplacer par :
```json
"objective": [
                "mobilité durable"
                ]
``` 

Ajouter une fonction de conversion des programs dans la back (avant les retour de fonction) + mettre à jour l'ointerface de reponse:
- libs/backend-ddd/src/program/domain/programFeatures.ts:38
- libs/backend-ddd/src/program/application/programService.ts:22

**Comment by yvalentin** [comment]
@ttdm

**Comment by oumeimaelisbihani** [comment]
@jbledevehat il faudrait vérifier que le filtrage par thématique marche bien comme avant (dans le questionnaire et dans le catalogue) https://dashboard.scalingo.com/apps/osc-fr1/tee-preprod-pr943
