### ISSUE TITLE
Sur la fiche dispositif, modifier date de fin en “date de fin de l’aide” et corriger le picto

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#708]
modifier date de fin en “date de fin de l’aide” et corriger [le picto](https://drive.google.com/file/d/15YYs8qEJ58id-hrOa2xzNcBow0qRzlWW/view?usp=drive_link)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ca8b07bf-0dd1-4ea8-b364-e71cefe31e83)

version cible : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b2b7897f-cf89-4848-ab7b-3f43604eba9a)

**Comment by dolemoine** [comment]
@ColineLebaratoux le lien vers l'app pour validation : https://tee-preprod-pr763.osc-fr1.scalingo.io
