### ISSUE TITLE
Dans les conditions d'éligibilité, remplacer le terme "micro-entreprise" par "entreprise individuelle"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#718]
Retour utilisateur : _"je ne sais pas ce que c'est moi une micro-entreprise"_

- [ ] Sur une fiche dispositif, dans l'encart dédié aux conditions d'éligibilité, remplacer "micro-entreprises" par "entreprises individuelles"

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/2ae3e7bf-cc58-450a-aa51-0a07a99381ba)

NB : cette information est tirée de la colonne "microEntre" sur [le tableau Data ](https://ademecloud.sharepoint.com/:x:/s/P-P-StartupDGE/ERKQ_wqzfFlHi85f0Fg1RRYBO3EwDP1_FwyvxQpOIsCIzg?rtime=CQ042oxq3Eg)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/f3fbc1e6-fbc6-4454-a954-719c783840fc)

**Comment by jbledevehat** [comment]
Attention, il y a une différence entre entreprise individuelle et micro-entreprise. Il faut garder micro-entreprise car c'est un régime spécifique des entreprises individuelles.
