### ISSUE TITLE
Correction UI du footer

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#728]
- [ ] Remplacer le logo conseillers entreprises par service-public.fr

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/beabc4f2-a052-40d3-b7d9-c6f559cbb79b)

- [ ] Faire tenir l'ensemble des logos des partenaires sur une même ligne 
- [ ] Supprimer le logo TEE dans le footer 
- [ ] Ajouter une ligne de séparation entre les logos des partenaires et les liens vers les pages accessibilité,...
- [ ] Revoir la version mobile

**Actuel** 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/521ada06-5fcb-4d56-8b34-a4210b6d1e4f)

**Version cible** 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/e80963ab-7525-40c1-a5b8-144ddae81e51)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/063d5b75-3234-4814-af2f-52e68c632bfa)

**Comment by dolemoine** [comment]
@ColineLebaratoux, quelques questions sur les points : 

- Remplacer le logo conseillers entreprises par service-public.fr : aujourd'hui le lien renvoie vers https://conseillers-entreprises.service-public.fr, je change pour https://www.service-public.fr ?
- comportement des logos partenaires : c'est le point de rupture qu'il faut probablement revoir, car sur une certaine largeur d'écran, on a bien l'allignement sur une ligne  : 


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/fcc3793f-f52a-4de8-a168-e03ee149d906)

Du coup je pense que ça va un peu de paire avec la révision de la version mobile, on peut peut-être se caler un point tous les deux pour ça ?

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine !
- Tu peux garder le lien vers https://conseillers-entreprises.service-public.fr/
- Supprimer le logo TEE dans le footer => rien à ajouter à la place / on enlève le lien 
- est-ce que je peux te laisser faire une proposition pour le comportement des logos partenaires pour atteindre la cible des maquettes ? et on en discute après ?

**Comment by dolemoine** [comment]
@ColineLebaratoux voilà le lien pour le check de la version modifiée : https://tee-preprod-pr756.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Hello ! 
Top, ça fonctionne bien le passage entre les différentes taille d'écran 
Je me demande juste pourquoi il n'y a pas le même espacement entre chaque logo ? 
<img width="1360" alt="Capture d’écran 2024-05-24 à 09 37 33" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/4a12f9ea-ad45-4944-8a20-f9e7fc389380">

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai corrigé l'espacement de l'icône "lien externe" et des logos partenaire.


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/a146de31-9e46-4534-acb4-a955a42b098a)



Pour le logo service public, il était de base plutôt alligné sur la gauche, comment souhaites-tu qu'il soit agencé ?
Tu peux me ping sur matermost si tu veux qu'on en parle en direct (c'est peut être plus simple ? )

**Comment by ColineLebaratoux** [comment]
C'est très bien, tu peux laisser comme ça !

**Comment by dolemoine** [comment]
Parfait,
Je te remets la lien pour validation : https://tee-preprod-pr756.osc-fr1.scalingo.io/
