### ISSUE TITLE
Mise à jour des mentions légales & politique de confidentialité

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#732]
Pour les mentions légales, reprendre le travail de Lilian avec : 
https://github.com/incubateur-ademe/legal-pages/blob/main/packages/markdown/src/LegalNotice.md

Dont les variables sont : 

{{siteUrl}} : https://mission-transition-ecologique.beta.gouv.fr/

{{siteHost.name}} : Scalingo
{{siteHost.address}} : 13 rue Jacques Peirotes 67000 Strasbourg, France
{{siteHost.email}} : hello@scalingo.com

{{element_thirdParties}} : 
La recherhce d'entreprise est effectuée via l'[API recherche entreprise](https://api.gouv.fr/les-api/api-recherche-entreprises). Les données sont ensuite précisées via l'[API SIREN](https://api.gouv.fr/les-api/sirene_v3)

 {{licenceUrl}} : https://github.com/betagouv/mission-transition-ecologique

---

Pour la Politique de confidentialité :

{{table_thirdParties}} : Reprendre la 7.1 de https://impactco2.fr/politique-de-confidentialite
{{table_cookies}} : Pareil pour cette section reprendre https://impactco2.fr/politique-de-confidentialite

Nous ajouterons les éléments nécessaire concernant Brevo et les cookies, plus tard.

**Comment by yvalentin** [comment]
- done pour la page mentions légales (fait à la main)

A prévoir intégration du plugin d'ADEME : https://github.com/incubateur-ademe/legal-pages

**Comment by yvalentin** [comment]
Mise a jour avec le plugin de l'incubateur de l'ADEME

Pages concernées :
- https://tee-preprod-pr845.osc-fr1.scalingo.io/donnees-personnelles
- https://tee-preprod-pr845.osc-fr1.scalingo.io/mentions-legales

**Comment by yvalentin** [comment]
holà !
A valider de nouveau !! (et oui, dsl ;-) )

- https://tee-preprod-pr845.osc-fr1.scalingo.io/donnees-personnelles
- https://tee-preprod-pr845.osc-fr1.scalingo.io/mentions-legales

**Comment by yvalentin** [comment]
@jbledevehat 
A valider ;-)

**Comment by jbledevehat** [comment]
Yes nickel
