### ISSUE TITLE
Ajouter une fonctionnalité "copier le lien" sur la fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#733]
- [ ] Ajouter un CTA "copier le lien" à côté du titre du dispositif 
- Au clic sur le CTA, affichage de "lien copié" avec l'url copié dans le presse papier de l'utilisateur (url qui conserve les données de l'entreprise)
- réutiliser le composant mis en place par @oumeimaelisbihani sur la fiche projet, en modifiant les couleurs. (ici : bouton en fond blanc, texte en gris > état actif texte en vert) (Pourquoi ne pas laisser le bouton en bleu ? => garder un unique CTA principal sur la page "contactez un conseiller)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/542e3e30-0935-4d91-ba50-543e047e5a66)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/05ff7749-f5e9-4a9d-a95b-5e57712d8b9a)

**Comment by ColineLebaratoux** [comment]
ok pour toi @jbledevehat ?

**Comment by ttdm** [comment]
Petit détail pratique, quel lien ?
Le lien exact qui conserve les données de l'entreprise, ex : https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat/investissement-contrat-chaleur-renouvelable?choix-du-parcours=j-ai-un-projet&siret=siret-non-renseigne&effectif=TPE&activite=tourisme&region=Centre-Val+de+Loire&objectifs=diminuer+ma+consommation+d%27eau

Ou le lien générique de la fiche : https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/investissement-contrat-chaleur-renouvelable

Les deux ont des utilités différentes (interne entre service dans une boite vs partage à un contact extérieur).

**Comment by ColineLebaratoux** [comment]
Bonne question ! 
A priori, actuellement, j'ai l'impression que ça suffirait de donner le lien générique, puisque les données affichées sur la fiche ne dépendent pas des données saisies. 

En revanche, demain, on va intégrer des champs conditionnels en fonction de la région / taille de l'entreprise : cf ticket #390 

Donc, en anticipation de cette évolution, le lien à communiquer doit être le lien exact qui conseeve les données de l'entreprise. 

Tu es d'accord ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux @jbledevehat à tester ici >> https://tee-preprod-pr958.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani 
Est-ce que tu peux centrer le bouton sur le titre ? 
![Capture d’écran 2024-08-12 à 11 41 40](https://github.com/user-attachments/assets/d3345419-caba-47a2-8d12-2588a89d6301)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux c'est bon normalement ici >> https://tee-preprod-pr958.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani ça me semble encore un tout petit peu trop haut. 
Je veux bien également que tu ajoute aussi un espace entre le titre et le bouton : 
<img width="506" alt="Capture d’écran 2024-08-12 à 15 06 07" src="https://github.com/user-attachments/assets/a4aaa670-db8f-4c23-9883-85ce01c41057">

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr958.osc-fr1.scalingo.io/ >> les changements sont la !

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani 
Pour que ce soit clean, il faudrait que le texte soit centré dans le bouton. 
Ici, tu as déplacé le texte vers la droite en conservant le même placement du bouton. 

N'hésite pas à me dire s'il y a une complexité que je ne mesure pas !
<img width="525" alt="Capture d’écran 2024-08-13 à 14 40 33" src="https://github.com/user-attachments/assets/b98febbb-98f5-4b4c-aac0-72d9e9e37a59">

**Comment by oumeimaelisbihani** [comment]
@jbledevehat @ColineLebaratoux c'est modifié : https://tee-preprod-pr958.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
Tout roule, c'est top
