### ISSUE TITLE
Ajouter l'en-tête de l'annuaire

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#737]
Après évolution des filtres sur l'annuaire, mettre une en-tête et les filtres thématique comme sur la page résultat 
cf. capture #597

**Comment by jbledevehat** [comment]
@oumeimaelisbihani Suite échange avec @ColineLebaratoux et @yvalentin je ventile cette demande pour la transmettre à @dolemoine

**Comment by dolemoine** [comment]
@jbledevehat juste pour être sûr de bien comprendre : 


![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/8b23a908-01b3-4755-bdc2-fc0ebc8e04ba)

**Comment by ColineLebaratoux** [comment]
@dolemoine, il s'agit de l'entête juste au dessus. 
<img width="740" alt="Capture d’écran 2024-05-28 à 10 27 10" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/b228072e-5f9f-48bd-b804-8cace049e385">

**Comment by dolemoine** [comment]
Merci pour les précisions!

**Comment by dolemoine** [comment]
@ColineLebaratoux  le lien pour validation : https://tee-preprod-pr790.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci, 
Est-ce qu'il y aurait un moyen pour passer le texte de description sur 5 lignes max sur mobile ? Le "etc." sur une ligne m'embête. 
Tu peux aussi un peu diminuer la marge en haut et en haut du bloc pour que le bandeau d'entête prenne moins de place [(comme sur cette maquette de l'annuaire des projets](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6342-423624&t=XyiilytQmkMIm8xx-1))
![IMG_6823](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/214f9d34-a40a-46c0-8d38-2b9992b2ac77)

**Comment by dolemoine** [comment]
Yes, je regarde pour faire les adaptations pour la version mobile!

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai poussé une modification sur le lien de test pour que tu puisses y jeter un coup d'oeil : https://tee-preprod-pr790.osc-fr1.scalingo.io/

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai refait une passe sur ce ticket, nouvelles modifs sur l'app de test si tu peux jeter un coup d'oeil. Si ok on merge aujourd'hui : https://tee-preprod-pr790.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
j'ai l'impression que ca n'a pas bougé. C'est toujours "accompagnement" et financements...proposés" => à remplacer par "aides"..."proposées"
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/ec927fcb-5156-4ad9-9ee4-e6ed000f2798)

**Comment by dolemoine** [comment]
@ColineLebaratoux  c'est ok pour le text

**Comment by ColineLebaratoux** [comment]
Merci ! Une dernière correction, navrée 😅 Céline vient de relever une faute : "partenaires publics"

Réalisez une recherche parmi les aides à la transition écologique des entreprises, proposées par l’ensemble des partenaires publics : ADEME, Bpifrance, CCI, CMA, etc.

**Comment by dolemoine** [comment]
@ColineLebaratoux done!

**Comment by ColineLebaratoux** [comment]
Merci !
