### ISSUE TITLE
Ecrire les bonnes pratiques d'écriture des projets

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#742]
- [ ] Ecrire les Guideline d'écriture des fiches projets pour chaque champ (ton of voice, nb de caractères, objectif visé...)
---
**Bonne pratique d'écriture des fiches projets :**
- écrire en parallèle les résultats que l’on peut retrouver côte à côte sur une fiche projet pour s’assurer de leur complémentarité / facilité à les différencier
- ajouter des mots clés associés à chaque projet : bilan GES = bilan carbone / panneaux solaires = photovoltaique / biomasse = chauffage au bois / chaleur fatale = chaleur de récupération
- mettre en place un process de validation des fiches actions par des experts

**Comment by celinebagault** [comment]
Je veux bien participer à rédiger ces guidelines @ColineLebaratoux
