### ISSUE TITLE
Reprendre les mentions des secteurs d'activités renseignées dans le formulaire "je préfère compléter mes informations manuellementt"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#751]
- [ ] Reprendre les mentions des secteurs d'activités renseignées dans le formulaire "je préfère compléter mes informations manuellement" sous la forme de "artisanat" "industrie" "tourisme, restauration" "tertiaire" "agricole" "autre secteur d'activité"
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/8b3c6947-4c88-4c4f-8ce2-c2a802035710)

- [ ] Changer sur le bandeau latéral 
- [ ] Dans le texte personnalisé

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/343bba01-31a6-43f5-96bc-ef210f858625)

- [ ] sur le formulaire

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/f593714e-a56c-4dc2-954a-6f4be378ab8e)

**Comment by ColineLebaratoux** [comment]
Non j'ai malheureusement aucun retour utilisateur sur ce point. 
Je propose de changer ce qu'on avait décidé, suite à une discussion avec @yvalentin. On se dit que "tourisme, restauration" ce n'est pas les mêmes secteurs et que changer le choix utilisateur peut porter à confusion. 
A priori c'est un minor fix, mais ce n'est pas urgent non plus à faire évoluer.

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai besoin de précision sur le besoin, j'ai l'impression que pas mal d'élément ont bien évolué depuis la création de ce ticket. On en parle à mon retour si ça te va.

**Comment by ColineLebaratoux** [comment]
ok !

**Comment by dolemoine** [comment]
@ColineLebaratoux @jbledevehat lien pour test ici : https://tee-preprod-pr982.osc-fr1.scalingo.io/

J'ai effectué assez peu de changement compte tenu du fait qu'un certains nombres d'éléments ont probablement déjà été modifié via d'autres PR sur le projet

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine ! 
ce ticket est bien toujours d'actualité. 
tu veux qu'on en discute rapidement ?

**Comment by dolemoine** [comment]
@ColineLebaratoux  on peut en parler demain matin si ça te va ?

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai apporté les modifs mais j'ai une question sur le fait d'utiliser le terminologie "activité artisanale", notamment sur le formulaire "Mon entreprise a une activité de type `Activité artisanle`", ce qui est un peu redondant. Idem pour le texte dans le header "du secteur `activité artisanale`. Qu'en penses-tu ?

**Comment by ColineLebaratoux** [comment]
oui tu as raison, gardons uniquement "artisanal"

**Comment by dolemoine** [comment]
@ColineLebaratoux  c'est modifié, je te laisse refaire un tour pour valider: https://tee-preprod-pr982.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@dolemoine je vois encore uniquement tourisme pour "tourisme, restauration"

est-ce que tu peux reprendre les textes suivants : "artisanat" "industrie" "tourisme, restauration" "tertiaire" "agricole" "autre secteur d'activité" ?

**Comment by dolemoine** [comment]
@ColineLebaratoux peut-être vider ton cache ?  car chez moi pas de soucis : 
![image](https://github.com/user-attachments/assets/77d8cb2a-c7f5-4fbc-a0ba-154338d00ff9)

**Comment by ColineLebaratoux** [comment]
ah oui mais pas sur cette page : 
<img width="1089" alt="Capture d’écran 2024-08-28 à 15 54 16" src="https://github.com/user-attachments/assets/54cadf49-75a0-4425-9c0b-daba6fcd53e9">

**Comment by ColineLebaratoux** [comment]
tu pourrais mettre agricole plutôt qu'agriculture aussi ?
