### ISSUE TITLE
rationnaliser les couleurs de la charte TEE

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#753]
- [x] Définir les couleurs principales et leurs déclinaisons "light"

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/0de8ffef-2ba7-4404-86af-509cd8e484c1)

[lien maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=5974%3A309211&t=rH3myyMG7o5xq7G2-1)

**Comment by ColineLebaratoux** [comment]
@yvalentin, j'ai posé ici les nuances de nos 4 couleurs principales, en jouant sur la saturation (les blancs) et la luminosité (les noirs). 
Est-ce que ça te convient ? 

Tout fonctionne sauf le bleu DSFR (#000091) qui tire trop vers le violet lorsqu'on le désature alors que j'aurais besoin d'un bleu clair. 
Je propose : 
- soit de modifier la couleur du bleu foncé qu'on utilise pour une teinte très proche (#001891) mais qui permet d'avoir un bleu clair en light
- soit de conserver le bleu DSFR mais d'ajouter des couleurs light non issuées de ses nuances

**Comment by ColineLebaratoux** [comment]
hello @yvalentin qu'en penses-tu ?

**Comment by dolemoine** [comment]
@ColineLebaratoux ok pour nous pour la charte de couleurs, avec le bleu (et ses nuances) que tu as défini, on va en profiter pour nettoyer le code en appliquant cette charte de manière globale.

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine ! est-ce que tu pourras me donner le mise à jour des codes couleurs des nuances pour que je les mette à jour sur Figma ?

**Comment by dolemoine** [comment]
@ColineLebaratoux ok je regarde pour te récupérer ça

**Comment by dolemoine** [comment]
@ColineLebaratoux la liste des codes couleurs de l'app après harmonisation : 

bleu
100% #001891
30% #92a4ff
10% #dbe1ff

vert
100% #1ebe8e
30% #b4f3e0
10% #e6fbf5

violet
100% #6a62f4
30% #d2d0fc
10% #f0effe

rouge
100% #fca081
30% #fee3d9
10% #fff6f2

jaune
100% #facf35
30% #fef1c2
10% #fffaeb

on utilise aussi un gris par endroit (bouton, bordure...), donc je l'ai ajouté également à la liste
gris
100% #777777
30% #d6d6d6
10% #f1f1f1

**Comment by ColineLebaratoux** [comment]
Je note. Merci @dolemoine  !
