### ISSUE TITLE
Faire évoluer la page de résultats du parcours "je ne sais pas par où commencer" pour intégrer les projets 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#760]
En tant qu'utilisateur néophyte, je souhaite découvrir des idées de projets et des aides pour engager la transition écologique de mon entreprise.

**Sur la page de résultats du parcours "je ne sais pas par où commencer"** : 
- nouveau composant "onglet" avec 2 onglets : Des idées d’actions à mettre en place / Vos aides financières pour naviguer entre la vue liste des projets / liste des dispositifs
- Fonctionnement actuel des tag thématique : seules les tag thématiques prioritaires de l'utilisateur sont affichés (en fonction de ses réponses au formulaire)
- Liste des projets avec un format carte (photo + titre + description courte) (chargement de toutes les cartes projets, pas de pagination)

[voir maquette ](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6571-369849&t=c0ApYmuYqJar9KVJ-1)

**Onglet "Des idées d’actions à mettre en place"** 
- Vue par défaut avec le filtre thématique "tous" 
- Uniquement sur le tag filtre "tous", ajout d'un bandeau Prio couleur vert #E6FFF7 + titre "Voici les actions par lesquelles commencer pour votre _taille de l'entreprise_  du secteur _nom du secteur_
- Ajout de l'illustration en largeur d'écran 12 colonnes. Le supprimer pour les autres tailles. (possible ou galère ?)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/d6fdc139-86e3-49ec-a6bb-075d9eeadcd9)
- affichage sur le bandeau des 3 projets prioritaires toutes thématiques confondues (avec le rating de la colonne prio). Les cartes prio se distingue des autres grâce à un badge vert "à faire en priorité" et un contour vert.
- au clic sur un tag thématique, la bandeau disparait. Les cartes prio se distinguent unqiuement avec le contour et le tag vert. [voir maquette tag construction](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6584-415119&t=c0ApYmuYqJar9KVJ-1) [ou tag énergie](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6571-226284&t=c0ApYmuYqJar9KVJ-1)

- Sur mobile, on supprime le bandeau vert et l'illustration, pour ne garder que le badge vert "à faire en priorité" et le contour vert. [voir maquette mobile](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6571-406355&t=c0ApYmuYqJar9KVJ-1)

**Onglet "Vos aides financières"** 
- reprendre la version actuelle de la page de résultats du parcours "je ne sais pas par où commencer"
- le filtre thématique reste actif entre les deux vues 
[voir maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6571-403219&t=c0ApYmuYqJar9KVJ-1)

**Comment by dolemoine** [comment]
@ColineLebaratoux autre question : 
- sur la maquette desktop, le résumé du titre ainsi que le nombre de résultats sont passés en couleur bleue (et italique pour le nombre de résultat), mais pas en version mobile, c'est volontaire ?

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/f0c01f5d-cf79-4831-9c3d-978c6ec316f8)



![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/cb18fdac-2884-4ee1-bfe0-d7e5c25e6556)

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine ! 
Pour répondre à tes questions : 
- le nombre de résultats indiqués doit bien prendre en compte le nombre de projet maintenant, et non plus le nombres de dispositifs trouvés pour l'entreprise ? => oui dans l'onglet "des idées d'actions à mettre en place" il s'agit bien du nb de projets 

- est-ce que le bandeau du filtre par thème est à généraliser partout ? (annuaire, j'ai un projet en tête, je ne sais pas par où commencer)? => oui, il me semble qu'il est déjà partout

-  est-ce que j'aligne ce bandeau à gauche comme sur les maquette ? => oui je veux bien !

- pour le moment je ne gère pas l'action "J'ai un autre projet" n'est-ce pas ? => exact, on se le garde sous le coude pour une prochaine version

- sur la maquette desktop, le résumé du titre ainsi que le nombre de résultats sont passés en couleur bleue (et italique pour le nombre de résultat), mais pas en version mobile, c'est volontaire ? => tu peux le passer en italique bleu partout (tous les parcours, toutes tailles d'écran)

**Comment by ColineLebaratoux** [comment]
@dolemoine j'ai mis à jour le ticket, on peut en rediscuter quand tu veux 🙂

**Comment by dolemoine** [comment]
@ColineLebaratoux , petite suggestion : le bandeau des tags de thématiques étant commun au deux affichages, j'aurai tendance à la glisser au dessus des 2 tabs : 



![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/1e582d09-b8e0-49bd-bda7-a105eb3e1649)

**Comment by dolemoine** [comment]
@ColineLebaratoux autre point. Aujourd'hui en terme de code, la page qui affiche les résultats quand tu suis le parcours "j'ai un objectif précis en tête" et "je ne sais pas par où commencer" est la même. 
En terme de modif, c'est plus simple et plus rapide si je n'ai pas à retoucher ça et à conserver la même chose pour les 2 parcours. On aurait donc également l'affichage des résultats par projet côté "j'ai un objectif en tête".
Est-ce que c'est quelque chose qui pourrait convenir? On peut en discuter de vive voix si ça permet de clarifier ce point.

**Comment by ColineLebaratoux** [comment]
@dolemoine @jbledevehat , on pourrait conserver la même page de résultat pour les deux parcours. Mais pourrait-on conditionner l'affichage de certains éléments : 
Sur la parcours "je ne sais pas par ou commencer" : 
- on enlève le "bandeau prio" vert et les cartes projets prio 
- on ajoute la phrase "Quel est votre projet ?"
- on arrive directement sur lla page de résultat filtré sur la vue thématique choisie par l'utilisateur à la question "Quel est votre objectif prioritaire ?" 

Je suis dispo ce matin si tu veux qu'on s'appelle pour en discuter

<img width="435" alt="Capture d’écran 2024-06-12 à 10 15 46" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/182637d0-bf21-494c-9f92-b8a95b3d0088">

**Comment by dolemoine** [comment]
@ColineLebaratoux tu veux dire sur le parcours "j'ai un objectif précis en tête" non ?

**Comment by ColineLebaratoux** [comment]
Oui oui, désolée ! je viens de corriger 🤭

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine, 
- [ ] Pourrais-tu modifier l'animation slider entre les onglets "des idées d'actions à mettre en place" / "vos aides financières" pour une transition nette [cf prototype](https://www.figma.com/proto/tHgzORFkJYTVspsQgR2kg6/TEE-V5?page-id=4712%3A119315&node-id=6799-392260&viewport=-23005%2C-14044%2C0.48&t=XYgYEbiRP07TAgjs-1&scaling=min-zoom&starting-point-node-id=6799%3A392260&content-scaling=fixed&show-proto-sidebar=1)

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai refait un certain nombre de modifs notamment au niveau de l'alignement des élements pour que ça colle aux maquettes. J'ai encore quelques petites modifs du début du ticket (texte "quel est votre projet") etc...
est-ce qu'on pourrait se faire un tour rapide de mon travail actuel et voir également les modifs que tu as ajoutées dernièrement ? 
pour le moment mes derniers travaux sont dispo sur ma branche, pas sur la demo (je ferai le merge ce soir ou demain matin)

**Comment by ColineLebaratoux** [comment]
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/f61cfbd5-d10b-4471-af3f-da1dfa16a176)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/acb2129d-62d0-47e9-aeab-bc5994bdfe49)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/ddbc2549-d6ab-4f92-a9dd-d17eb3fbbac8)

**Comment by dolemoine** [comment]
@dolemoine aligner le bouton "Filtrer" au même niveau que le nombre de résultats

**Comment by ColineLebaratoux** [comment]
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/6d2ef527-4cf5-4c57-ac0f-4b8a863f3a3e)

**Comment by dolemoine** [comment]
@dolemoine ajout filtre projet par éligibilité de l'entreprise

**Comment by dolemoine** [comment]
hello @ColineLebaratoux , j'ai oublié de te transmettre le lien pour la validation fonctionnelle ... 
https://tee-preprod-pr841.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @dolemoine ! 
Voilà mes retours : 

- [ ]  Peux-tu revoir les espacements pour gagner de la place : 
<img width="1435" alt="Capture d’écran 2024-07-09 à 10 37 47" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/40e23e06-8207-4617-836b-1238b8d086a3">
NB : L'espacement entre le bandeau thématique et la liste de résultat soit être le même sur les 2 onglets "des idées d'actions à mettre en place" "vos aides financières" (ce n'est pas le cas ici)

- [ ] En mobile, il y a un petit décalage entre le composant onglets et les tags au switch entre les 2 onglets.
- [ ] En mobile, au clic  sur "vos aides financières" il faut que l'onglet se déplace sur la gauche pour que l'utilisateur puisse lire entièrement le titre "vos aides financières"

https://github.com/betagouv/mission-transition-ecologique/assets/47628484/fa39f6e0-7cc1-44b6-9642-e04e4c87bce9

- [ ] Est-ce que tu peux ajouter la mention "1 résultat" quand il y a un seul résultat (il me semble qu'il ne s'affiche pas par défaut)

- [ ] Au clic sur une fiche dispositif depuis la page de résultats, onglet "vos aides financières", il faudrait que le bouton retour amène sur le liste de résultats au niveau de la carte du dispositif en question. (aujourd'hui au clic sur retour, on est redirigé vers la liste des idées d'actions à mettre en place)

**Comment by ttdm** [comment]
Pendant ma revue de code, j'ai vu quelques points fonctionnels qui me semblent problématiques, en particulier sur le filtrage des projets listés à l'utilisateur. 

Ce qui me semble désirable est : 

- [ ] dans j'ai un objectif en tête, afficher seulement les projets dont la thématique est la thématique recherchée par l'utilisateur (ce qui donne en moyenne 5 projet par thématique et non 20+ comme maintenant)
- [ ] dans je ne sais pas par ou commencer, le filtrage par objectif me semble correct : on n'affiche que les projets dont la thématique principale est la thématique sélectionnée et pour lesquels au moins un programme est disponible. Par contre, je pense que le tag ne doit pas être affiché s'il n'y a pas de projet éligible. Ex : [ne pas afficher le tag eau ici](https://tee-preprod-pr841.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=83014132100034&effectif=TPE&locaux=proprietaire&mobilite=oui&matieres-premieres=maximum&tri-dechets=oui&dechets=non&gestion-eau=oui&energie=non&audit=non#questionnaire-resultat)
- [ ] dans je ne sais pas par ou commencer, sans filtrage, à mon avis tu affiches trop de résultats. Je pense qu'il faut que tu affiches tous les projets qui appartiennent à une des thématiques dont le tag est visible et pour lesquels un programme est disponible.  Dont probablement juste 8 projets pour le lien du dessus (5+3). ça permet de garder une cohérence pour l'utilisateur. C'est bizarre sinon de passer de 20+ projet non catégorisés à 8 projets catégorisés. 

Je veux bien une confirmation @ColineLebaratoux  sur le comportement attendu, en partiuclier sur le dernier point.

**Comment by ColineLebaratoux** [comment]
Voilà mes retours @ttdm @dolemoine 

- [ ] dans j'ai un objectif en tête, afficher seulement les projets dont la thématique est la thématique recherchée par l'utilisateur (ce qui donne en moyenne 5 projet par thématique et non 20+ comme maintenant)
**=> je suis d'accord. En revanche, pour faciliter la navigation et permettre à l'utilisateur de décourvrir les autres projets sans avoir à revenir sur le questionnaire, je propose d'ajouter ici aussi les tags thématiques. Dans ce cas, le tag "tous" affiche bien l'intégralité des projets pour lesquels il est éligible. [(cf ticket dédié)](https://github.com/betagouv/mission-transition-ecologique/issues/822)**
 

- [ ] dans je ne sais pas par ou commencer, le filtrage par objectif me semble correct : on n'affiche que les projets dont la thématique principale est la thématique sélectionnée et pour lesquels au moins un programme est disponible. Par contre, je pense que le tag ne doit pas être affiché s'il n'y a pas de projet éligible. Ex : [ne pas afficher le tag eau ici](https://tee-preprod-pr841.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=83014132100034&effectif=TPE&locaux=proprietaire&mobilite=oui&matieres-premieres=maximum&tri-dechets=oui&dechets=non&gestion-eau=oui&energie=non&audit=non#questionnaire-resultat)
**=> Si, ça me semble nécessaire d'afficher le tag thématique même s'il n'y a aucun projet éligible. Si l'utilisateur a répondu qu'il avait un fort enjeux sur ses consommations d'eau et qu'il ne voit rien en lien avec l'eau ça peut être perturbant. Il est alors préférable d'afficher cet onglet avec "Aucun projet n'a pu être identifié sur cette thématique..." cf ticket 'Correction UI du message "Aucune aide n'a pu être identifiée ..."
[#748](https://github.com/betagouv/mission-transition-ecologique/issues/748)**
 

- [ ] dans je ne sais pas par ou commencer, sans filtrage, à mon avis tu affiches trop de résultats. Je pense qu'il faut que tu affiches tous les projets qui appartiennent à une des thématiques dont le tag est visible et pour lesquels un programme est disponible. Dont probablement juste 8 projets pour le lien du dessus (5+3). ça permet de garder une cohérence pour l'utilisateur. C'est bizarre sinon de passer de 20+ projet non catégorisés à 8 projets catégorisés.
**=> je suis d'accord ! Le "tous" correspond au cumul des projets issues des thématiques prioritaires.**

**Comment by dolemoine** [comment]
@ttdm @ColineLebaratoux merci pour vos retours, je gère les modifs dans la journée. Je reviens vers vous si question

**Comment by dolemoine** [comment]
@ttdm @ColineLebaratoux j'ai apporté des modifications sur les méthodes de filtrage, j'ai fait plusieurs tours mais je veux bien une repasse de votre côté rapidement pour valider le fonctionnement.
Pour info, sur le parcours je ne sais pas par où commencer, le tag "Tous" ne compte qu'une fois un projet même s'il est taggé sur 2 thématiques, c'est ce qui me semble le plus logique, est-ce que c'est ok pour vous ?

**Comment by ColineLebaratoux** [comment]
Oui c'est parfait comme ça ! Merci @dolemoine !

**Comment by dolemoine** [comment]
hello @ColineLebaratoux et @ttdm,

j'ai apporté par mal de modifications (plutôt tech -> @ttdm) mais aussi des corrections suite à tes remarques @ColineLebaratoux.
globalement tout vos retours ont été traités sauf : 

-  En mobile, au clic sur "vos aides financières" il faut que l'onglet se déplace sur la gauche pour que l'utilisateur puisse lire entièrement le titre "vos aides financières" 
**c'est un comportement attendu du Dsfr, mais il n'est malheureusement pas implémenté côté VueDsfr (la librairie adaptée utilisée sur le projet). Je n'aurai pas le temps de traiter ce point avant de partir. Si ce n'est pas bloquant, je propose qu'on se penche sur ce point dans une phase de stabilisation**

-  Au clic sur une fiche dispositif depuis la page de résultats, onglet "vos aides financières", il faudrait que le bouton retour amène sur le liste de résultats au niveau de la carte du dispositif en question. (aujourd'hui au clic sur retour, on est redirigé vers la liste des idées d'actions à mettre en place)
**Ce point a été identifié également par Yohann, qui semble déjà avoir une piste. Vu que c'est plutôt Oumeima/Yohann qui ont travaillé sur la partie routing, je propose qu'ils y jettent un coup d'oeil @yvalentin @oumeimaelisbihani **

bon je pense avoir fait le tour de tout vos retours, n'hésitez pas à me faire un retour, il se peut que certains élements soient passé à la trappe.

**Comment by ColineLebaratoux** [comment]
merci @dolemoine ! C'est dispo en préprod ou il faut attendre un peu ?

Le point 1 est un peu bloquant car il gène la navigation entre les 2 onglets. @jrayneau l'a également remonté comme un "problème d'affichage" : "sur mobile on est obligé de scroller horizontalement pour voir l'onglet "Vos aides"" Est-ce quelqu'un d'autre pourrait le prendre @yvalentin ?

**Comment by dolemoine** [comment]
pour le moment c'est dispo sur l'url de test du ticket : https://tee-preprod-pr841.osc-fr1.scalingo.io/ , je suis en train de faire le merge avec la branche qui sert pour la demo

**Comment by dolemoine** [comment]
@ColineLebaratoux comme dit sur mattermost, j'ai push une solution provisoire (sous réserve de validation) pour cette histoire de scroll des onglets. tu peux tester ça sur  https://tee-preprod-pr841.osc-fr1.scalingo.io/ le temps que yohann fasse le déploiement sur la preprod

**Comment by ColineLebaratoux** [comment]
Super @dolemoine, ça fonctionne bien ! 
Une petite correction à faire dans un second temps serait de supprimer cette barre grise qui me semble en trop, si c'est possible.
<img width="407" alt="Capture d’écran 2024-07-12 à 09 59 43" src="https://github.com/user-attachments/assets/73c77065-e280-42a6-ba5b-ef6d98adc323">

**Comment by dolemoine** [comment]
@ColineLebaratoux c'est modifié

**Comment by dolemoine** [comment]
@ColineLebaratoux c'est corrigé!

**Comment by ColineLebaratoux** [comment]
C'est parfait, merci !

**Comment by yvalentin** [comment]
> Super [@dolemoine](https://github.com/dolemoine), ça fonctionne bien ! Une petite correction à faire dans un second temps serait de supprimer cette barre grise qui me semble en trop, si c'est possible. <img alt="Capture d’écran 2024-07-12 à 09 59 43" width="407" src="https://private-user-images.githubusercontent.com/47628484/348174025-73c77065-e280-42a6-ba5b-ef6d98adc323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTY2MTIsIm5iZiI6MTcyMDc5NjMxMiwicGF0aCI6Ii80NzYyODQ4NC8zNDgxNzQwMjUtNzNjNzcwNjUtZTI4MC00MmE2LWJhNWItZWY2ZDk4YWRjMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE0NTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODBkODhkYzgyNTU3NGVlZTUzOTJhN2ZiOGZjNDdlNTYwYmZiMTIwOGVmZDY1MmI4MDEyOTM5Njg5YmNhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZjBObDTx-tooWdm-cgKwaRHogYuvOx8McsaLMchipMI">

Attention, il n'ai plus possible de scroll sur les onglets en mode mobile

**Comment by yvalentin** [comment]
@ColineLebaratoux Le ticket est toujours en cours de validation ?

**Comment by ColineLebaratoux** [comment]
> > Super [@dolemoine](https://github.com/dolemoine), ça fonctionne bien ! Une petite correction à faire dans un second temps serait de supprimer cette barre grise qui me semble en trop, si c'est possible. <img alt="Capture d’écran 2024-07-12 à 09 59 43" width="407" src="https://private-user-images.githubusercontent.com/47628484/348174025-73c77065-e280-42a6-ba5b-ef6d98adc323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTY2MTIsIm5iZiI6MTcyMDc5NjMxMiwicGF0aCI6Ii80NzYyODQ4NC8zNDgxNzQwMjUtNzNjNzcwNjUtZTI4MC00MmE2LWJhNWItZWY2ZDk4YWRjMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE0NTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODBkODhkYzgyNTU3NGVlZTUzOTJhN2ZiOGZjNDdlNTYwYmZiMTIwOGVmZDY1MmI4MDEyOTM5Njg5YmNhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZjBObDTx-tooWdm-cgKwaRHogYuvOx8McsaLMchipMI">
> 
> Attention, il n'ai plus possible de scroll sur les onglets en mode mobile

mais il est possible de taper sur chaque onglet pour passer de l'un à l'autre

**Comment by yvalentin** [comment]
@ColineLebaratoux Voici un peu près le rendu de la barre d'onglet sur mon tel... Donc sans le scroll, c'est un peu juste.... :-(



![Image](https://github.com/user-attachments/assets/d83930a8-c35f-403c-a3b8-6f5320bceb83)
