### ISSUE TITLE
Fiche projet

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#765]
En tant qu'utilisateur, je recherche les aides dont je peux bénéficier pour m'aider à réaliser mon projet. 

To do : 

- [x] Création d'une fiche projet intégrant : 
- photo + degradé avec la couleur thématique
- nom du projet
- rubrique "qu'est-ce que c'est" : description synthétique du projet
- rubrique "pour aller plus loin" : liens externes 
- rubrique "mes aides" : 
- 
**si l'utilisateur a renseigné son siret**
> Le texte personnalisé "Voici les études et aides financières pour votre ... du secteur ... en région .... 
> rubrique "Pour étudier votre projet" + cartes "études" éligibles 
> rubrique "Pour financer votre investissement" + carte "financement" éligibles

**si l'utilisateur n'a pas renseigné son siret**
> encart "complétez votre profil" : [voir maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325%3A389240&t=nEpK6jZ2i7UbvyGh-1)
- rubrique "contactez un conseiller" avec les champs supplémentaires
> champ projet  (pré-rempli par le projet en question)
- encart "projets complémentaires" intégrant les autres projets de la thématique (pertinent pour le secteur de l'entreprise)

[🖥 Maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6302%3A340552&t=nEpK6jZ2i7UbvyGh-1)

[📱Maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6302%3A342240&t=nEpK6jZ2i7UbvyGh-1)

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani, [c'est cette maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325-389240&t=wvUF4MKDkCeDqgKE-1)
Au clic sur le CTA "compléter mon profil", l'utilisateur est redirigé vers l'étape 1 (siret) du parcours "j'ai un objectif en tête" 
<img width="521" alt="Capture d’écran 2024-06-17 à 17 20 59" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/5c9c38a6-da0c-4333-bf33-be34f0a9df7a">

**Comment by ColineLebaratoux** [comment]
Mes retours : 

- [ ] Au clic sur les ancres sur le côté gauche, ajouter une animation de scroll (la même que celle sur la fiche dispositif au clic sur "contacter un conseiller" 

- [ ] ajouter une marge en dessous du titre de la page

- [ ]  aligner les noms du titre de la page, des titres des sections et des contenus des paragraphes 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/01a25a63-42e9-450c-b89a-0754dcece96b)

- [ ] prendre les [couleurs principales pour les dégradées des pages](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6254-271572&t=9Daipd7h6G83gXZQ-1) (le vert n'est pas le bon sur la première version à tester) 

- [ ] au clic sur "lien copié" changer l'état du bouton : 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/92908d4a-8480-424b-a0e1-557ba87e1af2)

- [ ] Augmenter et appliquer la même la taille des titres des sections "qu'est-ce que c'est" "pour aller plus loin" "mes aides" [cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6302-340552&t=9Daipd7h6G83gXZQ-1)

- [ ] Mettre l'astérisque en rouge 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/f85038c0-a9d6-4380-967e-d4e4378a8437)

- [ ] Dans le formulaire de contact, rendre éditable le champ "quel est votre projet ?" pré-rempli(pas grisé mais en noir)

- [ ] Aligner les projets complémentaires sur la gauche 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/890fa3aa-c879-48a6-b9ba-7d348d8e7083)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/d02affa3-11dc-4d8e-8acc-c0b3cc517524)

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr834.osc-fr1.scalingo.io/ nouvelle version de test @ColineLebaratoux , juste pour les bulletpoints de la section aller plus loin comme c'est du markdown et pas forcément des bulletpoints, c'est compliqué d'ajouter l'espace. Est ce que ça peut le faire sans ?

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani ! 
Merci. Je teste la fiche "géothermie" c'est ça ? 

Voilà mes retours : 
1) Concernant l'alignement, 
Est-ce que tu peux essayer d'aligner encore un peu ? Je sais qu'il y a un décalage du fait des blocs de contenus des paragraphe, mais visuellement ce décalage m'embête un peu :)
<img width="521" alt="Capture d’écran 2024-06-25 à 11 08 34" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/a216860b-7787-437e-bf00-e48abde09ed7">


2) Concernant les bulletpoints de la section aller plus loin
C'est dommage, on perd en lisibilité. On peut essayer de trouver un moyen de contourner pour ajouter un interlignage ? (une solution serait au niveau de la data, de créer autant de colonnes qu'il y a de bulletpoints non ?)

3) Concernant le bandeau latéral gauche sur la fiche projet : 
<img width="314" alt="Capture d’écran 2024-06-25 à 11 09 33" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/e4b73315-7379-4d32-8905-18202c0a65f1">

- [ ] Corriger "Le projet" par "Qu'est-ce que c'est ?"
- [ ] Peux-tu lui donner un comportement sticky au scroll ?
- [ ] Au clic sur "Mes aides" Peux-tu ajuster l'ancre au niveau du titre "Mes aides" 
- [ ] Idem, Au clic sur "Contact", peux-tu ajuster l'ancre au niveau du haut du formulaire "Contactez un conseiller"
- [ ] Quand on est en haut de page, au clic sur "pour aller plus loin" on a un scroll qui remonte de bas en haut. Ca serait plus harmonieux un scroll de haut vers le bas. C'est possible de l'ajuster ? 

NB : Je ne vois plus les projets complémentaires

**Comment by ColineLebaratoux** [comment]
- [ ] corriger l'alignement sur le bandeau "aucune aide"

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/90a5f35f-5bf8-4095-93dc-ddf81ee0fd24)

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr834.osc-fr1.scalingo.io/ >> j'ai corrigé les aides, les remarques plus haut. Pour les projets complémentaires, j'ai mis que s'il y en avait pas on les affichait pas, est ce qu'il vaut mieux avoir une section vide ?

**Comment by jbledevehat** [comment]
Le hover du bouton n'est pas sur le bouton, mais déborde étrangement
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/22809387/433be16f-1663-40c0-9bc1-99f0a435a3b4)

**Comment by oumeimaelisbihani** [comment]
c'est réglé !

**Comment by ColineLebaratoux** [comment]
Mes retours pour @yvalentin 

---
Concernant les ancres
- [ ] Au clic sur "Mes aides" Peux-tu ajuster l'ancre de sorte que le titre "Mes aides" soit en haut de la page
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/e61d15e3-dbc5-4f77-a271-a519317e5bf7)
- [ ] Au clic sur "Contact" Peux-tu ajuster l'ancre au niveau de sorte que le titre  "Contactez un conseiller" soit en haut de la page
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/462a1731-5798-4688-806b-390ac65dd25d)

---
Concernant les liens externes 
- [ ] Au clic sur un lien "Pour aller plus loin" > ouvrir dans une autre fenêtre

---
Quelques ajustements UI 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/7dc08608-cffe-4d8c-b774-66b167efe436)

- [ ] Aligner sur la gauche "copier le lien" et la barre latérale gauche de liens ancrés
- [ ] Aligner le haut de la barre latérale gauche de liens ancrés avec la description du premier bloc 

---
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/18ed10f9-c8a9-4b01-b5e6-07e2ed4606bf)

- [ ] Ajouter les marges gauche droite en version mobile

---
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/cc1265bc-eeea-40d2-ad7c-f2171a8b789f)

cible : 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/29834c1d-a2a2-4b7a-939a-6cfe1c539799)

- [ ] Revoir l'UI de la partie "projets complementaires" en version mobile (tag arrondis + espacement)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr834.osc-fr1.scalingo.io/ une nouvelle version avec les changements de @yvalentin

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani et @yvalentin !
C'est top ! 

- [ ] Juste un petit retour sur le point " Ajouter les marges gauche droite en version mobile", est-ce qu'on pourrait plutôt aligner les textes sur le titre et la carte dispositif ?

<img width="933" alt="Capture d’écran 2024-07-09 à 21 55 24" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/15c9007a-b21c-477f-8f86-2e4740af9983">

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr834.osc-fr1.scalingo.io/ >> je pense que là c'est mieux

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani @yvalentin Il n'y a plus le filtre coloré sur la photo de la fiche projet [sur la préprod](https://preprod.mission-transition-ecologique.incubateur.net/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=13002526500013&effectif=ME&locaux=proprietaire-et-locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=je-ne-sais-pas&gestion-eau=oui&energie=non&audit=oui&selection-audit=consommation-energie#diag-360)

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani, je peux te demander un mini dernière correction UI ? 

- [ ] Faire remonter la ligne verticale jusqu'en haut de la rubrique "qu'est-ce que c'est" ?

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/550a5a6b-7cb5-425e-889d-43f25a04d4fb)

**Comment by ColineLebaratoux** [comment]
@yvalentin @oumeimaelisbihani, je pose ici un soucis de navigation : 
- [ ] Au clic sur une fiche dispositif depuis la fiche projet, il faudrait que le bouton retour amène sur la fiche projet au niveau de la carte dispositif en question
