### ISSUE TITLE
Ajouter la rubrique "exemples de projets financés par cette aide" sur la fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#768]
En tant qu'utilisateur, lorsque je suis sur une "fiche dispositif", je souhaite comprendre quels projets sont financés par la subvention proposée.

TO DO : 
- [ ] Ajouter sur les fiches dispositifs, un bandeau avec des cartes projets liés : 
- On affiche pas le bandeau quand nous n'avons aucun projet lié

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/c45e12c7-424c-44ed-818d-c30f70542429)

**Comment by ColineLebaratoux** [comment]
Pour info, version originale, plus complexe : 

TO DO : 
- [ ] Ajouter sur les fiches dispositifs, un bandeau avec des cartes projets liés : 
- Sous forme de cartes carrés en défilement carroussel quand il y en a plusieurs 
- Sous forme de cartes horizontal quand il n'y a qu'un seul projet financé
- On affiche pas le bandeau quand nous n'avons aucun projet lié
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/2c4b4002-700e-4142-b121-09daea12da93)



![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/63eae841-8422-4607-abc6-a6f18a882798)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux version en cours ici >> https://tee-preprod-pr966.osc-fr1.scalingo.io/ il vaut mieux tester depuis le catalogue et pour avoir un dispositif avec plusieurs projets : pret-action-climat et un seul projet : accelerateur-decarbonation

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani pour le lien. 
Bon, je suis navrée mais je préfererais qu'on reparte sur la version décrite dans le ticket, sous forme de tag. Celle-ci était une proposition antérieure.
les raisons : 
- C'est plus léger, et dans ce sens ça correspond mieux aux critères d'écoconception de services numériques (RGESN).
- C'est cohérent avec la formalisation des projets présentes sur les fiches dispositifs dans la rubrique "projets complémentaires" sur les fiches projets
<img width="1410" alt="Capture d’écran 2024-08-14 à 10 56 19" src="https://github.com/user-attachments/assets/01de2132-7767-4d23-9362-03088c3412c9">

**Comment by oumeimaelisbihani** [comment]
@jbledevehat @ColineLebaratoux nouvelle version à tester : https://tee-preprod-pr966.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
@oumeimaelisbihani Il y a un parcours étrange qui n'a pas été décrit.
Depuis l'annuaire des aides, j'ai un parcours étrange quand je prend une aide  > Exemple : Tremplin > Je choisis le tag "Tri" et arrive sur la fiche projet Trier ses déchets > Je vois le dispositif "Tremplin" alors que je ne suis pas sur d'avoir cette aide. > Lorsque je clique sur Tremplin, j'arrive sur la première page questionnaire... Je pense que le plus simple serai de revenir simplement en arrière pour revenir sur la page Tremplin.

Il faudra à terme @ColineLebaratoux avoir une zone pour connaitre l'éligibilité d'une aide. J'ai créé la demande suivante : #977

**Comment by oumeimaelisbihani** [comment]
@jbledevehat c'était des erreurs de gestion de route ! Normalement tout marche bien là : https://tee-preprod-pr966.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
C'est bon

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux @jbledevehat suite à la review technique, une dernière question : pour avoir la navigation entre les projets de la section exemple et la fiche détail dispositif j'ai créé une nouvelle route qui donne ça par exemple : https://tee-preprod-pr966.osc-fr1.scalingo.io/aides-entreprise/accelerateur-decarbonation/plan-transition-bas-carbone. Est ce que c'est nécessaire pour vous ou bien http://localhost:4242/projets-entreprise/plan-transition-bas-carbone avoir ça comme lien et donc une fois qu'on clique sur un projet exemple, le seul moyen de revenir à la fiche dispositif c'est le bouton retour (ou retour natif) mais pas le fil d'ariane

**Comment by ColineLebaratoux** [comment]
merci @oumeimaelisbihani. On dirait qu'il y a des bugs : 
- sur ce lien https://tee-preprod-pr966.osc-fr1.scalingo.io/aides-entreprise/accelerateur-decarbonation/plan-transition-bas-carbone quand on clique sur un tag projet ça n'amène pas sur le projet correspondant
- ce lien http://localhost:4242/projets-entreprise/plan-transition-bas-carbone  n'est pas accessible

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux en effet c'est réglé ici : https://tee-preprod-pr966.osc-fr1.scalingo.io/ . Et pour le lien désolé c'était un soucis de copier coller : [https://tee-preprod-pr966.osc-fr1.scalingo.io/projets-entreprise/plan-transition-bas-carbone](https://tee-preprod-pr966.osc-fr1.scalingo.io/projets-entreprise/plan-transition-bas-carbone) marche mieux !

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani 
Merci pour le lien de test ! 
- Avec du recul, je pense que le comportement idéal serait : au clic sur un label exemple de projet sur une fiche dispositif, ouvir la fiche projet dans une autre fenêtre. ça permet à l'utilisateur de garder la fiche dispositif dans une fenetre et de cliquer sur plusieurs projets si besoin. 
- On peut faire pareil pour les projets complémentaires sur la fiche dispositif. 
Qu'en penses-tu ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux c'est modifié ici : https://tee-preprod-pr966.osc-fr1.scalingo.io/ pour les exemples de projets dans la fiche dispositif + dans la fiche projet pour les projets liés

**Comment by ColineLebaratoux** [comment]
super pour les liens externes pour les exemples de projets sur la fiche dispositif. En revanche, je ne vois pas les projets liés sur les fiches projets sur ce lien de preprod

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux j'ai l'impression qu'ils y sont bien : https://tee-preprod-pr966.osc-fr1.scalingo.io/projets-entreprise/bilan-ges ici par exemple il y a stratégie bas carbone et adaptation climat
