### ISSUE TITLE
Modification Description du formulaire

### ISSUE THREAD

**Issue by jrayneau** [betagouv/mission-transition-ecologique#773]
Proposition de l'équipe Conseillers-Entreprises pour : 
- éviter les demandes vides
- mieux visualiser les demandes multiples pour une même besoin

Modifier la description affichée à l'intérieur du champs texte.

**AVANT  :**
Bonjour,

Mon entreprise a une activité de type "...".
Le dispositif "Accélérateur décarbonation" pourrait m'intéresser car
J'ai besoin d'être accompagné(e) sur ...

Merci d'avance pour votre retour

**APRES  :**
Bonjour,

Mon entreprise a une activité de type '..."
J'ai pour projet de ...
J'ai besoin d'être accompagné(e) sur ...

Le dispositif "Accélérateur décarbonation" pourrait m'intéresser.

Merci d'avance pour votre retour

**Comment by ColineLebaratoux** [comment]
ok !
