### ISSUE TITLE
Changer la couleur pour la thématique eau

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#777]
Le violet pâle utilisé est trop clair et se confond avec la couleur des tags par défaut.

Proposition : 

- [ ] utiliser le [bleu roi](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6254%3A271572&t=9uAQA7VQBzecckHS-1) pour la thématique eau 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/1de1b20b-e2a8-488b-92d3-6c372a8b637f)

- [ ] nécessite de mettre à jour également l'illustration eau : 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/82482ad2-bfd3-4826-9ef6-1ac9a0281750)

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr886.osc-fr1.scalingo.io/ > pour tester

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani ! Pourrais-tu me régénérer ce lien ?

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr886.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci ! 
En revanche, je crois que l'illustration n'est pas la bonne. cf svg dans le ticket
![Capture d’écran 2024-07-23 à 17 01 14](https://github.com/user-attachments/assets/39b6e880-8c80-409f-90b8-02811b71d7ef)

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr886.osc-fr1.scalingo.io/ c'est modifié, désolé pour l'oubli
