### ISSUE TITLE
Suivi mise en conformité pages réglementaires

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#779]
Suite à échange avec Lilian : https://www.notion.so/accelerateur-transition-ecologique-ademe/Suivi-mise-en-conformit-pages-r-glementaires-41292e76b5514aacaf738ace7992f9da#0bd2fcd3cc19496599f7c2dcf802955b

**Comment by yvalentin** [comment]
voir #845
