### ISSUE TITLE
Corriger le header avec un menu déroulant "catalogue des projets" "catalogue des aides"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#786]
- [ ] Remplacer le nom "annuaire" par "catalogue "
- [ ] Créer un menu déroulant avec les liens vers les 2 pages (utilisation de la dropdown du dsfr) : 
- Catalogue des aides (ex annuaire)
- Catalogue des projets(new)

- [ ] sur mobile : afficher dans le menu burger : Accueil / Catalogue des aides / Catalogue des projets

[Lien vers la maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325%3A421795&t=nEpK6jZ2i7UbvyGh-1)

En profiter pour : 

- [ ] Mettre à jour le titre sur la page "annuaire" > remplacer par catalogue des aides. [Voir maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325%3A377759&t=nEpK6jZ2i7UbvyGh-1)

**Comment by yvalentin** [comment]
J'ai fait une petite exploration des possibilités...
Malheureusement, le composant DSFR et vue-dsfr ne propose pas de menu de ce type dans le header :-(

J'ai regardé si on pouvais surcharger le vue `DsfrHeader` (par exemple via slot, ou injection d'un nouveau composant `DsfrHeaderMenuLinks`, ...) mais difficilement faisable. Le seul truc que je vois c'est l’utilisation de [teleport](https://vuejs.org/guide/built-ins/teleport.html) afin de remplacer la partie `DsfrHeaderMenuLinks` par nos besoins...

Du coup, ce que j'en pense :
- Refaire le composant vuejs par copié/coller du composant d'origine afin d'avoir les composants `TeeDsfrHeader`  et `TeeDsfrHeaderMenuLinks`, voir `TeeDsfrHeaderMenuLink` (on utilise les composants d'origine pour le reste)
- Passer à TeeDsfrHeader quelques choses du genre (pour les liens) :
```ts
const quickLinks: DsfrHeaderMenuLinkProps[] = [
  {
    label: 'Accueil',
    to: {
      name: RouteName.Homepage
    }
  },
  {
    label: 'Catalogue',
    links: [
      {
        label: 'Programmes',
        to: {
          name: RouteName.CatalogPrograms
        }
      },
      {
        label: 'Projets',
        to: {
          name: RouteName.CatalogProjects
        }
      }
    ]
  }
]
```
- Faire un proposition de PR à vueDsfr afin d'incorporer nos améliorations dans la lib officiel
Argument supplémentaire, l'arrivé d'un [nouveau composant de header amélioré](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants-beta/en-tete-connecte/)

**Comment by dolemoine** [comment]
@jbledevehat le lien pour tester les modifs : https://tee-preprod-pr915.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
Je pense qu'on peut avoir une zone de hover de taille identique. 
C'est étrange d'avoir un grand rectangle pour le catalogue et un petit pour Accueil
<img width="575" alt="Capture d’écran 2024-08-01 à 16 38 53" src="https://github.com/user-attachments/assets/6ab094cd-e4d0-4ef5-b196-50c5122475f5">

Sans rapport, je vois encore les marges sur les cards, peut-être sans conséquence avec cette PR.

**Comment by dolemoine** [comment]
Bien vu pour la taille de bouton, c'est modifié.
Pour les marges blanches, je n'avais pas encore récupéré le travail d'oumeima sur ce point, c'est fait.
