### ISSUE TITLE
Ajouter des "Topbar" pour inciter à ajouter son siret sur les pages catalogue

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#787]
ticket en attente de revue UX #941 

- [ ] Ajouter une "topbar" pour inciter à ajouter son siret sur les pages catalogue des **aides** + lien vers la première étape du parcours "je ne sais pas par ou commencer" (sticky)
[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325%3A377759&t=nEpK6jZ2i7UbvyGh-1)

- [ ] Ajouter une "topbar" pour inciter à ajouter son siret sur les pages catalogue des **projets**  + lien vers la première étape du parcours "j'ai un projet en tête" (sticky)
[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325%3A347586&t=nEpK6jZ2i7UbvyGh-1)

[version mobile](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6342%3A423624&t=nEpK6jZ2i7UbvyGh-1) (non sticky sur mobile)

**Comment by ColineLebaratoux** [comment]
P2 : - [ ] Ajouter une "topbar" sur une fiche dispositif lorsqu'elle est consulté via l'annuaire ou via depuis une url (sans être passé par un parcours) [cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325%3A393437&t=nEpK6jZ2i7UbvyGh-1)
à revoir par @ColineLebaratoux  (1er version sans la Topbar sur la fiche dispositif « je complète mon profil et je vérifie mon éligibilité pour cette aide »

**Comment by jbledevehat** [comment]
@ColineLebaratoux Est-ce que le sticky est uniquement à la racine du catalogue ou aussi dans la page d'un dispositif/projet ?
Car sinon doublon avec la zone dédié dans la page projet, voir doublon avec la page dispositif #977
