### ISSUE TITLE
Ajouter les tags sur les cards objectives de la partie questionnaire

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#798]
- 2 à 3 tags "projets" cliquables dans chaque carte (nécessaire d'identifier dans les données les 2,3 projets exemples)+ état hover DSFR pour bien suggérer le fait que le  tag est cliquable 
- suivi de points de suspension (pour laisser comprendre qu'il y a d'autres projets à découvrir derrière la carte)

Comportement : 
- Au clic sur un tag > direction directement sur la fiche projet correspondante (précédé d'un loader)
- Au clic sur l'image > direction vers la page de résultats filtré sur la thématique correspondante
- rendre accessible les cartes thématiques et les tags (actuellement le tab ne les prend pas en compte)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/797
```

**Comment by oumeimaelisbihani** [comment]
@jbledevehat à tester ici >> https://tee-preprod-pr947.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani est-ce que tu peux me regénérer le lien pour tester les tags stp ?

**Comment by ColineLebaratoux** [comment]
@oumeima.el.isbihani, @Dorian et @Manon Piffault et @jrayneau, Je remets ici votre commentaire sur la clicabilité des tags des projets. Je teste et vous donne mon retour sur ce point :  

> C'est pas évident de comprendre que la carte Thème est cliquable mais pas au même niveau que les tags projets. D'autant plus vrai en mobile où l'on ne voit pas le curseur/main.

**Comment by oumeimaelisbihani** [comment]
désolé le voici : https://tee-preprod-pr947.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani sur mon iphone (safari), je n'ai pas les couleurs de fond sous les cartes thématiques. c'est uniquement chez moi ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux à tester ici : https://tee-preprod-pr947.osc-fr1.scalingo.io/ , nouveautés maintenant les cartes sont cliquables au niveau des titres et des images - l'effet d'ombre se fait aussi au click (notamment pour la version mobile)

**Comment by ColineLebaratoux** [comment]
merci @oumeimaelisbihani, 
C'est pas évident, j'imagine que l'utilisateur risque de cliquer sur les parties non cliquables. 
Complexe de rentre ces zones cliquables ?
![Capture d’écran 2024-09-05 à 10 46 32](https://github.com/user-attachments/assets/a29b63c2-9426-4ec0-84dc-7fd76b5151c4)

Sur mobile, c'est encore plus restreint, puisqu'il n'y a pas d'image. ça me semble problématique pour la navigation.

Si c'est trop complexes, je me demande s'il ne faut pas annuler l'idée des tags cliquables pour privilégier une zone de clic plus grande sur la carte thématique

**Comment by ColineLebaratoux** [comment]
+ réflechir à l'accessibilité des cartes thématiques (les tags devraient être navigables au tab)

**Comment by jbledevehat** [comment]
Aussi preneur de savoir si trop galère car fonctionnellement peut-être obsolète face à nos réflexion de refonte de la navigation

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani ! En revanche, je ne vois pas les changements dont tu parles [sur le lien](https://tee-preprod-pr947.osc-fr1.scalingo.io/questionnaire/objectifs?choix-du-parcours=j-ai-un-projet&siret=42395306600010&effectif=ME#questionnaire). Le déploiement s'est bien fait ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux j'ai trouvé comment rendre navigable au tab sans réduire la zone de click : https://tee-preprod-pr947.osc-fr1.scalingo.io/ donc toute la carte est cliquable pour accéder au theme et les tags cliquables pour les projets

**Comment by ColineLebaratoux** [comment]
génial ! C'est super comme ça 🙌
