### ISSUE TITLE
Avoir plusieurs opérateurs principaux (souci filtre annuaire)

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#802]
Lorsque je sélectionne tous les opérateurs sur l'annuaire j'ai 93 résultats alors que j'ai 100 dispositifs.
Il faut pouvoir associé plusieurs opérateurs principaux. Car c'est la valeur CCI ou CMA qui n'est pas pris en compte.

**Comment by oumeimaelisbihani** [comment]
Test disponible ici >> https://tee-preprod-pr810.osc-fr1.scalingo.io/
