### ISSUE TITLE
Persistence des filtres thématiques

### ISSUE THREAD

**Issue by dolemoine** [betagouv/mission-transition-ecologique#812]
Sur la page annuaire, je sélectionne une thematique
Je retourne sur la page accueil, et fait le parcours "J'ai un objectif précis en tête" sans saisie du SIRET, et je choisi une autre thématique. 

BUG: La thématique affichées dans les résultats est celle choisie précédemment côté annuaire

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/1200fea6-879d-434c-aefa-6b545cf59f65)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/760a30cf-1c2d-4f8e-94af-c66c951f71dd)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/43757076/2e79aa59-b6ba-43e8-a1e4-fc56aed64d12)

---

Les filtres sélectionnés ne sont pas réinitialisés lorsqu'on redémarre un parcours:

1 Faire un parcours
2 Sélectionner des filtres
3 Faire le second parcours -> les filtres sélectionnés le sont toujours

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/816
```

**Comment by jbledevehat** [comment]
@yvalentin pour info je te tag dessus en attendant jeudi

**Comment by yvalentin** [comment]
url pour test :

https://tee-preprod-pr846.osc-fr1.scalingo.io/
