### ISSUE TITLE
La sélection de filtre est conservée même lors d'un changement de parcours de question

### ISSUE THREAD

**Issue by dolemoine** [betagouv/mission-transition-ecologique#816]
Les filtres sélectionnés ne sont pas réinitialisés lorsqu'on redémarre un parcours:

1 Faire un parcours
2 Sélectionner des filtres
3 Faire le second parcours -> les filtres sélectionnés le sont toujours

**Comment by yvalentin** [comment]
> Merged in #812

C'est plus une duplication ou une completion qu'un merged car c'est une issue qui est linked là
