### ISSUE TITLE
Faire évoluer la page de résultats du parcours "j'ai un projet en tête" pour intégrer les projets

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#822]
En tant qu'utilisateur, je souhaite trouver mon projet facilement dans la liste thématique dans l'objectif d'accéder aux aides qui m'aideront à le réaliser. 
ex : Au clic sur une thématique "énergie", j'arrive sur la page de résultats filtrée sur les projets de la thématique "économies d'énergie" pour trouver mon projet de chauffage à bois

**Sur la page de résultats du parcours "j'ai un projet en tête"** : 
- [x] Supprimer "🎉 Félicitations, vous avez terminé !"
- [x] Modifier la phrase personnalisée (ne pas afficher sur mobile)
> "Voilà une liste de projets pertinents pour votre... du secteur ...en Région ..."
- [x] Ajouter l'ensemble des tag thématiques pour permettre à l'utilisateur de naviguer entre les thématique directement sur la page de résultats (sans repasser par le formulaire). L'utilisateur arrive sur l'onglet thématique qu'il a choisit à la dernière étape du formulaire.
- [x] Ajouter "Quel est votre projet ?" entre le bandeau thématique et le nb de résultats
- [x] Diminuer l'espacement entre "Quel est votre projet ?" et entre le bandeau thématique cf maquette
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/c90db010-b203-4ffc-8143-eddc0db1d3a8)

[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=5955-180261&t=7bc8suWGaflxWVg2-1)

**Comment by yvalentin** [comment]
Je remet le contenu du ticket 904 ici... Pas de besoin de ticket pour lui :-)

- [x] Sur la page de résultats du parcours "j'ai un projet en tête", supprimer les 2 onglets.
L'utilisateur est dirigé par défaut sur la page de résultats avec les projets. L'onglet "vos aides financières" n'est pas proposé sur ce parcours.

**Comment by yvalentin** [comment]
@ColineLebaratoux 
Lien pour validation:
https://tee-preprod-pr895.osc-fr1.scalingo.io/

**Comment by yvalentin** [comment]
@ColineLebaratoux J'attend la validation de [903](https://github.com/betagouv/mission-transition-ecologique/issues/903) afin de les mettre en prod quasi en même temps
