### ISSUE TITLE
Regression au niveau du bandeau sur le formulaire de contact

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#838]
- [ ] Augmenter la hauteur du champ de saisie pour le coller au bandeau

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/64e41180-512a-46e6-a12e-0606a9057c9e)

**Comment by dolemoine** [comment]
@ColineLebaratoux url pour vérification : https://tee-preprod-pr865.osc-fr1.scalingo.io
