### ISSUE TITLE
Monorepo: passage sous `nx`

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#842]

**Comment by yvalentin** [comment]
pour test fonctionnel

https://tee-preprod-pr831.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Hello @yvalentin 
J'ai fait des tests sur le parcours je ne sais pas par ou commencer avec plusieurs SIRET, à chaque fois je n'ai aucune aide sur la page de résultats 😬
https://tee-preprod-pr831.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=53806464300025&effectif=TPE&activite=tertiaire&region=Corse&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=oui&dechets=oui&gestion-eau=oui&energie=oui&audit=non&selection-audit=matieres-premieres#questionnaire-resultat

**Comment by ColineLebaratoux** [comment]
Hello @yvalentin !
Tout semble fonctionner sauf l'envoi d'un formulaire de contact :
J'ai essayé avec deux adresses mails différentes, j'ai un message d'erreur
<img width="1305" alt="Capture d’écran 2024-06-26 à 09 48 27" src="https://github.com/betagouv/mission-transition-ecologique/assets/47628484/24599aee-d42c-42f2-9bfc-7970aaec4945">

**Comment by yvalentin** [comment]
Je regarde ça au plus vite ;-)

**Comment by jbledevehat** [comment]
Outre le problème de @ColineLebaratoux Je ne vois pas de loup... Tiens moi au jus des que c'est good @yvalentin

**Comment by yvalentin** [comment]
@ColineLebaratoux @jbledevehat La page stat a été réparé ;-)
