### ISSUE TITLE
Utiliser baserow comme base de donnée de dispositifs

### ISSUE THREAD

**Issue by ttdm** [betagouv/mission-transition-ecologique#859]

**Comment by ColineLebaratoux** [comment]
Hello @ttdm,
Trop bien les dispositifs sur baserow ! J'en profite pour te glisser qq remarques pour y voir plus clair : 
- Est-ce qu'on pourrait faire apparaitre comme une liste à cocher les sections des secteurs d'activités (AAgriculture, sylviculture et pêche, BIndustries extractives, CIndustrie manufacturière...)
- Idem pour le filtre de pertinence par effectif (<5, Entre5et20, Entre20et50...)
- Est-ce que tu prévois une autre mise en forme pour les réponses aux questions du formulaire ? Ce n'était pas très clair sur notre tableau data "*""oui""non""je ne sais pas"...

Enfin, j'ai l'impression qu'il reste pas mal de champs qu'on avait décidé de supprimer non ?
- "thèmes ADEME, sous thème ademe, type de projet ademe"
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/9af14770-9688-4140-b7a3-3844fe283597)

- rénover son batiment, économiser l'énergie , économiser l'eau; réaliser un investissement ...
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/1a721af2-5222-4d39-a3da-2949c989c47b)

**Comment by ttdm** [comment]
> Est-ce qu'on pourrait faire apparaitre comme une liste à cocher les sections des secteurs d'activités (AAgriculture, sylviculture et pêche, BIndustries extractives, CIndustrie manufacturière...)
> Idem pour le filtre de pertinence par effectif (<5, Entre5et20, Entre20et50...)

Malheureusement non. Je vais les transformer en case à cocher (au cours des 2 prochaines semaines, quand je pourrais facilement vérifier que cela ne crée aucune modification des données). Par contre je ne peux pas les faire apparaitre comme une liste. A priori ça ressemblera à ça : 
![image](https://github.com/betagouv/mission-transition-ecologique/assets/15088539/59f8583c-60e4-4991-826e-175dc350d07a)

Je suis d'accord avec ta remarque, c'est pas terrible comme solution. Je poserai la question sur le forum baserow pour savoir s'ils voient une meilleure solution. 

 mais je ne peu xpas

> Est-ce que tu prévois une autre mise en forme pour les réponses aux questions du formulaire ? Ce n'était pas très clair sur notre tableau data "*""oui""non""je ne sais pas"...
Je prévois une sélection multiple avec chacune des réponse aux question + un réponse "tous". ça te semble ok ? 
(C'est la même chose qu'aujourd'hui mais avec des sélections donc plus contraint / moins source d'erreur.)

Pour les suppressions, effectivement il reste beaucoup de champs à supprimer. 
Je voulais avoir un retour de JB parce qu'on avait fait toute la liste des champs (notamment une partie des champs vers la fin du tableau). Pour les thèmes et sous thèmes ademe, j'avais gardé l'information inverse en mémoire. 
Dans un premier temps, je les ai déplacés à la fin de la table pourqu'ils soient isolés avant des les supprimer.

**Comment by ttdm** [comment]
Pour information, j'ai terminé de porter les programmes sur baserow = on obtient exactement la même chose sur baserow que ce que l'on obtenait sur excel.

Et premier bilan, il y a beaucoup plus de données non utilisées que ce que j'avais identifié initialement. 

La plupart des questions ne sont pas du tout utilisées. 
Par exemple, toutes les colonnes sur le ciblage de la taille des entreprises ne sont pas utilisées (uniquement l'éligibilité)
Tous les derniers champs qui sont globalement les anciens thèmes ne sont pas non plus utilisé. 
Il n'y a rien non plus avec les audits 

Il faudrait que l'on refasse une réunion, @ColineLebaratoux @jbledevehat  pour savoir si je développes les fonctionnalité correspondantes ou si on supprime ces champs.
