### ISSUE TITLE
Sur mobile, ajouter un état "séléctionné" sur les cartes dispositifs

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#868]
Sur mobile : 

- [ ] ajouter un état "séléctionné" sur les cartes dispositifs(au tap sur une carte dispositif sur la page de résultats)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/ba324c08-3b5b-442d-8bb8-26e5f16f9ed0)

Pb : Le passage entre la liste des résultats et la fiche dispositif n'est pas assez marqué. 
cf vidéo : https://github.com/betagouv/mission-transition-ecologique/assets/47628484/c5397e3e-970c-47cc-ae9a-de330d8dd68e

**Comment by oumeimaelisbihani** [comment]
@jbledevehat à tester ici >> https://tee-preprod-pr946.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani peux tu regénérer le lien stp ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux  https://tee-prod-pr946.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
hello @oumeimaelisbihani, je ne vois pas le changement d'état au tap sur une fiche dispositif sur écran mobile.
Tu peux vérifier ?

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani pour info c'est le ticket #906  dont je te parlais

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani super le hover des cartes ! 
la bordure colorée je ne la vois pas en revanche 🧐

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux 

![Image](https://github.com/user-attachments/assets/fb0cc8c5-a80a-4267-9dbe-aa1d2cdc9d15)

j'ai vérifié et ça marche bien pourtant juste le clic est instantané :/

**Comment by ColineLebaratoux** [comment]
En effet, je le vois sur mon mac, mais pas quand je teste sur mon iphone (safari)


https://github.com/user-attachments/assets/6e2b5b65-630b-41c9-9807-ec1945d6b87f

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux ton safari est bien à jour ? j'ai essayé sur mon iphone sur safari et sur chrome et ça apparait bien !

**Comment by jbledevehat** [comment]
Pour moi tout fonctionne bien :-)
