### ISSUE TITLE
Correction UI topbar

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#869]
Est-ce possible de conditionner le composant pour que les textes ne s'affichent que sur une ligne.
Si le texte est trop grand alors le couper et mettre des points de suspension 
ex : restauration de type rapide qui apparait ici sur 2 lignes

Objectif : diminuer le volume qu'occupe la topbar dans la page pour faire remonter les contenus de la page plus haut

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/4f86a1c9-8189-4ee6-ae7b-1dde4981835a)

**Comment by oumeimaelisbihani** [comment]
@jbledevehat à tester ici >> https://tee-preprod-pr945.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
hello @oumeimaelisbihani ! 
Peux-tu regénérer ce lien stp ?

**Comment by oumeimaelisbihani** [comment]
Salut @ColineLebaratoux comme c'était un fix mineur c'est déjà en prod du coup tu peux le voir directement ici https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat/projet/plan-action-eco-energie/visite-energie-cci?choix-du-parcours=j-ai-un-projet&siret=44474511100021&effectif=PE&objectifs=ma+performance+%C3%A9nerg%C3%A9tique par exemple

**Comment by ColineLebaratoux** [comment]
merci !
