### ISSUE TITLE
réduire l'espacement entre les cartes dispositifs

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#876]
Pour gagner de la place, réduire l'espacement entre les cartes dispositifs (sur les pages annuaires, les pages de résultats et les fiches projets) 

[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6799-393495&t=R0KBIlbFHfDTZJj1-1)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/8643a673-73a9-4e66-9899-08d5ac501c7f)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/906
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/868
```

**Comment by ttdm** [comment]
Est ce que ce choix de spacing te convient ?

Liens vers les 3 endroits où il y a des listes de programmes : 

- https://tee-preprod-pr990.osc-fr1.scalingo.io/projets-entreprise
- https://tee-preprod-pr990.osc-fr1.scalingo.io/questionnaire/resultat/projet/isolation-thermique?choix-du-parcours=j-ai-un-projet&siret=83014132100034&effectif=TPE&objectifs=rénover+mon+bâtiment
- https://tee-preprod-pr990.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=83014132100034&effectif=TPE&locaux=proprietaire&mobilite=maximum&matieres-premieres=oui&tri-dechets=non&dechets=non&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat

**Comment by ColineLebaratoux** [comment]
Hello @ttdm 
Merci ! tu pourras regénerer ces liens à ton retour stp ?

**Comment by ttdm** [comment]
@ColineLebaratoux les liens sont regénérés

**Comment by ColineLebaratoux** [comment]
très bien !
