### ISSUE TITLE
Sur la fiche dispositif, corriger le niveau de l'ancre au clic sur "contactez un conseiller"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#879]
Sur la fiche dispositif, corriger le niveau de l'ancre au clic sur "contactez un conseiller" car le titre est caché derrière la sticky top bar. 

actuel : 

![Image](https://github.com/user-attachments/assets/3fdd49a8-c809-4665-8c50-80705ce97fbc)

cible : 

![Image](https://github.com/user-attachments/assets/aaead903-300e-422f-b40d-aa4b7610f225)

**Comment by yvalentin** [comment]
Ca a été fixe avec dans la partie intégration des projet (release/project)

**Comment by dolemoine** [comment]
je cloture car comme précisé, ça a été fix lors de l'intégration des projets
