### ISSUE TITLE
Bug: la taille de la compagnie n'est plus envoyé dans Brevo (contact)

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#884]
!! !!une analyse plus conséquent des aures champs doit être faite afin d'éviter d'utiliser le `otherdata` !!

La taille de la compagnie n'est plus envoyé dans Brevo (contact)

![Image](https://github.com/user-attachments/assets/033f3f03-46dd-499d-a548-a3d2121e177f)

Une correction semble necessaire afin de retour le comportement et les data attendu.

La régression provient de la refacto effectué lors de la suppression de publicode dans le front.

```ts
// apps/web/src/service/api/opportunityApi.ts:59
companySize: (this.getFromUsedTrack(TrackId.StructureWorkforce, PublicodesKeys.Workforce) as unknown as number) ?? undefined,
```

`PublicodesKeys.Workforce` n'existe plus dans le code front de vuejs

A remplacer par :
```ts
companySize: TrackStructure.getSize() ?? undefined,
```

Le back doit aussi être changer en conséquent :
```ts
// libs/backend-ddd/src/opportunity/infrastructure/api/brevo/brevoContact.ts:66
...(contact.companySize && { TAILLE: convertCompanySize(contact.companySize) })
```

**Comment by ttdm** [comment]
@jbledevehat 

J'ai fix la donnée dans brevo mais je m'apercois que la transmission à BPI ne doit plus fonctionner depuis assez longtemps non plus.
Je m'intérroge sur ce que je dois transmettre.

J'ai l'impression qu'on transmettait à BPI un nombre d'employé estimé à partir de la question sur les tailles. 1 si TPE, 20 pour les PE, 50 les ME... ça te parle ? je recommence à transmettre cette information (en espérant que c'était bien la même que précédemment) ? 

Les autres options seraient de transmettre un texte "entre X et Y salariés" ou un label "TPE" ... 

Si c'est peu important, on doit pouvoir choisir l'option qui nous semble la plus intéressante. Si BPI est pointilleux sur nos transmissions, le mieux serait que tu me donnes un contact tech de chez eux.
