### ISSUE TITLE
Problèmes de navigation entre la liste de résultats en 2 tabs / fiche dispositif / fiche projet

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#902]
1) Au clic sur une **carte projet** depuis la liste de résultats (onglet "des idées d'actions à mettre en place"), il faudrait que le bouton "retour" de la fiche projet amène sur la liste de résultats des projets avec une ancre au niveau de la carte projet en question.

2) Au clic sur une **carte dispositif** depuis la liste de résultats (onglet"vos aides financières"), il faudrait que le bouton "retour" de la fiche dispositif amène sur la liste de résultats des aides avec une ancre au niveau de la carte dispositif en question.

3) Au clic sur une **carte dispositif depuis une fiche projet**, il faudrait que le bouton "retour" de la fiche dispositif amène sur la fiche projet avec une ancre au niveau de la carte dispositif en question (rubrique "mes aides")

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/903
```

**Comment by dolemoine** [comment]
@ColineLebaratoux @jbledevehat voici le lien de l'app pour tester : 

https://tee-preprod-pr939.osc-fr1.scalingo.io/

Pour des raisons techniques, je n'ai pas trouvé d'autre solution que d'ajouter un petit timeout le temps que l'élément soit bien chargé sur la page et que le scroll puisse être fonctionnel. Dans les 2 premiers cas c'est vraiment infime comme impact sur l'UX et ce n'est pas visible par l'utilisateur, dans le troisième, ça se fait clairement plus sentir, mais je n'ai pas d'autre solution pour le moment.

**Comment by jbledevehat** [comment]
Pour le 3ème cas, c'est vraiment très étrange ce mouvement... 
Si on enlève les ancres, est-ce qu'on revient au même endroit dans la page ou forcement en haut de page ? Parlons-en rapidement. Car j'aurai bien enlevé toute ces ancres ça me perturbe, j'aimerai retrouver le retour en arrière naturel du navigateur.
Je pense qu'il faut en tout cas enlever l'ancre sur le 3, car ce mouvement n'offre pas une bonne UX.

**Comment by dolemoine** [comment]
Je suis assez d'accord avec le comportement inconfortable pour l'utilisateur sur le cas numéro 3, malheureusement je n'ai pas vraiment d'autre solution tout de suite. 
Ok pour en discuter à plusieurs

**Comment by dolemoine** [comment]
après discussion avec @jbledevehat  : suppression du comportement de retour sur le cas 3, identifier s'il est possible d'avoir un retour naturel du navigateur au click sur les boutons retour.

**Comment by dolemoine** [comment]
ce que je peux proposer pour le moment, c'est un "retour naturel" sur les boutons "Retour" quand on est dans le détail d'un projet ou d'une aide (comportement identique au retour du navigateur comme mentionné par @jbledevehat), puis conserver un comportement classique sur le fil d'arianne (navigation avec "chargement" de la page donc alignement en top).
pour le troisième cas, le problème rencontré vient du fait qu'on a une animation sur la page détail d'un projet (un accordéon se déroule à l'affichage de la page) et on est contraint d'attendre la fin de cette animation pour effectuer un scroll (même un scroll navigateur). L'option pour pouvoir retomber sur l'état du scroll sur le bouton "Retour" (pas sur le lien dans le fil d'arianne) serait de supprimer cette animation.

dans un premier temps, les modifs sur les premiers points sont testables ici : https://tee-preprod-pr939.osc-fr1.scalingo.io

**Comment by ColineLebaratoux** [comment]
hello @ttdm 
est-ce que tu pourrais regénérer ce lien stp ?

**Comment by ttdm** [comment]
Salut, j'ai travaillé jeudi et non vendredi, désolé ! 
Pour info, cette branche est en prod donc tu peux regarder en prod si le comportement te convient !

**Comment by jbledevehat** [comment]
C'est bon pour moi tout roule, j'envoie en Done
