### ISSUE TITLE
Amélioration des URL pour faciliter la navigation

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#903]
Améliorer l’url en ajoutant l’historique de navigation, pour permettre de retracer le parcours de consultation d'une fiche dispositif depuis une fiche projet.
=> Questionnaire/projet/ID projet/ID dispositif 

ex : 
https://mission-transition-ecologique.beta.gouv.fr/questionnaire/projet/plan-action-eco-energie/visite-energie-cci?choix-du-parcours=je-ne-sais-pas-par-ou-commencer...

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/902
```

**Comment by yvalentin** [comment]
@ColineLebaratoux 
Lien de validation
https://tee-preprod-pr912.osc-fr1.scalingo.io/
