### ISSUE TITLE
Faire évoluer les intitulés sur la barre d'onglet sur mobile

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#905]
**Problème :** 
Le titre "des idées d'actions à mettre en place" est trop long et ne donne pas assez de visibilité sur le deuxième onglet sur mobile. 

![Image](https://github.com/user-attachments/assets/d83930a8-c35f-403c-a3b8-6f5320bceb83)

_Originally posted by @yvalentin in https://github.com/betagouv/mission-transition-ecologique/issues/760#issuecomment-2236447674_

*
---

**Proposition :** 
  - [ ] Sur mobile, afficher uniquement "Idées d'actions" pour le premier onglet et "Aides financières" pour le deuxième.

<img width="409" alt="Capture d’écran 2024-07-22 à 12 18 59" src="https://github.com/user-attachments/assets/73e7b7e2-74dc-492b-8eb4-210891671a0c">

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux à tester ici >> https://tee-preprod-pr1043.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
c'est étrange, ça fonctionne parfaitement sur chrome, safari sur mon mac. Mais sur mon iphone safari (dont j'ai vidé le cache), voilà ce qui se passe : 

https://github.com/user-attachments/assets/f0104937-1c93-48ab-a78e-9c017f6a5719

**Comment by ColineLebaratoux** [comment]
Toujours pareil sur mon iphone... que ce soit sur safari ou chrome. Je comprends pas pourquoi. 
@yvalentin ou @ttdm vous pourriez tester de votre côté svp?

**Comment by dolemoine** [comment]
Jai vérifié de mon côté, c'est ok pour moi avec Firefox sous Android

**Comment by ColineLebaratoux** [comment]
Merci @dolemoine
Je valide le ticket du coup
