### ISSUE TITLE
Revoir les conditions d’affichage de l'encart « Complétez votre profil...» sur la fiche projet

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#907]
Aujourd'hui, lorsqu'une entreprise ne souhaite pas renseigner son SIRET et passe par le parcours "je préfère compléter mes informations manuellement", l'encart _"Complétez votre profil en 2 minutes et accédez aux aides éligibles pour votre entreprise"_ s'affiche par défaut sur les fiches projets dans la rubriques "mes aides"

![Image](https://github.com/user-attachments/assets/111a802f-eaa4-43ed-afc5-6c422113a865)

- [x] Il faudrait afficher les dispositifs pour lesquels elle est éligible (on a l'info puisqu'on dispose de sa région, de son secteur d'activité et du nb d'employés)

**Comment by oumeimaelisbihani** [comment]
@jbledevehat pour le test https://tee-preprod-pr929.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
C'est bon

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux @jbledevehat remarques de @ttdm, peut etre à réfléchir dans un prochain ticket : 

1. si une entreprise passe par j'ai un projet en tête puis retourne sur l'annuaire alors elle va voir le bandeau. ça peut être surprenant comme information pour cette entreprise puisqu'elle a déjà renseigné ses informations.

2. J'ai l'impression qu'à la place du bandeau, il lui faudrait une information discrète d'élligibilité sur la page. J'imagine un petite encart en couleur, d'après les informations transmises, vous êtes éligibible ou non à cette aide. Plus une deuxième ligne qui explique que toutes les dispositifs sont affichés sur le cataloguqe et qu'en suivant un lien, l'entreprisene verra alors que les projets auxquelle elle est éligible.

Techniquement, ça revient à séparer dans le v-if isCatalogDetail && hasSiret et isCatalogDetail && !hasSiret
