### ISSUE TITLE
[XP Cannes] - Écriture des pages projet sectorielles

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#909]
- [ ] Ajouter des projets liés au secteur de l'hotellerie restauration pour l'expérimentation 
   - Voici la liste des actions FTD suite à réception et retraitement des données par l'équipe FTD : https://docs.google.com/spreadsheets/d/1LffE_GKtQG745Iyi9wnq8u8Vt12uu-AUd1FD_QajE90/edit?gid=484431621#gid=484431621
   - Possibilité de croiser avec l'Ecolabel Européen qui s'applique aux d'acteurs de l'hébergement uniquement https://www.ecolabeltoolbox.com/fr/ecolabel-europeen 
   - Ainsi que le Guide ADEME Tourisme Durable : https://www.monreseaupro-pnrsud.fr/media/uploads/2022/03/hebergeurs-touristiques-quelles-actions-mettre-en-place-pour-un-tourisme-durable-ademe.pdf

![Image](https://github.com/user-attachments/assets/d567d2fa-aab1-4647-bedf-27c1a96a0ac3)
![Image](https://github.com/user-attachments/assets/73c2c8e1-0aa6-47dd-8173-19f1ce635477)
![Image](https://github.com/user-attachments/assets/08952f36-b921-4d2b-a2e5-474103e1ae90)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1083
```

**Comment by jbledevehat** [comment]
Oui il faut ajouter les actions FTD dans les tuyaux

**Comment by mpiac** [comment]
Je me permets d'ajouter ce guide sur la restauration à la doc existantes : https://librairie.ademe.fr/developpement-durable/4893-guide-pratique-bretagne-restaurants-commerciaux-quelles-actions-mettre-en-place-pour-un-tourisme-durable-.html
