### ISSUE TITLE
Afficher la thématique RH par défaut sur la page de résultats

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#913]
Dans les pages de résultats des 2 parcours, la thématique RH devrait s'afficher par défaut (aucune question ne filtre cette thématique)

[exemple du bug sur ce lien](https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=37804750001242&effectif=TPE&locaux=non&mobilite=oui&matieres-premieres=oui&tri-dechets=oui&dechets=oui&gestion-eau=oui&energie=oui&audit=oui&selection-audit=certification&selection-audit=autre&selection-audit=je-ne-sais-pas#questionnaire-resultat)

bug discuté avec @ttdm

**Comment by dolemoine** [comment]
@jbledevehat @oumeimaelisbihani les corrections seront push demain une fois les droits github récupérés

**Comment by dolemoine** [comment]
@jbledevehat  c'est dispo ici pour validation : https://tee-preprod-pr942.osc-fr1.scalingo.io
