### ISSUE TITLE
revoir le filtrage sur la taille de l'entreprise

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#920]
En s'appuyant sur les colonnes "<5" "Entre5et20" ... ajouter 2 colonnes min/max taille entreprise à privilégier cad à afficher ou non.

**Comment by ttdm** [comment]
// micro-entrepreneur => gérer à part  "je suis micro-entrepreneur"
    // Moins de 9
    // entre 10 et 19
    // entre 20 et 49
    // entre 50 et 249
    // 250 to 499
    // Plus de 500
    // https://www.economie.gouv.fr/cedef/entreprises-categories#:~:text=Analyse%20statistique%20%3A%20les%20cat%C3%A9gories%20d'entreprises&text=une%20microentreprise%20est%20une%20entreprise,pas%202%20millions%20d'euros
