### ISSUE TITLE
Revoir les marges des cartes (pb de bandes blanches latérales)

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#932]
Le problèmes est de voir des cards avec des bandes blanches soit en haut et en bas, soit à gauche et droite. cf :

![Image](https://github.com/user-attachments/assets/363ace3f-82f3-4687-8e04-624c917b2f97)

![Image](https://github.com/user-attachments/assets/00a6e893-1f1d-44b7-80bf-f3ecf45ea3ea)

**Comment by oumeimaelisbihani** [comment]
@jbledevehat https://tee-preprod-pr938.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
Merciiii
