### ISSUE TITLE
Supprimer les acordeons sur les projets

### ISSUE THREAD

**Issue by jrayneau** [betagouv/mission-transition-ecologique#948]
Supprimer les accordéons sur les fiches projets. (pas d'usage)

- [ ] supprimer la ligne supérieur 
- [ ] conserver les séparateurs entre les sections 
- [ ] supprimer les icônes "arrow" pour déployer/replier l'accordéon
- [ ] en profiter pour remonter le contenu de la fiche projet en veillant toujours à l'alignement entre le bouton "copier le lien" et le titre la section "qu'est-ce que c'est"
<img width="1439" alt="Capture d’écran 2024-08-30 à 11 45 43" src="https://github.com/user-attachments/assets/e3077880-198f-4359-85b1-1f3ada24b1af">

**Comment by dolemoine** [comment]
@ColineLebaratoux pour test : https://tee-preprod-pr1089.osc-fr1.scalingo.io/
