### ISSUE TITLE
Problème longueur du menu Catalaogues

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#954]
A l'ouverture du menu catalogue celui-ci est fixe et se masque lorsque la fenêtre a une certaine taille. De plus elle fait apparaitre une scroll bar horizontal du fait de dépasser.

![Image](https://github.com/user-attachments/assets/570c9f3c-b1c2-4570-80cc-32dcf8112ea4)
![Image](https://github.com/user-attachments/assets/533b2476-2cec-4eca-97e9-72d11a343cb5)

**Comment by dolemoine** [comment]
@jbledevehat pour tester : https://tee-preprod-pr987.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@dolemoine tu pourrais regéréner le lien ? 
je pense que tu peux aussi diminuer la largeur du contenant

**Comment by dolemoine** [comment]
@ColineLebaratoux j'ai regénéré le lien, je regarde demain matin pour réduire la largeur du dropdown

**Comment by dolemoine** [comment]
@ColineLebaratoux modification faite sur la largeur : https://tee-preprod-pr987.osc-fr1.scalingo.io/
