### ISSUE TITLE
Sur les fiches projets ajouter des mentions pour distinguer les types d'aides

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#961]
"Pour étudier votre projet" pour les dispositifs de type "étude", "Formation"

"Pour financer votre investissement" pour les "Financement" "Prêt" "Avantage fiscal"

![Image](https://github.com/user-attachments/assets/56283990-f1b7-4b3d-bc55-6079039516ad)

[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6985-418136&t=zEDuteRH8167Djhy-1)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/224
```

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux à tester ici : https://tee-preprod-pr1030.osc-fr1.scalingo.io/
