### ISSUE TITLE
Correction sur la page de résultats "je ne sais pas par ou commencer"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#967]
- [ ] supprimer la mention de la région sur la phrase introductive.
=> les actions n'ont pas de liens avec le secteur géograpgique
=> permet d'alléger la phrase introductive

- [ ] masquer la mention du nombre de résultats uniquement sur l'onglet "tous" (ça flotte, on ne sait pas vraiment à quoi l'associer)

 [cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6799-391834&t=lWgzFmyvBexq2FIo-1)

- [ ] veiller  à garder le même placement pour le bandeau vert du tag "tous" et celui des tags thématiques

**Comment by dolemoine** [comment]
@ColineLebaratoux, concernant le dernier point, je ne suis pas sûr de tout à fait saisir la demande.
Est-ce qu'il s'agit du bandeau vert suivant : 
![image](https://github.com/user-attachments/assets/7eb31da8-bfd2-45ae-a6af-7a92e6c95543)
Et si oui, qu'entends-tu par "placement [...] des tags thématiques" ?

**Comment by ColineLebaratoux** [comment]
si tu enlèves la mention du nb de résultats avec le bandeau vert (oui c'est bien celui là) pourra remonter plus proche des tags, et sera alors à la même hauteur que les bandeaux thématiques. 
Lorsque l'utilisateur navigue d'un tag à l'autre, les placements des bandeaux sont les mêmes. 

=> je suis claire ? 😅

**Comment by ColineLebaratoux** [comment]
idem pour ce lien 🙏

**Comment by dolemoine** [comment]
@ColineLebaratoux c'est en cours de regénération

**Comment by ColineLebaratoux** [comment]
Parfait ! 

- [ ] Est-ce que tu peux en profiter pour centrer la phrase introductive dans l'espace vert ?

![Capture d’écran 2024-09-10 à 14 05 34](https://github.com/user-attachments/assets/653e80c9-4dfd-47bf-8a47-3ffb6dc12eb8)
![Capture d’écran 2024-09-10 à 14 06 46](https://github.com/user-attachments/assets/ccfa18eb-b95f-49b0-9bd6-79f5c9580d9c)
Merci !

**Comment by ColineLebaratoux** [comment]
C'est parfait comme ça, merci !
