### ISSUE TITLE
S'assurer que les liens ne sont pas obsolètes (pour aller plus loin / les étapes d'un dispositif)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#969]
S'assurer que les liens stockés dans la rubrique "pour aller plus loin " des fiches projets et dans les étapes des fiches dispositifs ne sont pas obsolètes

J'ai fait le test avec la formation ademe pour laquelle le premier lien [était cassé :](https://formations.ademe.fr/tmp/01001119-1720429428-9999999-9a7cecf0ea4d98c67fe5e83d4a1d40b9.pdf) 
https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat/projet/sensibilisation-equipes/formation-engager-entreprise-transition-ecologique?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=41513341200023&effectif=TPE&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=je-ne-sais-pas&gestion-eau=je-ne-sais-pas&energie=non&audit=non

![Image](https://github.com/user-attachments/assets/e7f79691-cc35-472f-8827-d03aca4a3d72)

=> @yvalentin @ttdm A t-on déja défini un process et une fréquence pour vérifier nos liens ?

**Comment by ttdm** [comment]
Je test tous les liens des étapes à chaque maj des programmes. 
Je peux étendre ce test aux liens de pour aller plus loin.

**Comment by ttdm** [comment]
@jbledevehat @ColineLebaratoux @celinebagault Je profite de cette PR pour faire un point sur les erreurs/points où il faut être attentif dans les données des dispositifs. Je tag qui pour ce point qualité de la donnée dans le futur ? 

@yvalentin Je te tag si tu veux suivre la discussion sur la gestion des "cas particuliers" (géographiques / sectoriels)

Voici donc la liste de mes remarques / points d'attention : 
1. le champ "url" des programmes n'a pas l'air d'être utilisé du tout. C'est normal ? 
2. un certain nombre de ces liens sont perrimés. Il faut tenir ces liens à jour ? Si oui, je vous donnerai la liste des erreurs. (une 15aine)
3. dans 2 dispositifs, il y a des "zones géographiques spécifiques". C'est un champ qui n'est pour l'instant pas utilisé du tout. Ce que je vous propose c'est d'ajouter automatiquement un élément à la liste "éligibilité spécifiques" avec le contenu de ce champ et on verra si un jour on le filtre automatiquement (c'est compliqué parce qu'il faut mapper la france entière et gérer le cas où on a une adresse exacte (via le siret) et le cas où on a pas d'adresse mais juste la région! ) 
4. la colonne "éligibilité NAF" pour les éligibilités plus fines que le code naf de niveau 1. ça concerne pour l'instant 12 programmes en prod. Sur ces 12 programmes, la moitié environ fait l'objet d'un publicode écrit manuellement pour réaliser le filtrage plus finement. Pour les autres le filtrage est réalisé via les colonnes de cade naf de niveau 1 (AAgriculture,BIndustries...) . Dans un cas comme dans l'autre, le texte de "éligibilité NAF" est affiché dans la rubrique "Secteur d'activité" des "conditions d'éligibilités" des fiches programmes. Je propose 2 solutions : soit j'édite manuellement les publicodes des 6 programmes où ça n'est pas fait (envron1H/programme) soit au contraire, on revient pour tous ces programmes à un filtrage via le naf de niveau 1 et un simple message pour les conditions plus complexe. A noter qu'il y a 2 inconvénients majeurs à réaliser un filtrage fin : a) le résultat du filtrage est toujours faux si on a pas le naf exact (si on a pas le siret) b) le code publicode est alors statique et ne suis plus l'évolution du baserow. Pour ces deux raisons, je conseille de simplement laisser une indication écrite et de faire le filtrage sur le code naf1. 


Pour finir, quelques petites modifications à effectuer : 

- [ ] dans navires-energies-propre, corriger le champs éligibilité spécifique pour qu'il s'agisse bien d'une liste. 
- [ ] dans fond-vert-territoires-d-industrie : problème sur le lien du champ étape 1 qui n'existe plus
- [ ] dans ecogestes-paca: problème de validation d'un lien du champ étape 1, ce n'est pas un lien c'est un mail, ça ne fonctionne pas en prod : https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/ecogestes-paca
- [ ] industries-vertes: problème de validation d'un lien du champ étape 2, ce n'est pas un lien, c'est un mail.

**Comment by ttdm** [comment]
Suite à une visio avec JB : 

1. c'est normal, c'est pour pouvoir remonter au programme de base, si besoin (demande d'opérateur / de curieux...)
2. Oui il faut les tenir à jour, mettre un warning. 
3. ajout d'un élément dans élibigilité spécifique et suppression de la colonne en question
4. ajout de l'info dans éligibilité spécifique et supression des modifs manuelles du publicodes. 

3 et 4 seront fait dans un nouveau ticket à mettre au prochain sprint.

**Comment by ttdm** [comment]
Pour info, voici la liste des problèmes détectés dans les projets : 
Warning : dans le projet "Plan d’action économies d’énergie", id 4, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Majeur: dans le projet "Plan d’action économies d’énergie", id 4 'erreur de validation de lien dans le champs "pour aller plus loin", https://www.cci.fr/crise-energetique/entreprises-20-conseils-pour-faire-baisser-votre-facture-denergie
Warning : dans le projet "Eclairage LED", id 2, programme liée inconnu : cedre-investissement, programme lié supprimé
Majeur: dans le projet "Eclairage LED", id 2 'erreur de validation de lien dans le champs "pour aller plus loin", https://librairie.ademe.fr/ged/207/renover-eclairage-tertaire-011133.pdf
Warning : dans le projet "Panneaux solaires", id 5, programme liée inconnu : solaire-ready, programme lié supprimé
Warning : dans le projet "Réduction des emballages", id 3, programme liée inconnu : cedre-investissement, programme lié supprimé
Warning : dans le projet "Réduction des emballages", id 3, programme liée inconnu : charte-zero-dechet-plastique, programme lié supprimé
Warning : dans le projet "Bilan de gaz à effet de serre", id 1, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Audit énergétique", id 14, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Isolation thermique", id 15, programme liée inconnu : cedre-investissement, programme lié supprimé
Warning : dans le projet "Isolation thermique", id 15, programme liée inconnu : investour, programme lié supprimé
Warning : dans le projet "Isolation thermique", id 15, programme liée inconnu : sites-touristiques-exemplaires, programme lié supprimé
Warning : dans le projet "Isolation thermique", id 15, programme liée inconnu : solaire-ready, programme lié supprimé
Majeur: dans le projet "Isolation thermique", id 15 'erreur de validation de lien dans le champs "pour aller plus loin", https://www.baisseleswatts.fr/actualites/equipement-energetique/quel-est-le-meilleur-isolant-thermique
Warning : dans le projet "Plan d'action mobilité", id 16, projet liée inconnu : 104, projet lié supprimé
Warning : dans le projet "Plan d'action mobilité", id 16, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Majeur: dans le projet "Plan d'action mobilité", id 16 'erreur de validation de lien dans le champs "pour aller plus loin", https://librairie.ademe.fr/ged/1555/plan-mobilite-entreprise-010502.pdf
Warning : dans le projet "Acquérir un véhicule propre", id 18, programme liée inconnu : sites-touristiques-exemplaires, programme lié supprimé
Warning : dans le projet "Acquérir un véhicule propre", id 18, programme liée inconnu : cheque-transition-bioethanol, programme lié supprimé
Warning : dans le projet "Acquérir un véhicule propre", id 18, programme liée inconnu : recharge-vehicule-electrique, programme lié supprimé
Warning : dans le projet "Acquérir un vélo", id 19, programme liée inconnu : sites-touristiques-exemplaires, programme lié supprimé
Warning : dans le projet "Plan d’action eau", id 20, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Majeur: dans le projet "Plan d’action eau", id 20 'erreur de validation de lien dans le champs "pour aller plus loin", https://www.cci.fr/actualites/10-conseils-aux-entreprises-pour-une-sobriete-en-eau
Warning : dans le projet "Plan d’action déchets & pertes matière", id 21, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Plan d’action déchets & pertes matière", id 21, programme liée inconnu : charte-zero-dechet-plastique, programme lié supprimé
Warning : dans le projet "Tri des déchets", id 23, programme liée inconnu : cedre-investissement, programme lié supprimé
Majeur: dans le projet "Tri des déchets", id 23 'erreur de validation de lien dans le champs "pour aller plus loin", https://librairie.ademe.fr/ged/7183/tri-a-la-source-des-9-flux-011719.pdf
Warning : dans le projet "Sensibilisation des équipes", id 26, programme liée inconnu : investour, programme lié supprimé
Majeur: dans le projet "Sensibilisation des équipes", id 26 'erreur de validation de lien dans le champs "pour aller plus loin", https://www.economie.gouv.fr/mission-innovation/les-actions-vertes/sensibilisation-aux-ecogestes
Warning : dans le projet "Recrutement", id 27, programme liée inconnu : investour, programme lié supprimé
Warning : dans le projet "Recrutement", id 27, programme liée inconnu : sud-pret-climat, programme lié supprimé
Majeur: dans le projet "Recrutement", id 27 'erreur de validation de lien dans le champs "pour aller plus loin", https://librairie.ademe.fr/ged/2528/sme-fiche-regerent-energie-2015.pdf
Warning : dans le projet "Formation environnement", id 28, programme liée inconnu : investour, programme lié supprimé
Warning : dans le projet "Formation environnement", id 28, programme liée inconnu : sud-pret-climat, programme lié supprimé
Warning : dans le projet "Stratégie RSE", id 30, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Diagnostic à 360° sur la transition écologique", id 31, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Plan de transition bas carbone", id 32, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Plan de transition bas carbone", id 32, programme liée inconnu : sud-pret-climat, programme lié supprimé
Warning : dans le projet "Plan d’adaptation au dérèglement climatique", id 33, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Majeur: dans le projet "Plan d’adaptation au dérèglement climatique", id 33 'erreur de validation de lien dans le champs "pour aller plus loin", https://librairie.ademe.fr/ged/6327/entreprise_comment_prendre_des_decisions.pdf
Warning : dans le projet "Communication & labélisation", id 35, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Éco-conception d’un produit ou service", id 36, programme liée inconnu : cedre-premier-pas, programme lié supprimé
Warning : dans le projet "Éco-conception d’un produit ou service", id 36, programme liée inconnu : cedre-investissement, programme lié supprimé
Warning : dans le projet "Récupérateur d’eau de pluie", id 71, programme liée inconnu : cedre-investissement, programme lié supprimé
Warning : dans le projet "Récupérateur d’eau de pluie", id 71, programme liée inconnu : sites-touristiques-exemplaires, programme lié supprimé


Les problèmes détectés dans les problèmes sont dans la PR chore: update program (les projets sont à jour d'où l'absence de PR malgré les warnings).
