### ISSUE TITLE
Correction de couleurs 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#972]
Je groupe plusieurs corrections de couleurs sur un même ticket. N'hésitez pas à dégrouper si ce n'est pas optimal :

- [ ] Sur les fiches projets eau dont le fond est bleu foncé, le titre doit apparaitre en blanc = contraste accessible
![Image](https://github.com/user-attachments/assets/8623783c-ab54-4f9b-beea-b5e297344e16)

---
- [ ] Pour fiches projets "Construction & rénovation" et "analyses environnementales" (fond violet) mettre le titre en blanc = contraste accessible

![Image](https://github.com/user-attachments/assets/07806164-ff6d-4cba-be72-88002cc599fa)
---

- [ ] Sur la page de choix de thématiique du parcours "j'ai un projet en tête", la couleur du fond de la thématique eau n'est pas la bonne. Les couleurs sont des nuances des couleurs principales à 30% : 

couleur à corriger : 
![Image](https://github.com/user-attachments/assets/526f3d88-1ae8-4419-985e-86adb95f7d17)

![Image](https://github.com/user-attachments/assets/1a773b5d-3c7d-441a-8dd9-145953a7190f)

[cf figma](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6514-275288&t=iYFDmRjNIG5P6Kf4-1)

**Comment by jbledevehat** [comment]
Voir si faut ajouter la carte #753 avec celle-ci

**Comment by dolemoine** [comment]
@ColineLebaratoux, j'ai push plusieurs modifs de fonds sur l'utilisation de la charte définie, on utilise bien à chaque fois des nuances (30% et 10%) des couleurs principales définies maintenant.
Il restera, quand tu peux, à me faire parvenir les ajustements te permettant d'obtenir le resultat sur ta palette de couleurs (car tu verras qu'on obtient pas les mêmes que toi en appliquant les pourcentages définis)

pour la couleur dans les fiches projets, je me suis rendu compte qu'on prenait toujours celle du theme principal auquel est rattaché le projet, par ex: 

Audit énergétique est rattachée à énergie et rénovation, avec énergie en theme principal.
Si sur la liste des projets, je sélectionne le tag "rénovation", j'ai bien le projet qui apparait, mais lorsque je vais sur la fiche projet, c'est la couleur du theme énergie que je récupère (jaune donc).
Pour le moment, vu qu'on ne conserve pas les informations sélectionnée lorsque la page est rafraîchie, on peut récupérer la bonne couleur dans un parcours "normal" de l'utilisateur (avec utilisation des liens et bouton retour).

Tu peux tester les modifs  ici : https://tee-preprod-pr1045.osc-fr1.scalingo.io/


PS: ça inclut aussi les modifs pour la carte #753

**Comment by ColineLebaratoux** [comment]
Bien vu ! En effet, pour reprendre ton exemple, idéalement il faudrait que la fiche projet "audit énergétique" ait la couleur de la thématique sélectionnée par l'utilisateur : jaune pour énergie, violet pour rénovation. 
A mettre dans un autre ticket du coup ?

**Comment by dolemoine** [comment]
je l'ai traité dans ce ticket du coup, tu peux tester en passant par le catalogue de projet :  https://tee-preprod-pr1045.osc-fr1.scalingo.io/projets-entreprise
avec la thématique énergie puis Audit énergétique
puis avec la thématique rénovation puis Audit énergétique

on prend bien la couleur de la thématique sélectionnée

**Comment by ColineLebaratoux** [comment]
parfait !

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine 
on a un problème d'accessibilité sur la page de choix de thématique version mobile. 
Est-ce qu'on pourrait mettre les couleurs en 10% sur les fonds ? (version mobile uniquement) 
![Image](https://github.com/user-attachments/assets/704ec636-b3d0-4b17-a5e0-1576406fda88)
![Image](https://github.com/user-attachments/assets/dbe6baa5-9bc7-40c1-b5f6-73d1377f33ae)
