### ISSUE TITLE
Bug sur les résultats au clic sur  l'un des 4 CTA "je me lance" de la page d'accueil

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#993]
Ce bug fait suite au ticket #322 :
> Au clic sur "je me lance" sur l'une des 4 thématiques, redirection vers le parcours "j'ai un projet en tête", avec la thématique pré-sélectionnée

- [x] Les données de l'entreprise ne sont pas collectées dans la phrase "Voilà une liste de projets pertinents pour votre enterprise.structureSize.undefined du secteur ... en Région ...".

- [x] au clic sur "questionnaire" dans le fil d'ariane, la redirection ne fonctionne pas (ticket #1025)

https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultat?choix-du-parcours=j-ai-un-projet&objectifs=ma+performance+%C3%A9nerg%C3%A9tique&siret=41513341200023&effectif=ME#questionnaire-resultat

![Image](https://github.com/user-attachments/assets/c1271793-19d8-49b5-9b3f-e3f5c7996d95)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1126.osc-fr1.scalingo.io/ le plus simple pour résoudre le bug a été d'enlever la préselection du theme. Est ce que ça peut le faire comme ça?

**Comment by ColineLebaratoux** [comment]
oui de toute façon on va bientôt les faire sauter ces contenus de la page d'accueil avec les 4 CTA
