### ISSUE TITLE
[XP Cannes] - Entretien avec Amélie TORTAY, Responsable du Club des entrepreneurs du Pays Grassois

### ISSUE THREAD

**Issue by RodolpheGagetta** [betagouv/mission-transition-ecologique#997]
Présentation de l'expérimentation cannoise au club des entrepreneurs du pays de Grasse (200 entreprises).

https://www.notion.so/accelerateur-transition-ecologique-ademe/CR-Am-lie-TORTAY-Club-des-entrepreneurs-du-Pays-de-Grasse-4b623b38750f48d19df8589d4a66f7e0

> Accord de participation du club à l'expérimentation (> Mise en relation directes avec les entreprises du tourisme membres du club)
> Mise en relation avec la responsable QSE de l'aéroport de Nice et de l'aérodrome de Mandelieu
> Mise en relation avec la responsable QSE de l'hotel Eden ROC à Antibes

```[tasklist]
### Tasks
- [x] 27/08/24: Relance à Amelie TORTAY > contacts proposés + Calendrier de dispo pour pitch de presentation
```

**Comment by celinebagault** [comment]
Lié à https://github.com/betagouv/mission-transition-ecologique/issues/1012
